### PR TITLE
userscripts/open_download: Flatpak compatibility

### PR DESCRIPTION
**Pull request by tinywrkb**
Make `open_download` compatible with Flatpak.

flatpak-xdg-utils's `xdg-open` send the request to open a file with associated application through XDG Desktop Portal, letting the user select application with the AppChooser Portal.  
In the Flatpak sandbox, we don't know which app would be launched, and we know very little about mime types.  

I also think that `open_download` should wait for `xdg-open` return code. We want to know when `xdg-open` failed, and we want to read the output with `:process`.

### CODE REVIEW

**Comment by tinywrkb** [comment]
2nd push was a minor typo fix.

**Comment by The-Compiler** [comment]
Agreed on both, thanks and sorry for the delay!

cc @t-wissmann who originally wrote the script

**Comment by t-wissmann** [comment]
> I also think that `open_download` should wait for `xdg-open` return code. We want to know when `xdg-open` failed, and we want to read the output with `:process`.

Then, one could even change the last line to
```bash
exec xdg-open "$path"
```

**Comment by tinywrkb** [comment]
> Then, one could even change the last line to
> 
> ```shell
> exec xdg-open "$path"
> ```

Right, I should've noticed this.

**Pull request merged**
