### PR TITLE
Greasemonkey-like Userscript Support

### PR DESCRIPTION
**Pull request by toofar**
Adds support for reading in userscripts from `<datafolder>/greasemonkey` (configurable) and injecting them into pages based on the greasemonkey compatible metadata block.

Tested on (old)webkit and qtwebengine 5.9. qtwebengine 5.7 and below not supported allthough I can add that finicky stuff back in if people actually want it.

Most of the work comes from andor44's fork from a couple of years ago. The impact on the existing codebase is very small. On webkit we manually pick scripts to inject in event handlers on webengine deciding when to inject and on what pages is handled for us.

greasemonkey.py wraps the userscripts in a simple lexical scope along with a bunch of GM_ functions that are useb by various userscripts floating about, certainly not all of the ones listed on the docs page. All the ones we implement should work fine though. Except that GM_xmlhttpRequest is stated in the docs to handle cross-origin requests and due to that being disabled globally on both supported backends we can't. I am going to look into getting that working though. If you want you can pass the `--qt-flag disable-web-security` to enable cross-origin requests globally, which will open that session up to cookie hijacking attacks from random pop-up ads etc.

The scripts currently run in the main javascript "world", meaning they can see all the same stuff you can see when you look at the web inspector console. This is good if you want your scripts to be able to change more about how web pages behave but bad if you are in the habit of running untrusted userscripts. The qtwebengine docs say that other worlds should be able to access the DOM too but my more featureful userscripts all fail to effect the page so I am still looking into whether it is possible to get more isolation without sacrificing features.

https://github.com/andor44/qutebrowser/commit/a19321714a33b6787ac18ba06800c8571fc376ed
https://wiki.greasespot.net/Greasemonkey_Manual:API
https://doc.qt.io/qt-5/qwebenginescript.html

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2867)

### CODE REVIEW

**Comment by The-Compiler** [comment]
As mentioned in the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/CONTRIBUTING.asciidoc) at the top, the new config system will be merged in September, and won't be reviewing PRs for new features until then. You'll also need to update this for the new config (and resolve conflicts if needed) once it is in.

**Comment by toofar** [comment]
Hmmm, that's what I thought but someone said otherwise and that they were you. Whoops. Should I close?

**Comment by The-Compiler** [comment]
I think I told everyone to please come back in September, sorry for the confusion! Whatever you prefer really - we can either look at this PR again in September, or close it now and then you open a new one once the new config is in.

**Comment by toofar** [comment]
Okay, I'll make a new one later and it will be even better. You'll see!

**Comment by The-Compiler** [comment]
re cross-origin `GM_xmlhttpRequest`: I wonder whether it'd be possible to use [QtWebChannel](http://doc.qt.io/qt-5/qtwebchannel-index.html) with a [QNetworkAccessManager](http://doc.qt.io/qt-5/qnetworkaccessmanager.html) to implement it - though then the JS definitely can't run in the main world.

**Comment by toofar** [comment]
Mhmm. I looked at that back then but it segfaulted as soon as used the webchannel. If it keeps doing that when I look again (haha, it's that time already) I guess I'll try an arch chroot or something because it is probably my dodgy frankendebian.

**Comment by The-Compiler** [comment]
FWIW segfaults and PyQt [can be quite tricky sometimes](http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html), but I'm happy to help once I got the new-config branch in :wink:

**Comment by The-Compiler** [comment]
@toofar The new config is in in the meantime, do you want to pick this up again?

**Comment by toofar** [comment]
Yeah, I got the cross origin gm_xhr requests working but there is still a bunch off stuff to look into. It could take some time.
* sometimes get Uncaught ReferenceError: qt is not defined when connecting to the webchannel on the js side. Reproducible so should be able to figure it.
* check the request headers are handled the same as other gm extensions do on other platforms (I've just been checking against chrome with tampermonkey)
* check the request headers and bodies are being treated right when coming from non-utf8 sites and on windows (when forming the QNetworkRequest I am calling str.encode('utf-8') on stuff from the webchannel)
* maybe pull that one javascript template into a seperate file for easier maintanance
* get scripts working in the non-main js world
* rebase
* look into how testable this, add tests
* maybe test with some other popular user scripts, I looked on greasyfork but all the popular ones are for mechanical turk automation, hmm

**Comment by The-Compiler** [comment]
> get scripts working in the non-main js world

FWIW if scripts modify JavaScript stuff on the original site (rather than just the DOM), this isn't going to work.

I took a quick look at how GreaseMonkey itself does this, and it seems like it's using an [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) where it runs the userscript concatenated with the `GM_*` API:

https://github.com/greasemonkey/greasemonkey/blob/10f3ef620c21865cf1db778b4cfd193d31a7f20e/src/user-script-obj.js#L234-L243

I guess qutebrowser could be able to do something similar to that - however, I'm not sure how to make the QWebChannel inaccessible by the website...

**Comment by toofar** [comment]
Yeah I am already doing that ([702371e](https://github.com/qutebrowser/qutebrowser/pull/2867/commits/702371eff37b2dbf8135217342b097aa77786ecc)) and I had an idea about putting a nonce inside the IIFE scope, a different one for each script, and saving them on the python side and throwing out anything that came over the QWebChannel that didn't have a valid one. I wanted to have a go at getting it to work properly first though.

>JavaScript stuff on the original site (rather than just the DOM)

Er, what does this mean, the DOM in other worlds is a shadow of the main one?

**Comment by The-Compiler** [comment]
> Er, what does this mean, the DOM in other worlds is a shadow of the main one?

I'm not sure what happens exactly internally, but it's something like that, yeah - if you e.g. do `window.foo = 23` in one world, it's not visible in another.

**Comment by The-Compiler** [comment]
@toofar what do you think about getting an initial version of userscripts into qutebrowser (maybe without the cross-origin XHR), and then improving on that later? Many people would really like this feature, and I bet it's usable for many (e.g. to block YouTube ads?) without that too.

**Comment by toofar** [comment]
Okay, I havn't done anything to this branch since this PR was opened so I'll finish this coffe and get rebasing.

**Pull request closed without merging**
