### PR TITLE
Per-domain javascript whitelist.

### PR DESCRIPTION
**Pull request by toofar**
Enable or disable javascript for a tab based on current domain or page url. I
know you are waiting to do a proper per-domain settings framework until after
the engine overhaul but I thought I might as well make a stab at making this
generic while I was at it.

[Review on Reviewable](https://reviewable.io/reviews/the-compiler/qutebrowser/1273)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Oh wow. Now I really don't know what to do about this... This is a feature I wanted myself for  months, but I know merging this now will be lots of pain down the road (with the QtWebEngine- and config migration). See https://github.com/The-Compiler/qutebrowser/pull/1155#issuecomment-176632234 too.

**Comment by toofar** [comment]
All good, just close the issue or something. I'm sure people can find it and copy it to their local install if they are desperate. I just implemented this because I thought background js or something might be causing performance issues (turns out that was something else: #1278). I just opened the pr so more people would be aware of it just in case.

**Comment by toofar** [comment]
Changed the domain setting model to be a little more generic (which broke existing keybindings and settings for anyone already using this patch, see commit message) and added cookies whitelist too.

**Comment by paretje** [comment]
Today, pyqt 5.6 merged into Debian testing, and qutebrowser stoped working. I in the end determined that this PR was the source of the problem. It appears it suffers from the same problem fixed (here)[https://github.com/The-Compiler/qutebrowser/commit/37b5f49c8542c04e7aae6ded6e8ab0c6aa5f2010] for qutebrowser. I fixed it for this PR (here)[https://github.com/paretje/qutebrowser/commit/a8486e0f8ef1088a2487613aaa6810206c8439f5]

**Comment by paretje** [comment]
In https://github.com/paretje/qutebrowser/commit/73ce5de91f0836ffed25efdb798d79ee053ea63c I fixed the PR with the updated decorations.

**Comment by paretje** [comment]
I updated the PR to fix the import of webview in https://github.com/paretje/qutebrowser/commit/95681f3ebe2970645462048163920fac60da97aa .

**Comment by The-Compiler** [comment]
With the `new-config` branch, this likely requires a complete rewrite. I'm going to (finally) look at per-domain settings as soon as there's `config.py` support, probably somewhen in September.

In the meantime I'm closing this. I added the patch to #27 though to make sure it doesn't get lost. Thanks for your contribution, I'm sure it's a good help when I'll implement this with the new config!

**Comment by nepumuk-fs** [comment]
Why not add whitelisting of JavaScript to content.host_blocking.whitelist ?

**Comment by The-Compiler** [comment]
@nepumuk-fs Huh, I don't follow. Those two things are unrelated to each other.

**Pull request closed without merging**
