### PR TITLE
Bitwarden password fill based off qute-lastpass

### PR DESCRIPTION
**Pull request by JonnyHaystack**
Hi,

I've made a qute-bitwarden userscript by modifying qute-lastpass. It's mostly the same as qute-lastpass except that the json returned by bitwarden is slightly different and Bitwarden uses a session hash which I store using keyctl (I took inspiration from [bitwarden-rofi](https://github.com/mattydebie/bitwarden-rofi)).

I've also added the parameter `--auto-lock` (as in bitwarden-rofi) which allows you to specify the timeout after which you must re-enter your master password.

Relevant issue here: #5030

### CODE REVIEW

**Comment by wisdomlight** [comment]
Newbee alert:
I know this is silly but - How do I download the script?? :-) 
or do i need to copy and paste it to a file on my machine?

**Comment by mschilli87** [comment]
@wisdomlight: Have a look at [the corresponding page in the documentation](https://qutebrowser.org/doc/userscripts.html).

**Comment by arza-zara** [comment]
@wisdomlight: In qutebrowser git repo:
```
git fetch origin pull/5031/head:bitwarden
git checkout bitwarden
```
(or automate with [hub](https://hub.github.com/) or [git config](https://gist.github.com/piscisaureus/3342247))

On this page: "Files changed" -> "..." -> "View file" -> "Raw" gives you a [direct link](https://raw.githubusercontent.com/JonnyHaystack/qutebrowser/master/misc/userscripts/qute-bitwarden).

**Comment by The-Compiler** [comment]
Thanks! I'm not too happy about yet another fork of the same script - but since probably all those scripts will be replaced by plugins at some point (see #30), I'm okay with it.

**Comment by JonnyHaystack** [comment]
Agreed, and I am looking forward to the plugin support :smiley:

**Pull request merged**
