### PR TITLE
Fix issue #2900

### PR DESCRIPTION
**Pull request by cryzed**
I hope this works correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2902)

### CODE REVIEW

**Comment by cryzed** [comment]
I'm not quite sure how to go about that. I came up with this:

```python
    def test_only_window_implies_with_private(self, fake_window, fake_history,
                                              tmpdir, sess_man):
        fake_window.private = True
        fake_history([Item(QUrl('http://www.qutebrowser.org/'), 'foobaz',
                           active=True)])

        session_path = tmpdir / 'baz.yml'
        try:
            sess_man.save(str(session_path), only_window=True)
        except sessions.SessionError:
            # This seems to happen on some systems only?!
            pass
        else:
            data = session_path.read_text('utf-8')
            assert r'title: "foobaz"' in data
```

But I'm mostly unfamiliar how to write proper tests with py.test and how all of qutebrowser's state handling and internals work. I also added a `private` attribute to `FakeMainWindow`. Unfortunately I have trouble running the tests with `py.test`:

```usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --faulthandler-timeout=70 --instafail --benchmark-columns=Min,Max,Median
  inifile: /home/user/Documents/Code/qutebrowser/pytest.ini
  rootdir: /home/user/Documents/Code/qutebrowser
```

**Comment by jgkamat** [comment]
I've attached a git format patch which adds a test that should check if this is working (which it is). 

I'm not sure if this is the 'right' way to write the test though :)

```
From 9af3e4ca33310209b055fa7e681e684c247894ef Mon Sep 17 00:00:00 2001
From: Jay Kamat <jaygkamat@gmail.com>
Date: Sun, 13 Aug 2017 17:15:04 -0700
Subject: [PATCH] Test for saving a session with --only-active-window

---
 tests/end2end/features/private.feature | 23 +++++++++++++++++++++++
 1 file changed, 23 insertions(+)

diff --git a/tests/end2end/features/private.feature b/tests/end2end/features/private.feature
index 55ded35d7..81a58ac34 100644
--- a/tests/end2end/features/private.feature
+++ b/tests/end2end/features/private.feature
@@ -153,3 +153,26 @@ Feature: Using private browsing
               - history:
                 - url: http://localhost:*/data/numbers/1.txt
                 - url: http://localhost:*/data/numbers/2.txt
+
+
+  Scenario: Saving session with only-active-window
+        When I open data/numbers/1.txt
+        And I open data/numbers/2.txt in a new tab
+        And I open data/numbers/3.txt in a private window
+        And I open data/numbers/4.txt in a new tab
+        And I open data/numbers/5.txt in a new tab
+        And I run :session-save --only-active-window window_session_name
+        And I run :window-only
+        And I run :tab-only
+        And I run :session-load -c window_session_name
+        And I wait until data/numbers/5.txt is loaded
+        Then the session should look like:
+            windows:
+                - tabs:
+                    - history:
+                        - url: http://localhost:*/data/numbers/3.txt
+                    - history:test_saving_session_with_onlyactivewindow
+                        - url: http://localhost:*/data/numbers/4.txt
+                    - history:
+                        - active: true
+                          url: http://localhost:*/data/numbers/5.txt
-- 
2.11.0
```

**Comment by jgkamat** [comment]
@cryzed any problem with this branch? If you're busy or some other reason like that I'll finish pushing this through for you.

I'm assuming it was just a mistake though, which happens `:)`

**Comment by cryzed** [comment]
No, I'm just an idiot. I was playing around with the delete branch feature in my IDE and didn't notice that I pushed it to the remote repository as well, I'm sorry.

If you still have the changes in a local clone, that would be great.

**Comment by jgkamat** [comment]
I'll re-create the pull request, no problem! `:D`

**Comment by Ape** [comment]
For future reference, everything you pushed to a pull request is still available on GitHub even if you delete the branch.

Just look for the latest code change message on the pull request, and open the commits. In this case you can still get to this page: https://github.com/qutebrowser/qutebrowser/pull/2902/commits/6f04771bb37d990f359c7c4a0b9447edfb9b7210

In addition, you can recover the deleted commits locally (unless git garbage collection has removed them). See `git reflog` for more information.

**Comment by cryzed** [comment]
Noted, thank you @Ape.

**Comment by lahwaacz** [comment]
I also vaguely remember that GitHub used to have something like an "Undelete branch" button... but maybe only if you used the web interface to delete it in the first place.

**Comment by cryzed** [comment]
It does actually, it's right there. I just thought it would be a better idea to simply recreate the pull request since it was already closed.

**Pull request closed without merging**
