### PR TITLE
Added setting to disable back and forward buttons on mice

### PR DESCRIPTION
**Pull request by nicholaslantz**
Added a new boolean setting called "input.mouse_backforward".  It enables the back and forward buttons on the mouse when it's set to true--this is the default.  When it's false QuteBrowser will not navigate through the browser's history as those buttons are pressed.

This change would resolve issue #5239.

### CODE REVIEW

**Comment by nicholaslantz** [comment]
Sure, makes sense to keep all mouse settings in a subcategory.  Thanks for the tip on `renamed:`.  I'll look into implementing those changes.

**Comment by mschilli87** [comment]
I honestly don't like the term `backforward`. Maybe we can come up with a better name by finding an alternative description? What do we achive by 'enabling the forward and backward buttons on the mouse'? Do we 'allow history navigation with the mouse (`input.mouse.history_navigation`)? Do we want to refer to this feature as 'time travel' (`input.mouse.time_travel`)? Maybe we could have a look how other brothers or the mouse manufacturers refer to this feature (I doubt it will be 'backforwarding' :wink:).

**Comment by nicholaslantz** [comment]
Okay, I've changed the setting names per the comments.  Good input on calling the setting `back_forward_buttons`, that does sound better.

I'm pretty sure I changed all of the references to `input.rocker_gestures` to the new name--I only found 2 references in `browser/eventfilter.py`.  Could there be any other references I missed?

**Comment by The-Compiler** [comment]
There were a few (unimportant) occurrences in `tests/manual/mouse.html` as well - I updated those and the changelog:

- ef0482cab Update tests/manual/mouse.html
- 0e02c910b Update changelog

Thank you!

**Pull request merged**
