### PR TITLE
Added searchengine completion

### PR DESCRIPTION
**Pull request by rsteube**
Added "Searchengines" section below History. Updated when config changes.
see #32

### CODE REVIEW

**Comment by The-Compiler** [comment]
Looks good from a quick look - @rcorre want to help review this as well?

**Comment by rcorre** [comment]
LGTM. Thanks for updating the tests as well! I'm not sure what's up with the [appveyor test](https://ci.appveyor.com/project/The-Compiler/qutebrowser/build/master-4638/job/nsnjtpdjj00plqxn). Environmental problems? Looks like some unix path separators snuck in there:

```
ERROR: InvocationError: 'C:\\projects\\qutebrowser\\.tox\\unittests-frozen/build/run-frozen-tests'
```

**Comment by rsteube** [comment]
Ah, so thats why it failed. Couldn't figure it out from the log - didn't see the slashes.

**Comment by The-Compiler** [comment]
That shouldn't be the issue - Windows can handle slashes as path separators fine **most of the time**...

This looks more like it somehow had a hang and then timed out after 1h. No idea why. I triggered a rebuild.

**Comment by The-Compiler** [comment]
I finally got around to looking at this - sorry for the delay! I was busy with exams.

What about adding a space after all names, like this:

```diff
diff --git a/qutebrowser/completion/models/urlmodel.py b/qutebrowser/completion/models/urlmodel.py
index f99437dd5..eb3d69ee9 100644
--- a/qutebrowser/completion/models/urlmodel.py
+++ b/qutebrowser/completion/models/urlmodel.py
@@ -78,7 +78,7 @@ class UrlCompletionModel(base.BaseCompletionModel):
         self._history.cleared.connect(self.on_history_cleared)
 
         for se_name, se_url in sorted(config.section('searchengines').items()):
-            self.new_item(self._searchengine_cat, se_name, se_url)
+            self.new_item(self._searchengine_cat, se_name + ' ', se_url)
         objreg.get('config').changed.connect(self.on_searchengines_changed)
 
         objreg.get('config').changed.connect(self.reformat_timestamps)
```

I didn't adjust the tests accordingly yet, but it seems to me like this would make things more practical?

**Comment by rsteube** [comment]
Sorry, but could you explain what makes this more practical? I've added the space and don't see a distinct difference in behaviour at the moment (apart from the second space on tab completion).

**Comment by The-Compiler** [comment]
When you tab complete a search engine, you'd usually want to type the thing you want to search next I'd say. When tab-completing to `:open ddg |` you can type that right away, with `:open ddg|` you'd need to type the space first. No big feelings here either way though!

**Comment by rsteube** [comment]
No, didn't mind adding it - just couldn't see the difference since i had no similar entries to tab over. When there is just one matching entry you automatically get the space. It's misssing when there are mutliple entries to tab over.

**Comment by The-Compiler** [comment]
Looks like this broke the tests: https://travis-ci.org/qutebrowser/qutebrowser/jobs/198596210

**Comment by The-Compiler** [comment]
I'm closing this in the meantime, until the new completion is in. I'm sure someone can pick it up and update it once the new completion is in, though. Thanks for the contribution anyways!

**Pull request closed without merging**
