### PR TITLE
Add comments for quickmarks and bookmarks.

### PR DESCRIPTION
**Pull request by ottopiramuthu**
Allows easier organization of urlmarks.

### CODE REVIEW

**Comment by jgkamat** [comment]
The quickmark/bookmark file is automatically overwritten by qb, so any 
comments you have in the file will get overwritten. Because of that, I'm not 
sure how useful this will be.

**Comment by The-Compiler** [comment]
That's a good point - I mentioned this PR in a [previous Reddit discussion](https://www.reddit.com/r/qutebrowser/comments/ddodbu/comments_in_quickmarks_file/).

**Comment by The-Compiler** [comment]
Thanks @ottopiramuthu!

From the Reddit discussion, it looks like some people indeed do manage the bookmarks/quickmarks file by hand, so I think this is fine - doesn't hurt either way.

With the bookmarks revolution (#3855) I think we should slightly change how things are stored to properly accommodate that, see https://github.com/qutebrowser/qutebrowser/pull/3855#issuecomment-557903957

**Comment by jcguu95** [comment]
I have a feeling that once the amount of bookmarks gets larger than ~100, it is going to be hard to retrieve what we really want. It gradually becomes a huge hole where things rarely come back.

I have some idea to change this, and since I really love qutebrowser, perhaps one day I'll implement it. Before that, let me lay some of them out. Please feel free to leave any feedback.

------

+ **Tagging** is necessary. After a bookmark is added, there should be a prompt for us to enter comments and tags. While adding tags, existent tags will be suggested (using narrowing-fuzzy-search). Each entry can have multiple tags. While searching/retrieving, users are allowed to use regex on bookmarks' names and tags. Some thing like `+math-grocery+routine` should be possible. There should also be another system that help unify tag names: it should help the user to merge tags like `repos, repo, repository` together easily.

+ **comments, date-time** should also be set. This allows users to search/retrieve bookmarks with context. Users can add comments to (non)-existent bookmarks anytime, automatically time-stamped.

+ **org-files** as database. If you haven't heard of org-mode, please do a quick search on youtube. There are lots of short videos showing its power. Sure, it is native in emacs, but we don't need emacs to parse it. It is **just an extended markdown**! It is easy to read for humans and easy to parse for computers. With suitable plugins of `vim`, `emacs`, `vs-code`, `atom`, .. you can read, handle, edit entries quite easily. If you want to create "folder hierarchy for your bookmarks", `org` allows you to do it easily manually too!

**Comment by jgkamat** [comment]
jcguu95 writes:

> I have some idea to change this, and since I really love qutebrowser, 
> perhaps one day I'll implement it. Before that, let me lay some of them out. 
> Please feel free to leave any feedback.

Note that rcorre has a large pull for bookmarks already, if you wanted to 
avoid conflicts.

> + **org-files** as database. If you haven't heard of org-mode, please do a 
> quick search on youtube. There are lots of short videos showing its power. 
> Sure, it is native in emacs, but we don't need emacs to parse it. It is 
> **just an extended markdown**! It is easy to read for humans and easy to 
> parse for computers. With suitable plugins of `vim`, `emacs`, `vs-code`, 
> `atom`, .. you can read, handle, edit entries quite easily. If you want to 
> create "folder hierarchy for your bookmarks", `org` allows you to do it 
> easily manually too!

I don't think org is the right format for something that will need to 
primarily be machine-generated and machine-consumed. Even a csv file would 
suffice for all the features you've described.

**Comment by The-Compiler** [comment]
@jcguu95 Like @jgkamat said, much of that is already implemented in #3855 by @rcorre. Note that any further discussion about the on-disk format likely will be pointless, we've had enough of that in #882.

**Comment by jcguu95** [comment]
Yeah.. I was there but forgot, and was not aware that the pull request has been reviewed recently. Seems that Thanks for all the hard work! I look forward to the new features :)

**Pull request merged**
