### PR TITLE
mypy: use annotations for typing instead of comments

### PR DESCRIPTION
**Pull request by stimut**

### CODE REVIEW

**Comment by stimut** [comment]
There is still one use of typing in comments:

```
$ grep --perl-regexp '# type: (?!ignore)' -R qutebrowser scripts tests
qutebrowser/utils/utils.py:            with open(fn, 'rb') as f:  # type: IO
```

However I don't think there is a way of changing that usage.

**Comment by The-Compiler** [comment]
What happens if you drop the annotation entirely? If it's really needed, according to https://www.python.org/dev/peps/pep-0526/#where-annotations-aren-t-allowed it should be possible to do:

```python3
f: IO
with ... as f:
```

**Comment by stimut** [comment]
Removing the annotation entirely raises an `Incompatible types` error when running `mypy`.

I've gone ahead and changed it as you suggested where the type is defined on the line above.

**Comment by The-Compiler** [comment]
Thanks! After some `misc_checks.py` adjustments in 6d04af727d613ea7cfdd25867a2b76003af07e66 I was able to add checks to disallow type comments (33c80e386cee4dfa5db5d8eb2a25442fa8fb864c) as well as `typing.` annotations (d5b08d1516048266c1f592288d4a0bf77863cd1f).

This way, I won't forget to make the same adjustments when merging older PRs, and new changes will also need to be consistent with your changes.

Thanks again for all your work! If you want to continue with some similar (but perhaps a tiny bit less mechanical) changes, maybe #176 would be a good place to continue - most notably, there's still a lot of `tmpdir` usage in tests, see https://github.com/qutebrowser/qutebrowser/issues/176#issuecomment-706325142.

However, if you'd rather take a break or not continue working on things like this at all, no worries!

**Pull request merged**
