### PR TITLE
Remove vim modelines in favor of .editorconfig

### LINKED ISSUE #7100: Remove vim modelines
We have an `.editorconfig` which is more universal, any editor should default to utf-8 nowadays, and `ft=python sts=4 sw=4 et` should be clear for `.py` anyways.

### PR DESCRIPTION
**Pull request by pylbrecht**
Removing vim modelines could be done using two one-liners. Most of the vim modelines
were followed by an empty line, so this one-liner took care of these ones:

```sh
rg '^# vim: .+\n\n' -l | xargs sed -i '/^# vim: /,+1d'
```

Then some of the vim modelines were followed by a pylint configuration line, so running
this one-liner afterwards took care of that:

```sh
rg '^# vim:' -l | xargs sed -i '/^# vim: /d'
```

Additionally some cleanup was necessary:
* removing vim-modeline hint from contributing docs
* removing the modeline pylint checker

To keep old pull requests from bringing back vim modelines, I added a check to
`scripts/dev/misc_checks.py`.

---

Closes #7100

### CODE REVIEW

**Comment by pylbrecht** [comment]
Most relevant changes are:
- `scripts/dev/misc_checks.py`
- `scripts/dev/pylint_checkers/qute_pylint/modeline.py`
- `.pylintrc`
- `scripts/dev/run_vulture.py`

**Review by toofar — APPROVED** [review]
Looks okay to me. Although I really haven't touched misc_checks before (or used it, tried it now and it chokes on all the random stuff in my checkout). So you might want to wait for @The-Compiler to have another look.

image

I was going to suggest that we could use plain open().readlines() instead of this tokenize thing because it might be faster, but it bails on some encoding issues. And it's plenty fast anyway.

One thing we are a bit cautious of with all the pending autoformatter changes is that they are going to cause conflicts with the pending PRs. But this one should be fine.

**Comment by toofar** [comment]
Oh and personally I would prefer that this kind of thing was done in two commits: automated changes in one commit, manual changes in one (or more) commit. ;)

**Comment by pylbrecht** [comment]
> Oh and personally I would prefer that this kind of thing was done in two commits: automated changes in one commit, manual changes in one (or more) commit. ;)

I fully agree with this! The automated changes completely drown the manual ones.
I did some surgery on the commit history.

**Comment by The-Compiler** [comment]
We have a lot of files! :sweat_smile: 

Looks great, and one more v3.0.0 issue down - thanks!

**Pull request merged**
