### PR TITLE
handle <EOL> of `:config-write-py` generated file

### PR DESCRIPTION
**Pull request by lxhillwind**
#3195 Sorry for not totally obey contents described in [contributing doc](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc), but I think this pull request contains very, very few modification to code base.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3196)

### CODE REVIEW

**Comment by lxhillwind** [comment]
The newest commit is about adjustment of `TestConfigPyWriter.test_output`.

**Comment by lxhillwind** [comment]
Should I fix the 'line too long' in my previous commit, and push a new commit here?

**Comment by The-Compiler** [comment]
Yes please! Don't worry about the other failing test, looks like that's flaky.

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
