### PR TITLE
Filter installed dictionaries using a regex to ensure correct name

### LINKED ISSUE #3634: Crash with invalid dictionary filenames
Looks like this doesn't get caught properly on init:

```
16:39:44 DEBUG    init       app:_init_modules:468 Initializing websettings...
16:39:45 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==1.1.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 188, in main
    return app.run(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 137, in run
    init(args, crash_handler)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 163, in init
    _init_modules(args, crash_handler)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 469, in _init_modules
    websettings.init(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 215, in init
    webenginesettings.init(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 297, in init
    websettings.init_mappings(MAPPINGS)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 198, in init_mappings
    mapping.set(value)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 72, in set
    self._set(value, settings=settings)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 154, in _set
    filenames = [self._find_installed(code) for code in value]
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 154, in <listcomp>
    filenames = [self._find_installed(code) for code in value]
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 143, in _find_installed
    local_filename = spell.local_filename(code)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 64, in local_filename
    all_installed = local_files(code)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 51, in local_files
    for matching_dict in sorted(matching_dicts, key=version, reverse=True):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 36, in version
    .format(filename))
ValueError: the given dictionary file name is malformed: /usr/share/qt/qtwebengine_dictionaries/en-US.bdic
```

https://crashes.qutebrowser.org/view/63cd0d83

cc @elshize

### PR DESCRIPTION
**Pull request by elshize**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3702)

*Edit by @The-Compiler to auto-close the issue: Fixes #3634*

### CODE REVIEW

**Comment by elshize** [comment]
Fixes #3634

**Comment by The-Compiler** [comment]
This seems to [fail the tests](https://travis-ci.org/qutebrowser/qutebrowser/jobs/352095814#L573) and I'm also not sure if it's a good solution, as it hides errors. I think it'd be better to show an error to the user, as they intended to install a dictionary but messed it up somehow (I assume the crash report was with a manual download/rename somehow).

**Comment by elshize** [comment]
I guess you're right. Will do that soon.

**Comment by elshize** [comment]
Should I give a warning or an error message?

**Comment by elshize** [comment]
I'm having a problem with capturing the warning message in `test_version`. Even though I capture it, it fails with:
```
E       Failed: Got logging message on logger message with level WARNING: Found a dictionary with a malformed name: malformed_filename!
```

What am I doing wrong?

**Comment by The-Compiler** [comment]
Seems to work fine on Travis? The only issue I can see is that [spell.py is not fully covered anymore](https://travis-ci.org/qutebrowser/qutebrowser/jobs/354372208#L773).

**Comment by The-Compiler** [comment]
Thanks for the contribution and your patience!

**Pull request merged**
