### PR TITLE
Add userscript qute-keepassxc

### LINKED ISSUE #6017: Adopting qute-keepassxc userscript
Hi,

I am the author of [qute-keepassxc](https://github.com/ususdei/qute-keepassxc) - a userscript to fetch login credentials from an open KeepassXC database via its native browser extension API.

Installing and updating this userscript as a separate git clone is not really conveniant as one of its user pointed out recently (ususdei/qute-keepassxc#7).
I think the most comfortable way to use this script were as part of `qutebrowser` itself.

So this issue is mainly an upfront question on whether you would be willing to adopt and maintain my script as part of qutebrowser or if that required any significant changes first?
If so, I would gladly prepare a PR against qutebrowser next.

Thanks!

### PR DESCRIPTION
**Pull request by ususdei**
This PR adds my userscript `qute-keepassxc` to fetch credentials from KeepassXC using its browser protocol from https://github.com/ususdei/qute-keepassxc to qutebrowser itself.

Please forward any issues arising with this userscript directly to me.

Closes #6017

### CODE REVIEW

**Comment by ususdei** [comment]
Meh, one check confuses markdown underlines in my documentation with conflict markers... :-/

Any alternative syntax preferences on this?

**Comment by toofar** [comment]
Just make the headers `#` prefixed instead of underlined I guess.

Have you any thoughts on pros and cons of using the browser integration vs the secret service integration? I haven't used the browser integration before (I wonder how much of the protocol was designed with webextensions in mind and isn't relevant here?) but I'll put some notes on the secret service integration.
1. The secret service spec says implementors can negotiate algorthim's for encrypting secrets in flight but I'm not sure if this is used in practice. So perhaps it would be more open to sniffing than this.
2. Apparently the secret service spec doesn't specify a schema for how to request secrets so at least when using keepassxc and the keying python module you have to put custom `service` and `username` attributes on the entries because the keys in the request from DBus doesn't match keepasscs's internal names for things. So if this works just looking at URL it's probably easier to get started with (even with having to generate keys).
3. For the secret service integration you can mark only certain folders as accessible by that API, is that the case for the browser integration too?

**Comment by The-Compiler** [comment]
Feel free to keep the underlines as-is, I'll instead make the script checking for it a bit more clever.

**Comment by ususdei** [comment]
Ahh, I just pushed an updated version.
When your patch for the script arrives, I might revert this one. The pipeline needs to be retriggered anyway.
Otherwise feel free to take this PR as it is now.

Regarding the secret service integration:
When I wrote this userscript KeepassXC did not yet support the secret service but I took a look at its documentation later on.
(I haven't tried it myself so I could be wrong in some points).

1. That might be a problem but from what I read, its even worse. The secret service does not require any authentication whatsoever. So every program with access to your DBus can probably query all your exposed secrets.
2. Indeed, it feels like you have to duplicate all fields to be accessible from the secret service and then again you have to implement the logic to map URLs to secrets yourself. Maybe I'm missing something but I definitely prefer the browser API here. And can you handle TOTP tokens via the secret service? The browser API has special support for them and I am currently toying with adding that to this userscript, too.
3. The browser API will ask you everytime you query an entry if this request shall be allowed. You can then accept the request, deny it or permanently allow it. In that case KeepassXC will add a marker to this database entry that your tool (identified by the encryptedly stored ID) may query this entry without further questions. So this does not impose a certain folder structure on my database but I can decide for every entry how it shall be exposed.

**Comment by toofar** [comment]
>1. That might be a problem but from what I read, its even worse. The secret service does not require any authentication whatsoever. So every program with access to your DBus can probably query all your exposed secrets.

Yep, while the keepass DB is unlocked.

> 2. And can you handle TOTP tokens via the secret service?

idk, I use my phone for that. I wouldn't be surprised if it didn't work with it.

> 3. The browser API [does <snip>]

The secrets service integration displays a balloon notification in the system tray when something reads from it! It doesn't prompt for permission or anything. When the DB locks it raises, but only on the workspace keypass is on.

Anyway, sounds like the browser API integration is much more mature.

**Comment by The-Compiler** [comment]
Sorry for the delay - looks reasonable, thanks!

**Pull request merged**
