### PR TITLE
Show hostname in history page.

### PR DESCRIPTION
**Pull request by imransobir**
Like so:
d

### CODE REVIEW

**Comment by The-Compiler** [comment]
LGTM - the old version doesn't show it, but that's fine I guess.

**Comment by imransobir** [comment]
Do you mean the non-javascript page?

**Comment by The-Compiler** [comment]
Yep.

**Comment by imransobir** [comment]
@The-Compiler anything else pending here?

**Comment by The-Compiler** [comment]
Good timing, just wanted to give it another try 😆 Probably ready to merge, just didn't get to it yet!

**Comment by The-Compiler** [comment]
Yup, looks good - thank you!

**Pull request merged**
