### PR TITLE
PAC: fix isPlainHostName()

### PR DESCRIPTION
**Pull request by kiryl**
Fix isPlainHostName() implementation and add test-case for it.

Signed-off-by: Kirill A. Shutemov <kirill@shutemov.name>

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! @abbradar want to take a quick look too?

**Comment by abbradar** [comment]
Seems okay to me, thanks!

**Comment by kiryl** [comment]
I've removed few more double-escaping cases.

@abbradar does it look okay to you?

**Comment by The-Compiler** [comment]
Not so sure anymore about not needing tests for those as they're coming from an existing PAC  implementation 😆 

I guess they were there because it originally used to be a string, not its own file.

**Comment by kiryl** [comment]
On Tue, Feb 21, 2017 at 04:40:48AM -0800, Florian Bruhin wrote:
> I guess they were there because it originally used to be a string, not its own file.

That's my understanding too.

-- 
 Kirill A. Shutemov

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
