### PR TITLE
Added userscript to handle 1password

### PR DESCRIPTION
**Pull request by mkonig**
Hi

I used https://github.com/tomoakley/dotfiles/blob/master/qutebrowser/userscripts/1password and adapted it to linux.
In addition I added a feature that opens the default vault of 1password  if the script can not find an entry for the current website.
The user can then select any entry from his vault and the information is then pasted into the website.

### CODE REVIEW

**Comment by The-Compiler** [comment]
@tomoakley mind giving this a look?

@mkonig Could you please add this to the userscript readme (see the failing [misc checks](https://github.com/qutebrowser/qutebrowser/pull/6456/checks?check_run_id=2791195421) and also take a look at the [shellcheck output](https://github.com/qutebrowser/qutebrowser/pull/6456/checks?check_run_id=2791195579) (both notes and warnings)?

**Comment by mkonig** [comment]
Hi. @The-Compiler could you check again. I think I fixed all issues.

**Comment by The-Compiler** [comment]
Sorry for the delay. I'll get back to this ASAP.

**Comment by tomoakley** [comment]
Sorry I completely dropped the ball on this. Your additions and refactors look great @mkonig! I will update my local version tomorrow and give it a try ✨

**Pull request merged**
