### PR TITLE
Add setting to always whitelist current navigation

### PR DESCRIPTION
**Pull request by jgkamat**
Prevents ERR_BLOCKED_BY_CLIENT when navigating. 

See #273. I could add a dialog maybe but that seems like it would be more complicated with callbacks, and I didn't want to touch much because you were thinking about pulling this out to use a plugin api (and this might get canned because of that).

I'm not sure if this is a good name, or if this should be enabled by default.

On qtwebkit, the given URL seems to be outdated (dosen't get updated on redirects) like it does on qtwebengine, I'm not sure what a good way of handling that would be.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4425)

### CODE REVIEW

**Comment by mschilli87** [comment]
To me it is not clear from the description what this option does.
What is "the current URL being visited"? Does it mean that any page I open won't be blocked in the future?
How can anything be blocked then?

**Comment by jgkamat** [comment]
For example, I pulled [this ad from ddg](http://duckduckgo.com/y.js?u3=https%3A%2F%2Fr.search.yahoo.com%2Fcbclk%2FdWU9MURERDMzMUYwMDY5NDZGNiZ1dD0xNTQyMjY5Njk1NDg1JnVvPTc0MTQ4NDg4MDcwODMzJmx0PTImZXM9SWxiYlExNEdQUy5zZG5PLg--%2FRV%3D2%2FRE%3D1542298495%2FRO%3D10%2FRU%3Dhttps%253a%252f%252fwww.bing.com%252faclick%253fld%253dd3uwVljCI4D7l-62jkERnFwjVUCUz0uHecqNasWTgTqaJTF6X-lNuFCSsdVe7RWpqDnhKK6iISpxof6mJPvWpqxwTXfuPp4SP_W8XvioXlh5XuLB9Mrms1yRfxm631i754idCUNOtkywszGMN6cHWuaIW0wiUaoSX-fOaEExt7lv37NbQS%2526u%253dhttp%25253a%25252f%25252ftracker.marinsm.com%25252frd%25253fcid%25253d901pdb6671%252526mid%25253d901n7v6848%252526mkwid%25253dLEM8aR7m%252526pcrid%25253d74148488070833%252526pkw%25253dcomputer%252526pmt%25253dbe%252526pdv%25253dc%252526lp%25253dhttp%25253a%25252f%25252faltfarm.mediaplex.com%25252fad%25252fck%25252f12309-80731-2060-1%25253fcid%25253d290627002%252526lid%25253d57675690022%252526st%25253dcomputer%252526VEN1%25253dLEM8aR7m%25252c74148488070833%25252c901n7v6848%25252cc%252526VEN2%25253dbe%25252ccomputer%252526MPRE%25253dhttp%2525253A%2525252F%2525252Faltfarm.mediaplex.com%2525252Fad%2525252Fck%2525252F26965-198869-27909-9%2525253F%2526rlid%253d75e802bac3bb11f8f4635957e944bd31%2FRK%3D2%2FRS%3DuEWYe4nG4WziqtLrJCX_ZpRYQSY-&ad_provider=yhs&vqd=3-145386581413505888393855907573646659728-86080836945795330682221437997241418804). If you click it with the adblocker on, it will block your navigation. This PR passes that navigation, while retaining blocking for things you're not navigating directly to. Ads in general come from requests that aren't tied to the main navigation request and that's how they are blocked. For example, 'http://googleadservices.com/' is blocked by the host blocker, which blocks youtube ads. With this PR, it will let you navigate to 'http://googleadservices.com/' despite that entry.

**Comment by mschilli87** [comment]
@jgkamat: My comment was more meant as a motivation to improve the description to make it clear.
Maybe something like 'Ignore host blocker for direct navigation requests.'?

**Comment by jgkamat** [comment]
Florian Bruhin writes:

> Can you explain in what scenarios this would be useful? When navigating to a site which is on the blacklist, while it won't outright fail, the page will likely be very broken, since it can't load any of its resources.

This is mainly useful for clicking on ad links, for example, on the search:

https://duckduckgo.com/?q=google+ads&ia=web

There is the ad link

https://duckduckgo.com/y.js?u3=https%3A%2F%2Fr.search.yahoo.com%2Fcbclk%2FdWU9OTYwREIwRkUxNDI1NEU4MSZ1dD0xNTUxNDU4ODE0NTA0JnVvPTc2ODI4NDMzMDQwOTU3Jmx0PTImZXM9YU1tdjdoc0dQU18zUGQ3LiZqZT05ZWJjODVlOC0zYzQxLTExZTktOWNhNC0zODYzYmI0ODNlZDAtN2ZjOWIzNjZjNzAwJnVpPTYyLjI0NS4xOS4xODAmanQ9MTU1MTQ1ODgxNDUyMCZwcD1uMQ--%2FRV%3D2%2FRE%3D1551487614%2FRO%3D10%2FRU%3Dhttps%253a%252f%252fwww.bing.com%252faclick%253fld%253de3yaZ2BFqQgsrVmIdFBSfMHzVUCUyHABKQwqCrYpOoHQoE1_XFP6hyicuW-AcvGFR0T31WCKSF7zhWhrzbNlittGO79dmPrh9e6FyIrV77qCz3eHNnRmxLRLLA8T_NCgKHWs5mYksKO5CtPsrVUsLaStOkKv2kDezCg8dtZ_nZH0HbzfPL%2526u%253daHR0cCUzYSUyZiUyZmNsaWNrc2VydmUuZGFydHNlYXJjaC5uZXQlMmZsaW5rJTJmY2xpY2slM2ZsaWQlM2Q0MzcwMDAyNDk5MzMzNjU4OCUyNmRzX3Nfa3dnaWQlM2Q1ODcwMDAwMzE3MzY2MDg0MSUyNiUyNmRzX2VfYWRpZCUzZDc2ODI4NDMzMDQwOTU3JTI2JTI2ZHNfdXJsX3YlM2QyJTI2ZHNfZGVzdF91cmwlM2RodHRwcyUzYSUyZiUyZmFkcy5nb29nbGUuY29tJTJmc3RhcnQlMmYlM2Zzb3VyY2VpZCUzZGF3byUyNnN1YmlkJTNkdXMtZW4tYWRvbi1iaS1hdy1jLWJrX2RmXzEtZXhhY3QhbzIlN2UlNWIqR0NMSUQqJTVkJTdlJTViKktleXdvcmRJRColNWQlN2UlNWIqR0NMU1JDKiU1ZCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bSUzZGNwYyUyNnV0bV9jYW1wYWlnbiUzZDEwMDU5NDQlMjUyMCUyNTdDJTI1MjBBZFdvcmRzJTI1MjAlMjU3QyUyNTIwRFIlMjUyMCUyNTdDJTI1MjBFU1MwMSUyNTIwJTI1N0MlMjUyME5BJTI1MjAlMjU3QyUyNTIwVVMlMjUyMCUyNTdDJTI1MjBlbiUyNTIwJTI1N0MlMjUyMERlc2t0b3AlMjUyMCUyNTdDJTI1MjBCaW5nJTI1MjBTRU0lMjUyMCUyNTdDJTI1MjBCS1dTJTI1MjAlN2UlMjUyMFBsYXRpbnVtJTI1MjBFeGFjdCUyNnV0bV90ZXJtJTNkZ29vZ2xlJTI1MjBhZHMlMjZ1dG1fY29udGVudCUzZFVTX0VOX0V4YWN0X1N1cGVyX0JLV1NfR29vZ2xlJTI1MjBBZHM%2526rlid%253d6753d489b8e11369d44388f0d91ff16c%2FRK%3D2%2FRS%3DM93GAR.R5uZh1rt6VqvYgfFIazQ-&ad_provider=yhs&vqd=3-290278960675707112934818136930492920960-108929116537270968391169528762858329968

which you can navigate just fine to ads.google.com/start (which isn't blocked
by default)

I find I never actually want to navigate and browse a site in the ad block
list (that's what the whitelist is for), but I do want to pass through ad
redirects to normal sites, while still having the block entry for indirect
requests.

It would be nice if we got some sort of page load 'id' to associate different
requests as part of one page load, but I don't think we have that.

**Comment by The-Compiler** [comment]
Sorry, but I'd rather not get this in - it'll inevitably lead to hard-to-debug "why does this page load but not really" kind of issues.

The ideal solution for this would be error pages with some kind of button to whitelist all direct connections that host for the current qutebrowser session (see

**Pull request closed without merging**
