### PR TITLE
mypy: use from-import in some qutebrowser/browser files

### PR DESCRIPTION
**Pull request by stimut**
Not all files in `qutebrowser/browser` have been included as I would
like the PRs to be easily reviewable. Let me know if you would prefer
larger PRs instead.

See #5396

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! Are you doing those changes manually or do you have them automated in some way?

Given that the next release should be v2.0.0 which drops Python 3.5 support, I wonder if it'd make sense to also rewrite those comments to annotations while you're at it? Then I'd have to at least drop Python 3.5 from CI first.

On the other hand, those changes can probably be automated (at least partially) using [com2ann](https://github.com/ilevkivskyi/com2ann) - so let me know what you prefer!

**Comment by stimut** [comment]
I was doing the changes manually. It's really not difficult, but I guess there are a lot.

I think rewriting the comments to annotations makes sense, and I am happy to include them in this PR. Using com2ann (thanks for pointing me to that!) will make that easier. I'll send an updated PR shortly.

**Comment by stimut** [comment]
By the way, I think it's a good idea to do the `com2ann` runs at the same time as the import changes (rather than leaving it as one big automated separate PR or similar), as there are sometimes some manual formatting fixes needed from my brief experience with it.

**Comment by stimut** [comment]
It looks like the `continuous-integration/travis-ci/pr` job is failing, as it is still using Python 3.5. From what I can tell, all the other tests/checks have already been moved to GH Actions, so assuming the Travis config is not needed anymore (as Python 3.5 doesn't need to be tested anymore), I have created #5835.

**Comment by The-Compiler** [comment]
I now dropped Python 3.5 support in 685a66280aff600a83aa30da814aea63f0116c31 so this is ready to merge - thanks for getting the ball rolling!

Do you intend to continue working on this? That'd be awesome, as both of those changes definitely improve code readability quite a bit. Feel free to open a bit bigger PR. I think 100-200 changed lines still would be perfectly fine to review, given that those are relatively trivial changes - but whatever works best for you!

**Comment by stimut** [comment]
> Do you intend to continue working on this? That'd be awesome, as both of those changes definitely improve code readability quite a bit. Feel free to open a bit bigger PR. I think 100-200 changed lines still would be perfectly fine to review, given that those are relatively trivial changes - but whatever works best for you!

Yep, I'm happy to keep working on this. 100-200 line PRs sound good.

**Pull request merged**
