### PR TITLE
Improve open in existing instance speed

### PR DESCRIPTION
**Pull request by user202729**
Partially solves issue #1098.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4506)

### CODE REVIEW

**Comment by jgkamat** [comment]
For me, this seems to open in existing instance even when --temp-basedir is
supplied. I think this is because the basedir gets initialized after the ipc
queryn runs.

**Comment by user202729** [comment]
Actually, it doesn't work too, even without --temp-basedir.

**Comment by user202729** [comment]
The dependency graph looks something like this. Red things are slow and can be removed, green things are required.

Looks like that it's necessary to split `send` and `listen`.

image

**Comment by user202729** [comment]
I reimplemented this and do a force-push, but some of the changes are "dirty" and move code around in somewhat-unexpected ways. It works however.

https://github.com/user202729/qutebrowser/tree/fast-ipc

**Comment by mschilli87** [comment]
@user202729: If you squash the commits, the diff doesn't look very 'dirty' to me:
https://github.com/qutebrowser/qutebrowser/compare/master...user202729:fast-ipc

**Comment by The-Compiler** [comment]
Don't actually squash the commits, though, please - sometimes it's useful to view things with a bit of context. :wink:

I can't seem to reopen the PR - @user202729, can you?

**Comment by user202729** [comment]
Closed PR with force-pushed branch can't be reopened, as the button tooltip said. The only way would be making a new PR.

However I'd look into lazy import first (#153), as that will hopefully reduce the number of code movement required.

**Comment by The-Compiler** [comment]
Lazy importing is probably going to be quite a hack. I think moving things around a bit would be the better solution, if it's enough to make a tangible difference.

**Pull request closed without merging**
