### PR TITLE
scripts/dev/src2asciidoc.py: vim: readonly

### PR DESCRIPTION
**Pull request by blueyed**
Set 'readonly' via Vim modeline in generated scripts.

[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3514)

### CODE REVIEW

**Comment by jgkamat** [comment]
I think you might want to edit the [autogenerated header](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/dev/src2asciidoc.py#L44), so these edits don't get overwritten next time the file is generated

**Comment by blueyed** [comment]
It's in here already: https://github.com/qutebrowser/qutebrowser/pull/3514/files#diff-08e76fb7836503b745e1d25e63f4f413R47.

**Comment by jgkamat** [comment]
Oh whoops, I completely missed that, sorry :)

**Comment by blueyed** [comment]
No worries, thanks for reviewing! :)

**Comment by The-Compiler** [comment]
Good idea, thanks!

**Pull request merged**
