### PR TITLE
Fix searching with leading arguments and ';;'

### PR DESCRIPTION
**Pull request by jgkamat**
Previously, slash searching for things like `-m qutebrowser` would result in an error complaining about "unrecognized argument: qutebrowser".

This PR tries to fix this. Instead of taking a single string, I take in a varargs (as `["--", "-m", "qutebrowser"]` is a valid input).

Let me know if anything seems wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3796)

### CODE REVIEW

**Comment by jgkamat** [comment]
Hmm, I think I'll have to think about not splitting the command a bit. Ideally, I would like `/;;` to work fine, but `:search hi ;; message-info hi` should probably work as well. I don't know if anyone is chaining commands with search, but if they did, this would break it.

Maybe we could have a :search-internal command, which is just the `:search` command, but it dosen't split `;;`. I'm not sure if it's worth the effort to do that, what do you think? :P 

Jseval has the same flag yet, and I don't think anyone has complained about `:jseval 1 + 1 ;; message-info hi` failing, so it might just be ok to add the flag...

**Comment by toofar** [comment]
Yeah I don't know how people are using bindings and such. Though the search command isn't even blocking so putting it last would have the same result.

**Comment by jgkamat** [comment]
Ah, I forgot you could do that, I think that's a good idea to add to the normal search command, let me know if anyone thinks otherwise :)

**Comment by jgkamat** [comment]
Ah, I didn't even think of that, that's a much cleaner solution to this, I'll try to switch it to the alternate method :)

**Comment by toofar** [comment]
Hmm, I'm pretty sure I tested with multiple spaces and it worked as expected.

**Comment by The-Compiler** [comment]
Thanks! I refactored it a bit to reduce code duplication in 6eb8284fe05f9d97573d18ac205d4d83ff375cd0

**Pull request merged**
