### PR TITLE
autoinstall spellcheck dictionaries [WIP]

### LINKED ISSUE #3759: Install dictionaries to standarddir.data() on Qt >= 5.10
Moving this here from #2939 as it probably warrants some more discussion.

In Qt 5.10, I [added](https://codereview.qt-project.org/#/c/201422/) a `QTWEBENGINE_DICTIONARIES_PATH` environment variable to Qt, allowing to customize it so installing dictionaries doesn't require root rights.

With that, it'd be possible for qutebrowser to install dictionaries automatically, without having to run a separate script with root permissions.

Here's how things roughly should look, IMHO:

- qutebrowser should set `QTWEBENGINE_DICTIONARIES_PATH` to something like `os.path.join(standarddir.data(), 'dictionaries')` (probably in `qutebrowser/browser/webengine/webenginesettings.py`)
- The `spell.py` script should be patched to use that path on Qt >= 5.10 (and still use the current system-wide path on older Qt versions)
- Ideally, when setting `spellcheck.languages` to a missing dictionary on Qt >= 5.10, instead of showing a warning, qutebrowser should ask whether to download that dictionary (without a separate script).

@rnhmjoj [said](https://github.com/qutebrowser/qutebrowser/issues/2939#issuecomment-375658738):
> Another issue I have found: the script calls imports `browser.webengine.spell` and then calls `qutebrowser.utils.standarddir` which not initialized, so I had to "manually" read the environment to get the path. 

It should be possible for the script to call `standarddir.init()` - reading it manually like in [the NixOS patch](https://github.com/rnhmjoj/nixpkgs/blob/f9dfa0e328d0642735d84825ab889013e3bdb691/pkgs/applications/networking/browsers/qutebrowser/dictionaries-path.patch) won't work on operating systems other than Linux :wink:

@elshize IIRC you said you wanted to take a look at this some while ago - are you okay with @rnhmjoj taking a look?

### PR DESCRIPTION
**Pull request by rnhmjoj**
##### things done
1. [x] set`QTWEBENGINE_DICTIONARIES_PATH` to `qutebrowser/dictionaries` if Qt >= 5.10
2. [x] fetch and install dictionaries automatically when setting `spellchecking.languages`
3. [ ] run tests

##### issues to solve
1. [ ] how to update the dictionaries without the script?
2. [x] the download is blocking and freezes the browser
3. [ ] files should be downloaded once for all profiles

Closes #3759

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3762)

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Thank you, I'll take a look.

**Comment by rnhmjoj** [comment]
I'm running into some problems.

I would like to move the dictionary installation outside webenginesettings.py and do something like
```patch
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -501,6 +501,8 @@ def _init_modules(args, crash_handler):
 
     log.init.debug("Misc initialization...")
     macros.init()
+    spell.init()
+
     # Init backend-specific stuff
     browsertab.init()
```

the problem is that we lose the ability to install dictionaries when the config is update at runtime. Also I don't know how to access the current profile.

Instead I could just rorder the modules so the download manager is initialised before
```patch
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -466,9 +466,6 @@ def _init_modules(args, crash_handler):
     log.init.debug("Initializing sessions...")
     sessions.init(qApp)
 
-    log.init.debug("Initializing websettings...")
-    websettings.init(args)
-
     log.init.debug("Initializing adblock...")
     host_blocker = adblock.HostBlocker()
     host_blocker.read_hosts()
@@ -496,6 +493,9 @@ def _init_modules(args, crash_handler):
     download_manager = qtnetworkdownloads.DownloadManager(pare>
     objreg.register('qtnetwork-download-manager', download_man>
 
+    log.init.debug("Initializing websettings...")
+    websettings.init(args)
+
     log.init.debug("Initializing Greasemonkey...")
     greasemonkey.init()

```
but is it even safe to do?

Another issue is that the dictionaries are installed twice if I do
```patch
--- a/qutebrowser/browser/webengine/webenginesettings.py
+++ b/qutebrowser/browser/webengine/webenginesettings.py
@@ -217,12 +217,13 @@ class ProfileSetter:
     def set_dictionary_language(self, warn=True):
         """Load the given dictionaries."""
         filenames = []
+        missing = []
         for code in config.val.spellcheck.languages or []:
             local_filename = spell.local_filename(code)
             if not local_filename:
-                spell.install_code(code)
+                missing.append(code)
             filenames.append(local_filename)
-
+        spell.Installer(missing)
         log.config.debug("Found dicts: {}".format(filenames))
         self._profile.setSpellCheckLanguages(filenames)

```

because this code is called for both default and private profiles.

**Comment by The-Compiler** [comment]
Sorry for the long delay! I finally got around to taking a first look at this - are you still interested in finishing it?

FWIW right now this is way too much code duplication with `dictcli.py` which will make maintaining it in the future difficult - it should probably be written in a way so the code in `spell.py` can be used by `dictcli.py` as well.

If you won't have the time to finish it, I'll probably be able to pick it up - just let me know.

**Comment by rnhmjoj** [comment]
Yeah, unfortunately I'm not going to be able to work on this anytime soon, sorry.
You are free to resume it. Thank you!

**Comment by The-Compiler** [comment]
I've taken a look at it, but it looks like it's a bit more complicated than I originally thought... For now I'll push a commit to update `dictcli.py` to not require root anymore on Qt 5.10 (and qutebrowser will now set `QTWEBENGINE_DICTIONARIES_PATH` accordingly).

I pushed my existing work to [the autospell branch](https://github.com/qutebrowser/experiments/compare/autospell) in my qutebrowser/experiments repository though.

I also opened #4003 to track the rest of this. Thanks for the contribution anyways! :+1:

**Comment by rnhmjoj** [comment]
Thank you.

**Pull request closed without merging**
