### PR TITLE
Rename desktop file to follow appdata ID

### PR DESCRIPTION
**Pull request by ykgmfq**
This is a follow-up to b415edaf62680facec826b4457f8318392de9125. The [Freedesktop standard](https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s02.html) says:

> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of example.org writes "Foo Viewer", they might choose the name org.example.FooViewer, resulting in a file named org.example.FooViewer.desktop.

This change would also help Flatpak deployment.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4547)

### CODE REVIEW

**Comment by jgkamat** [comment]
I'm going to let @The-Compiler handle merging this because it will likely require an update to [the arch pkgbuild](https://aur.archlinux.org/packages/qutebrowser-git/) and possibly [all the other packages](https://github.com/gentoo/gentoo/blob/master/www-client/qutebrowser/qutebrowser-9999.ebuild#L55) out there.

**Comment by ykgmfq** [comment]
See also https://github.com/flathub/flathub/pull/814

**Comment by ykgmfq** [comment]
@jgkamat the arch package is done, and gentoo is waiting for this to be merged, so they can merge my change there. Maybe we can just go ahead and merge?

**Comment by The-Compiler** [comment]
I mainly delayed this because I didn't want to merge it last-minute before the v1.6.0 release, which was quite late already.

Just merged it and it broke `qutebrowser-git` (and probably others) because you didn't adjust `misc/Makefile` :wink: I fixed this in c7b9c385d59a97e30817f6bbc1531791095ba49c.

Thanks!

**Comment by ykgmfq** [comment]
Whoops! My brain probably merged MANIFEST and MAKEFILE into one thing 😉

**Comment by The-Compiler** [comment]
Looking at https://github.com/wayland-project/wayland-protocols/blob/70ed9d7ee8f6491032fcccb74f25693851d740f2/stable/xdg-shell/xdg-shell.xml#L590 and https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop the current `q_app.setDesktopFileName("qutebrowser")` call in `app.py` should probably now set it to `org.qutebrowser.qutebrowser` instead - correct, @ykgmfq?

**Comment by ykgmfq** [comment]
Yeah looks good to me.

**Pull request merged**
