### PR TITLE
Short options for basedir, temp-basedir, debug, and debug-flags

### PR DESCRIPTION
**Pull request by MacGyverNL**
As discussed in IRC:

Assigns -B for basedir, -T for temp-basedir.

Assigns -d for debug, -D for debug-flags.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3900)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks!

**Comment by toofar** [comment]
Regarding the first failure(s) `KeyError: "args"` I think the `webkit_tab` fixture should use the `fake_args` fixture too? I'm not sure why it isn't failing all the time (oh, it was just introduced yesterday in  b9fc068af5) but:
```
qutebrowser/browser/webkit/webkittab.py:651: in __init__
    private=private, tab=self)
qutebrowser/browser/webkit/webview.py:74: in __init__
    parent=self)
qutebrowser/browser/webkit/webpage.py:76: in __init__
    win_id=win_id, tab_id=tab_id, private=private, parent=self)
qutebrowser/browser/webkit/network/networkmanager.py:151: in __init__
    self._args = objreg.get('args')
qutebrowser/utils/objreg.py:229: in get
    return reg[name]
```

**Comment by The-Compiler** [comment]
Fixed that one in master a few minutes ago :wink:

**Comment by toofar** [comment]
Typical.

**Pull request merged**
