### PR TITLE
Per-domain settings

### LINKED ISSUE #27: Per domain settings
For all settings where this makes sense, the setting should be configurable per domain (or probably even protocol/domain/port triple).

This will make a lot of things easier:
- NoScript is essentially done then
- RequestPolicy is a lot easier
- etc.

---

# For the current status of this (February 2018), see [this comment](https://github.com/qutebrowser/qutebrowser/issues/27#issuecomment-367154807).

### PR DESCRIPTION
**Pull request by The-Compiler**
Initial version of per-domain settings - still has a few issues (mostly needing refreshes sometimes with QtWebEngine), but good enough to be merged into `master`.

@toofar said he has a few questions/reviews, so I'm opening a PR.

@jgkamat if you have the time to take a look as well (especially at the config storage related stuff we talked about in IRC), that'd be much appreciated!

@rcorre I'm guessing GitHub will auto-request you as a reviewer :wink: The completion related changes are minimal (just some change to tests so the patching is picked up), but if you have the time to take a look at the rest, that'd be appreciated!

Fixes #27 (yaaay!), I'll open a new issue for whatever is postponed until after the PR is in.

**Note:** Starting on this branch will rewrite your `autoconfig.yml` to a format which is incompatible with the current master branch. You might want to back it up first.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3618)

### CODE REVIEW

**Comment by The-Compiler** [comment]
In 5c4277aac81228713f3c4582ece7be9bc3cd35d9 I added some default keybindings (see the commit message) to toggle scripts. I did something different to dwb there for once, as those dwb bindings (search for `toggle_scripts` in the [manpage](https://portix.bitbucket.io/dwb/resources/manpage.html)) always confused me.

I'd like some comments on that - do those keybindings look like they make sense?

**Comment by jgkamat** [comment]
The keybindings (letter wise) make sense to me, and I think we won't have issues with accidentally hitting them because the chain is 3 letters long, and there's no 'ttt' chain. 

However I think some people might have `t` bound to something (I have `t` bound to `:open -t`, which is a default bind in vimperator). I think that most people who have such a bind will know how to disable these bindings easily, but it might end up being a bit of an annoyance. I can't think of a better key though (t for toggle, and 'g' has a bunch of binds already), so I'm fine with it overall.

**Comment by The-Compiler** [comment]
I just pushed a rather big refactoring of the `websettings` module in 3956f81e730463adcba05d92d0043155609aa422. That was badly needed, IMHO :wink:

**Comment by The-Compiler** [comment]
And after some crazy workarounds, the annoying issues in #3622 should be taken care of. Giving this another round in the CI, and after that I'm going to merge it when nothing else comes up.

@toofar still interested in your comments of course, but IIRC you should still be able to comment on merged pull requests.

**Pull request merged**
