### PR TITLE
add chain-able command jseval-file for executing multiple js files

### PR DESCRIPTION
**Pull request by ghost**
Example usecase:
Using readabilityjs from mozilla to make websites more readable:
`git clone "https://github.com/mozilla/readability.git" ~/.local/share/qutebrowser/js/readability`
and in config.py:
`config.bind(',r', 'jseval-file readability/JSDOMParser.js ;; jseval-file readability/Readability.js ;; jseval var article = new Readability(document).parse(); document.head.innerHTML = ""; document.body.innerHTML = article.content;')`

This is my first code contribution on Github, so please tell me if I did anything wrong or if something is odd.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4081)

### CODE REVIEW

**Comment by jgkamat** [comment]
Henry Kohli writes:

> @@ -2081,6 +2081,22 @@ class CommandDispatcher:
>          widget = self._current_widget()
>          widget.run_js_async(js_code, callback=jseval_cb, world=world)
>
> +    @cmdutils.register(instance='command-dispatcher', scope='window', no_cmd_split=False)

no_cmd_split here can be removed, the default value is False.

> +    def jseval_file(self, js_file, quiet=False, *,
> +                    world: typing.Union[usertypes.JsWorld, int] = None):
> +        """Evaluate a JavaScript file.
> +
> +        Args:
> +            js_file: path to js file to evaluate
> +                 If the path is relative, the file is searched in a js/ subdir
> +                  in qutebrowser's data dir, e.g.
> +                  `~/.local/share/qutebrowser/js`.
> +            quiet: Don't show resulting JS object.
> +            world: Ignored on QtWebKit. On QtWebEngine, a world ID or name to
> +                   run the snippet in.
> +        """
> +        self.jseval(js_file, file=True, quiet=quiet,world=world)

There should be a space after this comma. Other than that, there are a couple
pylint errors, could you take a look at those:

https://travis-ci.org/qutebrowser/qutebrowser/jobs/405380241

I think this could be pretty useful, thanks for the PR :)

**Comment by jgkamat** [comment]
Florian Bruhin writes:

> I'm also not sure if it's guaranteed to work correctly when chained, as the
> old JS code might still be executing when you're running new one.

I don't think this will be an issue because JS is single-threaded, but if the
files are loaded out of order this could be a problem.

> What about instead allowing multiple arguments to :jseval --file (but then
> you can't easily chain a normal :jseval to it - but you could create another
> file)?

This does sound a lot cleaner than having two commands, maybe we could do
something sort of like apply, where the last argument is interpreted as js if
it's not a file (checked by python). That might overcomplicate things, but it
might be a common pattern to load some files and run a little inline JS.

**Comment by The-Compiler** [comment]
Another possibility: Something like herbstluftwm's `chain` command (see its [manpage](http://herbstluftwm.org/herbstluftwm.html)), which would allow you to do:

```
:chain ;; jseval foo ;; jseval bar
```

but it always splits, and you can chose your own separator as the first argument.

**Comment by The-Compiler** [comment]
@Herny64 what do you think about the alternatives I proposed above?

**Comment by Herny64** [comment]
@The-Compiler Sounds nice. A git, GitHub related question: Should I push this :chain command to this pull request or should i create a new pull request for this ? Can I change the title of this pull request or is this not necessarily. Already tried using a search engine but probably used the wrong keywords.

**Comment by The-Compiler** [comment]
Probably better to close this and open a new PR in this case, as it's a different feature. Usually, for improvements for an existing PR, you'd push new commits to the same branch - but here it makes little sense.

**Pull request closed without merging**
