### PR TITLE
Replaced \b in prev- and next- regex for symbols for #2485

### LINKED ISSUE #2485: prev-/next-regexes should match at beginning/end of string
```
>>> re.search(r'\b<<\b', '<<')
>>> re.search(r'^<<$', '<<')
<_sre.SRE_Match object; span=(0, 2), match='<<'>
```

### PR DESCRIPTION
**Pull request by kronos29296**
Closes #2485

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2960)

### CODE REVIEW

**Comment by The-Compiler** [comment]
This means they won't match at word boundaries anymore now, right?

Also, note that my current priority is getting the new config in (see the note at the top of the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/CONTRIBUTING.asciidoc), though the exams at least or done now), so you'll need to re-do this once it's in anyways.

**Comment by kronos29296** [comment]
Okay. I somehow completely missed that.

**Comment by The-Compiler** [comment]
Err, sorry, that was my bad - it should be on the latest `master` (which has `new-config` merged) not `new-config`. 😊

**Comment by The-Compiler** [comment]
@kronos29296 Any update on this? If you don't have the time to work on this anymore, feel free to close it FWIW.

**Comment by kronos29296** [comment]
Got caught up in real life (Exams). Will finish it by this week.

**Comment by The-Compiler** [comment]
`configdiff.py` is here to show what people have configured in their legacy configs, the correct place to adjust this is `configdata.yml`.

Also, this probably still is an issue:

> This means they won't match at word boundaries anymore now, right?

**Comment by kronos29296** [comment]
Do you want me to change all the regexes? I thought only the symbols created problems with matching word boundaries and so changed only them.

**Comment by The-Compiler** [comment]
I agree it looks like only the symbols are problematic, probably because `\b` matches word boundaries and `<<` isn't a word.

This still has some issues though:

- `configdiff.py` still shouldn't be modified
- `$$` isn't needed anymore in `configdata.yml` (different format)
- Seeing how difficult it is to get those regexes right, I think it'd be good if there was an unittest for the default value
- It still has the issue of `^<<$` not matching e.g. `<< foo`, but that should match.

I'm not sure what to do about the last one (`\B` might be the answer, but I don't understand why yet).

Would you like to look into that and write a test for it too?

**Comment by The-Compiler** [comment]
Closing this now because of inactivity - thanks for your contribution anyways!

**Pull request closed without merging**
