### PR TITLE
Flip the Qt 6 switch

### LINKED ISSUE #7202: Switching to Qt 6 by default
*(Continuation of #5395 because that was getting rather big)*

# Current state

The qt6-v2 branch **has been merged to master** on March 18th, 2023, but with Qt 5 still being the default. See #7628 for details. This issue is now repurposed on what there needs to be done for Qt 6 to be the default Qt wrapper.

~~The last fixes for the `qt6-v2` branch with Qt 6 support went in around May 19th. Multiple core developers (and users) have been using it as a daily driver since far longer (late 2021 / early 2022) and all known crashes are fixed, with all tests passing.~~

~~There is still a lot of remaining work, however, on the development side. Due to the [big amount of changes](https://github.com/qutebrowser/qutebrowser/compare/qt6-v2) (currently 156 commits, 314 files changed, 12,978 additions and 4,094 deletions) it's tricky to integrate this into `master` without breaking lots of existing open PRs. Thus, we'd like to do another round of PR merging before attempting to do so. The current approach also breaks various tooling, by not properly supporting static analysis (#7128, but that will introduce another big code churn), or by not fixing linting issues yet (#1455).~~

~~Bottomline: Feel free to use the `qt6-v2` branch, keep in mind it will be rebased from time to time, and it will still take lots of efforts behind the scenes to get it fully integrated.~~

# How to try

## `mkvenv.py`

- **Take a backup of your qutebrowser data directory** (see `:version`) unless you don't mind losing cookies and such when down-/upgrading. This isn't needed if you use `--temp-basedir` below, but if you forget to do so, your data will get upgraded, and as far as I'm aware, there is no way to read it with Qt 5 after that.
- Clone the git repo, e.g. via `git clone https://github.com/qutebrowser/qutebrowser.git`
- `cd qutebrowser`
- ~~Check out the branch using `git checkout qt6-v2`~~
- Create a new separate environment via `python3 scripts/mkvenv.py --venv-dir .venv-qt6 --pyqt-version 6.3`
- Set `QUTE_QT_WRAPPER=PyQt6` somewhere in the environment
- Run `.venv-qt6/bin/qutebrowser --temp-basedir` and verify via `:version` that you're indeed on Qt 6

## Archlinux

[qutebrowser-qt6-git](https://aur.archlinux.org/packages/qutebrowser-qt6-git) is available in the AUR.

## Windows / macOS

Built as part of the [nightly builds](https://github.com/qutebrowser/qutebrowser/actions/workflows/nightly.yml) on CI. Click on the most recent passing build, then find the `qt6` builds under "Artifacts". Note that you will need to be logged in with a GitHub account to download.

**Note for macOS:** Due to a [PyInstaller issue](https://github.com/pyinstaller/pyinstaller/pull/6903), Chromium's [sandboxing](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox_faq.md) is currently disabled **for macOS builds with Qt 6**. This means that there will be no additional layer of protection in case of Chromium security bugs. Thus, it's advised to not use this build in production. Hopefully, this situation [will be resolved before the final 3.0.0 release](https://github.com/qutebrowser/qutebrowser/issues/7278).

## Flatpak

[Published in the `flathub-beta` repo](https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1129936579):

> Adding the flathub-beta remote and installing from the beta branch can be done through an application manager (Gnome Software, Discover, ...) or via the command-line.
>
> ```
> $ flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
> $ flatpak install flathub-beta org.qutebrowser.qutebrowser//beta
> ```

# Remaining issues

- [x] Flickering rectangles with AMD graphics: #7398 (seems to be fixed in Qt 6.4)
- [x] Mouse wheel sometimes stops working for me: #7523 (known upsteam Qt issue)
- [x] favicons don't show for some tabs sometimes ~~(TODO: find reproducer, going to eg https://github.com/qutebrowser/qutebrowser/commits/qt6-test and clicking on one of the commits seems to lose the favicon) *([from @toofar](https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1003259843), haven't checked if it's still an issue)*~~ see https://github.com/qutebrowser/qutebrowser/issues/7202#issuecomment-1142021295
- [x] Wrong MPRIS name: #7431

# TODOs

- [x] Get macOS builds to work
- [x] ~~Look at remaining API changes and new features (comment below)~~ moved to #7756
- [ ] Look at remaining `FIXME:qt6` comments
- [x] Make sure qutebrowser has enough feedback (e.g. logging?) about which Qt wrappers it uses and why
- [x] ~~Maybe investigate storing the Qt wrapper to use in a config file so that we don't unexpectedly switch (and destroy data?) if one is unavailable~~
- [ ] Decide what to do about test coverage (switch to Qt 6? Combine?)
- [x] ~~Probably merge some PRs while waiting for more feedback and to avoid crazy conflicts with the next steps~~ moved to v4
- [x] ~~Integrate #7128 if we didn't find a way to make static analysis work otherwise~~ see #7370 and linked discussion and issue
- [x] ~~Adopt `black` (#1455) so that we pass "normal" linting again and don't have crazy long lines~~ moved to v4
- [x] ~~Look at adopting PySide6 again~~ not a priority at the moment
- [x] Check if we can revert 3c4d51a03cefb010e57c1e85c53e70bb77de8387
- [x] Potentially start cherry-picking some stuff to master
- [ ] Figure out why our way of blocking back/forward mouse button presses broke
- [x] Perhaps introduce a Qt 5 warning to get people to switch over

### PR DESCRIPTION
**Pull request by The-Compiler**
- Enable autoselection for `QUTE_QT_WRAPPER`, so that PyQt6 is preferred, and we fall back to PyQt5 if it is unavailable
- Replace `_DEFAULT_WRAPPER` in `machinery.py` with a `_WRAPPER_OVERRIDE` (cc @ionenwks)
- Switch most tooling (everything except mypy?) to Qt 6 by default, so that `...-qt5` is the Qt 5 variant, and no suffix is Qt 6
- Provide both PyQt5 and PyQt6 to pylint, which seems to teach it to check things with basically an union of PyQt5 and PyQt6

Will be merged once Qt 6.5.2 is out due to various regressions in Qt 6.5.1. That's [planned to happen](https://wiki.qt.io/Qt_6.5_Release) on Wednesday. With a few days until Archlinux/~~Gentoo~~ have updated their Qt packages hopefully, I'm aiming to merge this in early July.

As for distributions:

- Archlinux is definitely worth waiting for - they are usually fast, and most of the userbase is there
- Gentoo already defaults to Qt 6 for git anyways
- Any other distributions with a git qutebrowser package?

The unstable-qt6 docker environment fails because the image isn't pushed yet. Will need merge to master first, as it gets only pushed there.

Closes #7202 (finally!).

### CODE REVIEW

**Comment by toofar** [comment]
Yay! :clap: 

> Will be merged once Qt 6.5.2 is out

Hmm, I was thinking there might be something in the autoselect logic to only auto-switch to Qt6 for 6.5.2+, do you think there is any need for that?

**Comment by The-Compiler** [comment]
Welp, I just noticed some of `scripts/` and all of `misc/userscripts` are still both Qt 5. 

For the latter, I think we can safely use `qutebrowser.qt.*` but those definitely need to be done before flipping the switch.

For the former, I'll need to experiment some more, because those scripts are sometimes useful outside of qutebrowser too. But I suppose having a qutebrowser installed would still be a safe assumption.

Should hopefully have time to get to this before this can be merged anyways.

**Comment by The-Compiler** [comment]
> Hmm, I was thinking there might be something in the autoselect logic to only auto-switch to Qt6 on 6.5.2+, do you think there is any need for that?

I thought about it, but I'm somewhat lukewarm about it. I'm really not sure what happens exactly when you mix Qt 5 and Qt 6 in the same process. It might be fine when not creating a `QApplication`, but it still seems to me like something that could cause weird trouble.

But when doing this, we'd be forced to import Qt 6, then find out it's actually not good, and then import Qt 5 instead.

Since I have a workaround for #7732 now (which was probably the most important issue, all the rest is annoying but not a crash), I decided to not bother with it. I'm assuming once 6.5.2 is out, people are not usually going to use 6.5.0/.1 anyways.

If I need to revert that workaround (#7753 possibly...), that might be worth another thought.

**Comment by toofar** [comment]
> Welp, I just noticed some of scripts/ and all of misc/userscripts are still both Qt 5.

I don't have the whole situation in my head atm but when I was looking at https://github.com/qutebrowser/qutebrowser/pull/7128 I had the thought that just upgrading them to Qt6 and not worrying about Qt5 compatibility would be fine. I guess the downside of that would be any distros that package the new release and don't have Qt6 available. I'm not sure how common that scenario is and how much effort we should put into polishing all the rough edges for it.

**Pull request merged**
