### PR TITLE
make win_ids start at 1 instead of 0

### PR DESCRIPTION
**Pull request by mjauvin**
with this change, [count] can eventually be used to reference window ids.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3551)

### CODE REVIEW

**Comment by jgkamat** [comment]
I have a feeling this might break some other parts of qb,  (and will probably break people's workflows and scripts), so this needs to be approached rather carefully.

**Comment by mjauvin** [comment]
At least all [unit] tests are still passing...

**Comment by mjauvin** [comment]
end2end/features/test_tabs_bdd are failing...

**Comment by mjauvin** [comment]
If I fix all the tests for this PR, is it something that will get accepeted or am I losing my time?

**Comment by mjauvin** [comment]
Bad start, am going to look at this at a different angle, changind the index at the core is not the way to go.

**Pull request closed without merging**
