### PR TITLE
Pdfjs zoom keys

### LINKED ISSUE #1916: Send zoom keys to pdfjs instead of zooming the whole page
When PDF is opened currently zoom keys zoom the whole page. This has several disadvantages:

* Control bar is zoomed, which can be undesirable;
* Render quality suffers because zooming is done essentially by interpolation of rendered page.

It would be nice for qutebrowser to instead "ask" pdfjs somehow to zoom.

### PR DESCRIPTION
**Pull request by Kingdread**
Fixes #1916.

This sends zoom commands to pdfjs (if a pdfjs page is displayed), which
zooms only the content (and leaves the controls unzoomed), which is
probably what you want when you zoom pdf sites.

The API was actually easier than I expected :laughing:

The check uses a simple heuristic to determine if a pdfjs page is displayed (it checks for the `#viewer.pdfViewer` element and for the `/pdf.js` and `viewer.js` scripts). It's currently only implemented for WebKit, as we only support pdfjs for WebKit, though I guess that it might be possible to do it in a similar way for WebEngine if needed. If the heuristic is bad or impacts performance too much, we could try and set a flag on the WebView when pdfjs is loaded (in the unsupported content handler), but this way it should work for any pdf.js instance (it also works for the demo).

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2001)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Seems like you also have a circular import there :wink:

```
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/webkit/network/webkitqutescheme.py", line 29, in <module>
    from qutebrowser.browser import pdfjs, qutescheme
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/pdfjs.py", line 27, in <module>
    from qutebrowser.browser.webkit import webview as webkit_webview
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/webkit/webview.py", line 33, in <module>
    from qutebrowser.browser.webkit import webpage
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/webkit/webpage.py", line 32, in <module>
    from qutebrowser.browser import pdfjs
ImportError: cannot import name 'pdfjs'
```

**Comment by Kingdread** [comment]
Darn, definitely not what I wanted :laughing: will refactor it!

**Comment by Kingdread** [comment]
Okay, I've thought a bit more about this, and I think that this easy implementation might not be the best. Instead I think we need to differentiate between some kind of "smart" zoom (that respects webapps like pdfjs and later maybe PDFium) and a "dumb" zoom (that just zooms the widget), because of a few reasons:

* Some people might not like qutebrowser to zoom pdfjs, sometimes even just for a single command (what if they are on a small screen and they actually want to zoom the interface). Having a way to change between smart/dumb zoom on a per-command basis might be handy, at the very least we'd need setting to turn it off.
* In some cases we might want to programmatically get the dumb zoom factor, e.g. when calculating the position of hints or when doing tests (especially for this feature).

But of course there are downsides:

* The `tab.zoom` API would need be extended.
* Porting the logic to webengine wouldn't be hard, it would just be complicated due to the fact that webengine loves async, but the other zoom code expects at least `zoom.factor()` to be sync.
* Keeping track of 2 zoom values per tab per session isn't great either, especially because history is already bugged with pdfjs.

So I guess the compromise is:

* Keep the implementation restricted to WebKit+pdfjs for now.
* Extend the zoom API with a `smart` parameter (default `False`) for `factor`, `offset` and `set_factor`.
  * Smart zoom would not be saved in the session, it's "set and forget".
  * Smart zoom is independent from the normal zoom and does not modify the fuzzylist.
  * Smart zoom falls back to the normal methods if smart zooming is not possible.
* `:zoom` would get a new parameter `--smart` which would try to forward the commands to pdfjs (or PDFium, ...)
* Find some other way to get the "smart" value in BDD tests (maybe just a log message after doing `:zoom --smart`)

**Comment by The-Compiler** [comment]
That proposal sounds good to me!

**Comment by The-Compiler** [comment]
@Kingdread what's the state on this? I remember us talking about whether it's really a good idea to do this or not, but I kind of forgot about it, it seems... Are you still interested to continue working on this? Should we close it and add a comment so the patch doesn't get lost, and then postpone it to $later?

**Comment by The-Compiler** [comment]
Closing this too for now - I added the patch to #1916. Thanks for the contribution anyways!

**Comment by user202729** [comment]
@The-Compiler Info: The current version (master) implements `AbstractTab.factor` by storing them in the member `_zoom_factor` while setting and `factor()` just retrieves it, while this branch (pdfjs-zoom-keys) queries the widget for the factor. The approaches are incompatible, and some changes are necessary before (if) merging.

What should the design be?

**Comment by toofar** [comment]
This is the PR that introduces `_zoom_factor` https://github.com/qutebrowser/qutebrowser/pull/2940
It explains that querying the widget before the page has finished loading always returns 100%, I think. Since that PR was only a year ago I assume that is still the case and this should be changed to use that.

**Pull request closed without merging**
