### PR TITLE
Update the ad blocker question on faq.asciidoc

### PR DESCRIPTION
**Pull request by oacar**
Changed the answer to ad blocker question based on the version 2.0.0 update.

### CODE REVIEW

**Comment by marco-parillo** [comment]
It looks to me as if these two are related: https://github.com/qutebrowser/qutebrowser/pull/6045

**Comment by oacar** [comment]
Totally. This looks redundant, as #6045 already does what I intended to do.

**Comment by The-Compiler** [comment]
Thanks for the PR! Let me note it might take me a bit until I get back to you because I'm currently busy with a pytest training as well as the v2.0.2 release, and maybe taking a prolonged weekend off after that. I'll probably rewrite things based on both this and #6045 though.

**Comment by The-Compiler** [comment]
Thanks again and sorry for the delay! I took the freedom to improve it a bit and add a couple of links: 6509bb824a78a622bb3aa456eaf5389fcf71dbce

**Pull request merged**
