### PR TITLE
userscripts: adding localhost userscript

### PR DESCRIPTION
**Pull request by SidharthArya**
for quick navigation to localhost:port

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! Mind adding a link to your blogpost as well?

**Comment by SidharthArya** [comment]
Hi @The-Compiler. Is this okay ?

**Comment by The-Compiler** [comment]
Looks great, thank you! :+1:

**Comment by SidharthArya** [comment]
Thank you

**Comment by The-Compiler** [comment]
FYI, the link you added here originally seems to go to some kind of scam site now. I replaced it by https://blog.sidhartharya.com/a-quicker-way-to-reach-localhost-with-qutebrowser/ which seems to be the proper place nowadays.

**Pull request merged**
