### PR TITLE
[WIP] Tentative fix for #5078

### PR DESCRIPTION
**Pull request by lufte**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks for the update! However, it looks like the workaround doesn't actually work for the [test page](https://projects.dm.id.lv/Public-Key-Pins_test), because apparently it happens before the URL updates:

```
(Pdb) p show_non_overr_cert_error
True
(Pdb) p url
PyQt5.QtCore.QUrl('https://certerror.projects.dm.id.lv/hsts-recourse.html')
(Pdb) p self.url(requested=True)
PyQt5.QtCore.QUrl('https://projects.dm.id.lv/Public-Key-Pins_test')
```

Maybe your earlier approach about saving the URL in `_on_navigation_request` was a pretty good idea? (I can't find it anymore, but I think it was in this PR, and possibly force-pushed away?)

**Comment by The-Compiler** [comment]
Whoops, I didn't want to actually merge this yet - still, maybe it'd be good to re-add the previous code in a separate PR?

**Comment by lufte** [comment]
Oh hey, sorry, I wrote this code and wanted to check if I broke the build but didn't actually test it 😅.

Yeah I force pushed and lost that change, but it wasn't that long anyway, I can re write it. I'll make sure to find some free time this week to finish this.

**Comment by arza-zara** [comment]
> I force pushed and lost that change, but it wasn't that long anyway, I can re write it. 

https://github.com/qutebrowser/qutebrowser/commit/789fcb0c2bbb156799d7763d8752b1ca5aa1d886? Or you can dig `git reflog`.

**Comment by lufte** [comment]
That's the one, thanks!

**Comment by The-Compiler** [comment]
@arza-zara Oh, nice, how did you find it? Did you have it locally?

@lufte I pushed a follow-up based on that in f90313bc0e92f9fb17d4d589cd1920e8d94810c2. For future contributions, I'd prefer force-pushes only for minor things (like typo changes) - I like seeing "failed"/previous approaches in history as it can be useful information. No biggie though!

**Comment by lufte** [comment]
It was actually here in the PR log.
> @lufte lufte force-pushed the lufte:issue5078  branch from 789fcb0 to 2aa2bc0 7 days ago

I just didn't see it while browsing from my phone (or maybe it's not shown on the mobile version).

> @lufte I pushed a follow-up based on that in f90313b. For future contributions, I'd prefer force-pushes only for minor things (like typo changes) - I like seeing "failed"/previous approaches in history as it can be useful information. No biggie though!

Alright! I'm sure we should have all the cases covered with this solution. I'll try to test it anyways to confirm. And yeah, force pushing is a bad habit 😅

**Pull request merged**
