### PR TITLE
Fix: restrict output of `task` to one line (closes #3726)

### LINKED ISSUE #3726: TaskAdd: Multiline Output Fails
As far as I can tell, won't multiline output always result in an error when used as an arg for `message-info` and/or `message-error`.

https://github.com/qutebrowser/qutebrowser/blob/69a013bc82d2ecc485e4b0659c16af7b78606f6d/misc/userscripts/taskadd#L28-L34

Tacking on `| head -1` to the end of the `task` command should fix this.

### PR DESCRIPTION
**Pull request by bbugyi200**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3728)

---
[edit by @jgkamat to link issues: Closes #3726]

### CODE REVIEW

**Comment by The-Compiler** [comment]
This won't work either, qutebrowser isn't bash :wink:

**Comment by bbugyi200** [comment]
You sure? I tested this one for success and failure. Seems to work for me.

Otherwise, what did you mean when you said "shorten it when doing the `echo`"?

**Comment by The-Compiler** [comment]
Oh, sorry, I misread something in your code - however, I think this still breaks with multi-line messages, as it'd execute a qutebrowser command like `:message-info 'foo` (with no trailing `'`).

Something like `echo "message-info '$(echo $msg | head -n 1)'" >> "$QUTE_FIFO"` would probably work?

**Comment by bbugyi200** [comment]
Good point. I didn't think of that. Oddly enough, however, `message-info 'foo` works for me (it just prints `foo` to the status line).

Regardless, I changed it to be safe. I had to throw double quotes around `$msg` though. Otherwise, that command substitution syntax substitutes newlines with spaces (which I figured out after about an hour and a half of banging my head against the wall).

**Comment by The-Compiler** [comment]
LGTM now, thanks!

**Pull request merged**
