### PR TITLE
update .gitignore for temporary vim files

### PR DESCRIPTION
**Pull request by fridokus**
Do not add vim undofiles by default.
Also, after .swp comes .swo etc., so added those as well.

For hacktober :+1:

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! What do you think about adding some more vim-related files? See https://www.toptal.com/developers/gitignore/api/vim

In general I'd recommend ignoring files like that system-wide in `~/.gitignore` (or configuring vim to write undo/swap files into `~/.cache`), but I guess given that many qutebrowser users/developers are using vim, this makes sense anyways.

**Comment by fridokus** [comment]
Updated with the files that I think are relevant.. let me know if you agree!

**Comment by The-Compiler** [comment]
I think this now would ignore the `.svg` files in `icons/` and such, right? Also, why are the others not relevant?

**Comment by fridokus** [comment]
No, it will ignore only files starting with `_` or `.` and ending in `svg`. 

I was thinking that `tags` is a generic name that might be used at some point and `.netrwhist` is for a plugin so that's maybe too specific..

**Comment by The-Compiler** [comment]
Makes sense - thank you! :+1:

**Pull request merged**
