### PR TITLE
Make the main window default geometry configurable

### PR DESCRIPTION
**Pull request by mrozekma**
Added a few config options to control the geometry of new windows (the first window seems to remember its geometry from last session, but windows after that are fixed size). Tests mostly fail on my system for some reason, so going to see what CI says.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I'm not really convinced that a setting is the right way to go here. I think other applications handle this by doing something like taking the geometry/size of an existing window and then shift it a bit. Maybe it'd make more sense for qutebrowser to do the same?

**Comment by mrozekma** [comment]
If you think that's better, sure. My case is that my monitor is fairly large and 800x600 is small enough to break several of the webapps I regularly use. I'd actually be fine with a larger hardcoded value, but I figured some people wouldn't so I went with configurable. Using the size of other existing windows would also work though.

**Comment by The-Compiler** [comment]
Yes, I think that'd be a better course of action. Some people also complained that new windows open on the wrong screen, so it seems more natural to base the geometry on e.g. `objreg.last_focused_window()` or so. I wonder what Qt does by default if we're not loading a geometry at all?

**Comment by mrozekma** [comment]
> I wonder what Qt does by default if we're not loading a geometry at all?

Good idea; the docs say Qt leaves it to the window manager in that case, although on Windows that apparently means a 640x480 window :(

**Comment by The-Compiler** [comment]
@mrozekma Gentle ping - do you plan to implement what we've discussed above (basing it on the last focused window's geometry)?

**Comment by The-Compiler** [comment]
Closing this as I'm assuming you're not interested in continuing to work on it - if you are, feel free to open a new PR though, and thanks for the contribution anyways!

I also opened #5837 to track this, based on the approach we've discussed above.

**Pull request closed without merging**
