### PR TITLE
Properly signal scheme errors

### PR DESCRIPTION
**Pull request by SubbulakshmiRS**
Two patch files about correct usage of QuteSchemeError 
and general clean up are applied on master branch using git am .

Closes https://github.com/qutebrowser/qutebrowser/issues/4059

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4122)

### CODE REVIEW

**Comment by SubbulakshmiRS** [comment]
for fixing these errors , can i amend the commit every time , for travisCI of github to automatically check and tell ? @The-Compiler @toofar

**Comment by The-Compiler** [comment]
You can just push more commits to your branch. Also, no need to highlight us every time, we both follow this repository :wink:

**Comment by The-Compiler** [comment]
Are you still interested in finishing this, @SubbulakshmiRS? As-is, it looks like a lot of tests are broken.

**Comment by The-Compiler** [comment]
Closing this now - looking at the change in 003300855aa03f2f75693457306303de097fdc88 it looks like some places did assume that an exception was passed, and others assumed an error code... Since I'm the one who created this mess, I'm probably the best person to clean it up :wink: Thanks for the contribution though!

**Pull request closed without merging**
