### PR TITLE
Simplify TabCompletionModel.rebuild.

### PR DESCRIPTION
**Pull request by rcorre**
Rather than trying to add/remove rows from the model to accomodate
new/removed tabs or windows, just clear the model and reconstruct it
from scratch.

The cost to do this is trivial and it simplifies the implementation
significantly. This will make it easier to port to a new completion API
as described in #74.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Seems like this [broke](https://travis-ci.org/The-Compiler/qutebrowser/jobs/184759966#L537) a test, not sure why yet - can you take a look please?

cc @toofar

**Comment by rcorre** [comment]
Ah, this is because we only [expand](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/completion/completionwidget.py#L290) categories when the model is first set.

This means "real-time" `:buffer` completion updates are already partially broken. Try opening buffer completion in one window and then spawning more windows; you'll see "empty" categories start to appear.

My change just breaks it worse because now all the categories are "new" so nothing looks expanded.

We can fix by overriding `rowsInserted` to expand new categories as they get added. Not sure yet what the performance impact of that is.

**Comment by The-Compiler** [comment]
Can't we just expand everything when the completion is opened or so?

**Comment by rcorre** [comment]
We do. The problem is adding new categories to the completion _without_ re-opening it, like opening new windows while `buffer` completion is open (which is what the failing test tries to do).

I think `rowsInserted` will be fine though, as it only applies to rows added to the currently active completion. We wont take a hit, for example, when building up a huge model like `urlmodel`. I'll push that up in a sec.

**Comment by The-Compiler** [comment]
FWIW I wonder if we should just ditch realtime-updating support. In fact, didn't we talk about that before *somewhere*? I don't think there's an useful usecase for realtime updating, but I'd like to hear what @haasn (who wrote the test) and @blyxxyz (#1798) think.

**Comment by rcorre** [comment]
yep, we talked about this before and I was in favor of ditching realtime updates -- this was when I was discussing the complete elimination of cached completion models for #74. Then we got into talking about `urlmodel` performance and I got off onto this whole sql thing :sweat_smile: 

Anyways, I'd still like to construct most completion models on demand which would totally eliminate this problem. But when looking into that I found this, and I figured realtime updates should either work completely or not work at all...

**Comment by rcorre** [comment]
https://github.com/The-Compiler/qutebrowser/issues/74#issuecomment-240381072

**Comment by haasn** [comment]
My stance on realtime updates is that realtime updates for things like tab titles is useful, because tabs can and will change their titles for stuff like realtime update notifications.

Adding new tabs in realtime is probably useless, because if you have `:buffers` open you're probably not opening new tabs at the same time.

**Comment by rcorre** [comment]
Superseded by #2295

**Pull request closed without merging**
