### PR TITLE
Add 'undo-across-windows' option

### PR DESCRIPTION
**Pull request by cmlaverdiere**
This aims to solve issues #1420 and #1031. When the option is set to true, the
undo of closed tabs and windows behaves like Chromium.

Pretty rough (no docs / tests yet) but just looking for initial feedback. Tests related to tabs passed.

### CODE REVIEW

**Comment by The-Compiler** [comment]
So I just tested Chromium's behaviour, and there is something I consider quite unintuitive - if I have two open windows:

- window 1:
  - tab 1/1
- window 2:
  - tab 2/1
  - tab 2/2

When I focuse window 2 and close tab 2, then focus window 1 (and maybe don't even see window 2 anymore) and press `Ctrl-Shift-T` there, nothing seems to happen, but in the unfocused window the tab is restored.

Your PR duplicates that behaviour, is that intended? I think doing `u` should always do something in the *current* window (as the one the last tab was closed in might even be on another workspace). FWIW I'd be okay if you could close a tab in window 1, and then when you do `u` in window 2, that tab would open there.

**Comment by CLaverdiere** [comment]
Yes I intentionally made it behave like Chromium. I've never seen it as unintuitive as I usually only undo within a few minutes of closing the tab, so I'll be in the same window anyway. It's more consistent with the undo of closed windows as well. Should this be configurable?

**Comment by The-Compiler** [comment]
I agree that should be the common case - but if someone happens to accidentally do `u` in the "wrong" window, doing something in a window which isn't shown is quite surprising.

Would you be okay with changing it so `u` always opens the last-closed tab (even if global) in the current window? I don't think it needs to be configurable, IMHO.

**Comment by The-Compiler** [comment]
@lahwaacz I like that idea - and with `tabs-are-windows` the normal `:undo` could default to that as well (as there are no tabs then).

@CLaverdiere what do you think?

**Comment by CLaverdiere** [comment]
I like it. I'll try to implement @lahwaacz's idea soon.

**Comment by CLaverdiere** [comment]
Added the window switch, and tests pass.

**Comment by The-Compiler** [comment]
Thanks! FWIW, if he tests on Travis/AppVeyor happen to fail, that's because of some flaky tests added today. Working on getting them stable!

Could you maybe add some tests for `:undo -w` to `tests/end2end/features/tabs.feature` while you're at it? Check the existing `:undo` tests, they should be quite easy to add.

(hint: You might need to add `Given I have a new instance` liberally so older windows don't interfer)

**Comment by The-Compiler** [comment]
I also think this saves a session to disk every time a window is closed, right? Might be a better idea to store that in RAM (and maybe refactor the session code a bit if needed).

**Comment by CLaverdiere** [comment]
Tests and in memory sessions implemented. Seems to be working well.

**Comment by The-Compiler** [comment]
Could you take a look at the [broken session tests](https://travis-ci.org/The-Compiler/qutebrowser/jobs/136838769#L666) please? Not sure what exactly is broken right now, but let me know if you need help!

**Comment by The-Compiler** [comment]
@CLaverdiere Did you get a chance to take a look? If you don't have the time to look at it in the near future, let me know, and I'll try to take over when I find the time.

**Comment by CLaverdiere** [comment]
Feel free to take it over, I don't have much free time at the moment.

**Comment by The-Compiler** [comment]
Let's face it, I probably won't get to picking this up anytime soon either, I just have too much on my plate :wink:

I added the patch to #1031 as a comment to ensure nothing gets lost, and I'll pick it up at some later time, so I'm closing this now. Thanks for your contribution anyways!

**Pull request closed without merging**
