### PR TITLE
[WIP] Feature/form filler

### PR DESCRIPTION
**Pull request by antoyo**
This pull request fixes the issue #180.

Currently, we can save password in plain-text in a YAML file and encrypted with `pass` (also using YAML).

I need to fixes some issues, but I open the pull request now to get some feedback.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I appreciate your efforts, but as mentioned in #180 I really don't want to tie qutebrowser to a specific password backend, so I think I prefer not having this built-in until plugins are ready.

What do you think about #873 which is an userscript to store passwords? Maybe the focus should be on adding some commands like `:fill-form {username,password,...} <value>` or to qutebrowser and then building an userscript like in #873 for now?

**Comment by t-wissmann** [comment]
What are you implementing? Password filling or form filling in general? This isn't specified in #180. I think this clearly should be distinguished. What's the difference?

In password filling, the store provides a username and a password, and I want the password filler to pick the correct username/password-pair from the store and paste it in the login form. Furthermore I don't care how the form fields of the login form are actually called (i.e. `name`, `username`, `user`, `usr`, or `email`; OR: `password`, `pw`, `passwd`). I just want to enter the site! Furthermore I still want to enter it after the administrator of the site changes the field names! You can find an approach in #873.

In form filling I clearly distinguish between the fields. An example application is the address field of the local pizza ordering service, in which I have to enter my address every time I order a pizza. Here, I have much more fields and I clearly want to distinguish between the `email` and the `name` field. I'm sure one can easily adapt the #873 for form filling.

**Comment by antoyo** [comment]
I intented to create a password filler, but there are some issues as you mentioned, @t-wissmann.

@The-Compiler, in this pull request, there is an option to choose between the default password backend (YAML file in the qutebrowser config directory) and the `pass` backend. There is even a possibility to add other backends, if we need.

Anyway, if you don't want it built-in in qutebrowser, just close this pull request.
And don't worry about me spending time on this, I'll keep this feature in my fork for my personal use.

**Comment by antoyo** [comment]
@t-wissmann With the new commits, this is now a password filler.
One thing that seems to miss in your implementation is a shortcut the fill the form **and sumbit** it.
My implementation has this feature (it even works when the form is hidden and in Gmail two-steps login).
However, I have one issue with my implementation of this feature.
Check for instance [these login forms][1] (click on "Sign in" in the top right corner).
The problem I have is that I have no way to distinguish the two forms (LDAP and standard) except using data from these forms (it is necessary to submit to the right form using the shortcut). For now, I resolved this issue by saving the form action.
Nevertheless, as you said, it won't work anymore if these forms are changed by the web developpers.
I know there is not a lot of website with different unique login forms, but does anyone have an idea to solve this issue without having to save form data?

[1]: https://git.framasoft.org/public/projects

**Comment by t-wissmann** [comment]
I don't think there is a way to submit the right form without remembering which form it was. One workaround is to ask the user to focus some field of the form before filling username and password and submitting the form.

Personally, don't like automatic form submission at all (not only because it causes implementation troubles). Mainly because without auto-submission, the user has the chance to double check that at least the right username has been entered. The annoying thing of login-forms is to pick the right password (one should have separate passwords for separate websites). However, the additional time/effort needed for manual form submission is insignificant. :-)

**Comment by The-Compiler** [comment]
This has been stalled for a long time now, and as mentioned I'd rather wait until there's a plugin API. Until then, the `password_fill` userscript should be suitable.

I added the patch to #180 to make sure it doesn't get lost, so I'm closing this now. Thanks for your contribution anyways, @antoyo!

**Pull request closed without merging**
