### PR TITLE
Add :navigate strip

### PR DESCRIPTION
**Pull request by steils**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4438)

### CODE REVIEW

**Comment by rcorre** [comment]
LGTM, but it seems like `test_stripping_a_label` is failing on the pyqt571 and pyqt59 tests:

- https://travis-ci.org/qutebrowser/qutebrowser/jobs/459573645
- https://travis-ci.org/qutebrowser/qutebrowser/jobs/459573646
- https://travis-ci.org/qutebrowser/qutebrowser/jobs/459573647

Might be that `QUrl.RemoveFragment | QUrl.RemoveQuery` worked differently on older qt versions?

**Comment by The-Compiler** [comment]
FWIW I don't think this should be bound to a key by default.

**Comment by jgkamat** [comment]
The stripping label tests are failing because the test framework thinks the page isn't loading with anchors (?):

```
----> Waiting for re.compile("(load status for <qutebrowser\\.browser\\..* tab_id=\\d+ url='http\\:\\/\\/localhost\\:… in the log
19:22:57.011 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('http://localhost:34963/data/navigate#label')) (tab 1)
19:22:57.011 DEBUG    webview    tabbedbrowser:on_title_changed:623 Changing title for idx 1 to 'Navigate'
19:23:01.863 DEBUG    ipc        ipc:on_timeout:369 on_timeout got called with None socket!
```

We could probably just ignore them on older qt versions, or turn these into unit tests.

**Comment by The-Compiler** [comment]
Thanks @steils for the PR and @rcorre @jgkamat for the reviews/comments! Merged with a couple of related changes:

- 30a0fdfc1 Remove default binding for `:navigate strip`
- 32c95b5ab Simplify :navigate command
- b784438e3 Turn some :navigate tests into unit tests
- 7b08c3e28 Check URL validity for :navigate up/strip
- f3f19dad6 Improve :navigate strip docs

**Comment by steils** [comment]
Sorry, I abandoned it, got other thing to do, then forgot:( Thank you very much for finishing

**Comment by The-Compiler** [comment]
Dang, looks like I messed things up and `:navigate strip` actually crashes - fixed now. :see_no_evil:

**Pull request merged**
