### PR TITLE
change the code for the renamed preferences

### PR DESCRIPTION
**Pull request by dkanada**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3261)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks for the update! Note that you can push changes to an existing PR (by just pushing more changes to the existing branch) :wink:

**Comment by dkanada** [comment]
I have never tried merging lots of changes to master from a pull request though =p and my fork was probably over two hundred commits behind. I figured it would be easier to fork it again rather than try to merge.

**Comment by dkanada** [comment]
Let me know if I missed any references in the code, otherwise I think this should be all of the changes.

**Comment by The-Compiler** [comment]
The main problem I can see with `tabs.width.bar` now becoming `tabs.width` is that when you have an old `config.py`, there's no nice error shown:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configfiles.py", line 418, in read_config_py
    exec(code, module.__dict__)
  File "/home/florian/.config/qutebrowser/config.py", line 21, in <module>
    c.tabs.width.bar = 100
AttributeError: 'str' object has no attribute 'bar'
```

But I guess people will manage to find out what's going on.

**Comment by The-Compiler** [comment]
I just noticed that you edited `doc/help/settings.asciidoc` by hand - don't do that, see the comment at the beginning of the file :wink:

**Pull request merged**
