### PR TITLE
Add new ua_fetch script

### LINKED ISSUE #5804: Reintroduce script for updating user agents
The [completions](https://github.com/qutebrowser/qutebrowser/blob/v1.14.0/qutebrowser/config/configdata.yml#L576-L586) for the `content.headers.user_agent` setting needs to be updated periodically to keep the suggested user agents recent.

We used to have a [script](https://github.com/qutebrowser/qutebrowser/blob/v1.8.3/scripts/dev/ua_fetch.py) to generate those entries, but it was removed in 5e64aae70be25e8871846af15ff92cfce7a816d9 because the underlying [website](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/) added cloudflare protection so it's not possible to get the UAs automatically anymore.

However, it looks like there's a project called [top-user-agents](https://github.com/Kikobeats/top-user-agents) which periodically updates a [JSON file](https://github.com/Kikobeats/top-user-agents/blob/master/index.json) with the same information in a machine-readable format.

With that it should be possible to add a new script to `scripts/dev/` again, which does something like this:

- Use `requests` to fetch this JSON file from GitHub
- Get the entries using Python's `JSON` module
- Parse those user agents, perhaps using [`websettings.UserAgent.parse`](https://github.com/qutebrowser/qutebrowser/blob/v1.14.0/qutebrowser/config/websettings.py#L39-L78) from qutebrowser.
- Discard any user agent which is not Chrome (anything that doesn't contain `Chrome/...`; or anything that contains `Edg/...` or `OPR/...`)
- For each of Windows/Mac/Linux, find the user agent with the newest Chrome version and print it.

In a later step, that script could then be improved to automatically update `configdata.yml` instead of printing the user agents, and finally, this could be integrated with [GitHub Actions](https://github.com/features/actions) to automatically send a pull request once a month or so to update the values in the repository (or instead it could be added to the release automation).

### PR DESCRIPTION
**Pull request by ninewise**
It's been a while since I did a contribution and this seemed something nice to do during midday break. Closes #5804. Implementation is almost exactly as asked, except I did the filtering of non-Chrome user agents before parsing (the parser crashed on a missing key `AppleWebkit` if I didn't).

### CODE REVIEW

**Comment by The-Compiler** [comment]
That was quick! :smile: 

Could you make sure the script outputs the UAs in the same format as [configdata.yml uses](https://github.com/qutebrowser/qutebrowser/blob/v1.14.0/qutebrowser/config/configdata.yml#L578-L586) (including line wrapping, e.g. using the `textwrap` module)? That way, it should be possible to update them from inside vim easily again.

**Review by The-Compiler — CHANGES_REQUESTED** [review]
Right now this seems to print entires for `Windows NT 6.3` and `Intel Mac OS X 10_13_6` which are both quite old. Currently we have `Windows NT 10.0` and `Intel Mac OS X 10_15_6` in the config - I'd expect those to be more popular than the one printed in the script, but maybe I'm wrong and we'd need some additional filtering/sorting based on OS versions?

Also, it'd be good if the name printed could be e.g. `Chrome 85 Win10/Linux/macOS`, similar to what's in `configdata.yml` currently.

**Comment by ninewise** [comment]
Somehow, `Windows NT 6.3` has a `Chrome/85.0.4183.102` which is more recent (I presume) than the `Chrome/85.0.4183.83` in combination with `Windows NT 10.0` (but less popular). Similar for the Macintosh user agents. I could fix this by (1) comparing only the first 2 numbers in the Chrome version or (2) parsing the OS version string (but that seems unstable to me).

**Comment by The-Compiler** [comment]
Thanks! Merged with a couple of minor changes?

- 11d6cd805 scripts: Fix docstring
- 4e887b89d scripts: Quote resulting UA
- 0f15b3fba Regenerate UAs

**Pull request merged**
