### PR TITLE
Add argument extra-url-suffixes

### PR DESCRIPTION
**Pull request by frelon**
Solves #5063

### CODE REVIEW

**Comment by The-Compiler** [comment]
I thought #4888 already allowed for `.local` domains? cc @Holzhaus

**Comment by frelon** [comment]
It doesn't seem to work with sub-domains to *.local...
I tried it with URL https://test.company.local and a password in company.local/username and I got the error 

```
Process stderr:
No pass candidates for URL 'https://test.company.local' found! (I tried ['test.company.local'])
```

**Comment by Holzhaus** [comment]
@The-Compiler The fix was to join subdomain and domain if and only if suffix is empty. This should also work for subdomains:

```python
$ python
Python 3.7.4 (default, Oct  4 2019, 06:57:26)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tldextract
>>> tldextract.__version__
'2.2.1'
>>> tldextract.extract('https://company.local')
ExtractResult(subdomain='company', domain='local', suffix='')
>>> tldextract.extract('https://test.company.local')
ExtractResult(subdomain='test.company', domain='local', suffix='')
```

Maybe @frelon's tldextract version is outdated/buggy?

**Comment by The-Compiler** [comment]
If I'm reading the output above right, that's happening for @frelon as well (it looks like `qute-pass` did try `test.company.local`), but @frelon expected `company.local` to be tried - correct?

**Comment by frelon** [comment]
Exactly @The-Compiler, It does try the full URL but I would like it to use the company.local one if it exists (Same AD-account for all *.company.local sites)

**Comment by Holzhaus** [comment]
In that case we should probably use `str.rpartition` to split the subdomain to add `company.local` to the candidate list, too. Specifying extra suffixes manually is cumbersome and shouldn't be necessary.

**Comment by The-Compiler** [comment]
Doesn't hurt to add this though, IMHO - thanks @frelon!

**Pull request merged**
