### PR TITLE
Add a setting to paste images from clipboard

### LINKED ISSUE #5256: Can't paste images from clipboard / expose JavascriptCanPaste
**Version info**:
qutebrowser v1.10.1
Git commit: df45e7401 (2020-02-22 10:27:28 +0100)
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

**Description**
Can't paste a image from clipboard in qutebrowser, I try this coping from gimp, when paste gimp crash. I also test it with Photoshopea an online image editor, in this case nothing happen. It works fine in Brave (Chromium).

**How to reproduce**
1.- Open an image with a image editor.
2.- Use the select tool for select a part of the image.
3.- Copy that with ctrl+c.
4.- paste it in a Facebook comment input or any other input field with image compatibility.

### PR DESCRIPTION
**Pull request by Lembrun**
Close #5256  also see the last comment on it, to reproduce the gimp crash(I'll report the error to gimp if there is not an issue already)

### CODE REVIEW

**Review by The-Compiler — CHANGES_REQUESTED** [review]
Hmm, given that those two settings are dependent on each other, I think it'd be better to have a single setting `content.javascript.clipboard` with values like `none`, `read` and `read-write` or so. What do you think?

If you agree, you can change the `Attr(...)` calls to have a `converter` (like `content.desktop_capture`), do the same change for `can_access_clipboard` in `webkitsettings.py` as well, adjust `configdata.yml` accordingly and finally add a `self._migrate_renamed_bool` call in `qutebrowser/config/configfiles.py` (in `YamlMigrations`) to migrate existing configs.

**Comment by Lembrun** [comment]
Yeah it makes sense to merge the settings, apparently you can't separate the `can_acces_clipboard` into `read` and `read-write`, so no need for a `read` gonna juste be a `read-write`

I did more test with the [photo site](photopea.com) and for whatever reasons you can't copy an image from it to the clipboard, their function returns false (but I can't be bothered to check their 10k+ lines of minified js)

With local examples everything works as expected.

**Comment by The-Compiler** [comment]
Hmm, then maybe name them `access` and `access-paste` or something? The [Qt docs](https://doc.qt.io/qt-5/qwebenginesettings.html#WebAttribute-enum) say:

> - JavascriptCanAccessClipboard: Allows JavaScript programs to read from and write to the clipboard. Writing to the clipboard is always allowed if it is specifically requested by the user. See JavascriptCanPaste to also allow pasting the content of the clipboard content from JavaScript. Disabled by default.
> - JavascriptCanPaste: Enables JavaScript `execCommand("paste")`. This also requires enabling JavascriptCanAccessClipboard. Disabled by default.

**Comment by Lembrun** [comment]
Yeah I understood it like (for the writing to clipboard) you get  prompted for it or you do it  by e.g doing a command in js to copy something to your clipboard and then it's going to write to your clipboard

And from what I can see in the python shell there is only

```
 QWebEngineSettings.JavascriptCanAccessClipboard.
QWebEngineSettings.JavascriptCanAccessClipboard.as_integer_ratio(  QWebEngineSettings.JavascriptCanAccessClipboard.imag
QWebEngineSettings.JavascriptCanAccessClipboard.bit_length(        QWebEngineSettings.JavascriptCanAccessClipboard.numerator
QWebEngineSettings.JavascriptCanAccessClipboard.conjugate(         QWebEngineSettings.JavascriptCanAccessClipboard.real
QWebEngineSettings.JavascriptCanAccessClipboard.denominator        QWebEngineSettings.JavascriptCanAccessClipboard.to_bytes( QWebEngineSettings.JavascriptCanAccessClipboard.
```
And the current setting doesn't do the distinction so I guess I am  missing something  if there is a setting for that.

**Comment by Lembrun** [comment]
Also did more testing with ungoogled-chromium,brave and you can't copy an image from photopea to the clipboard same error in their js. I've never actually used this feature before so I don't know about other sites where this kind of writing to the clipboard via js is supposed to work.

Not too bad ? Since the original request was just pasting from clip to site ?

**Comment by The-Compiler** [comment]
I don't follow anymore. QtWebEngine has two different settings for this, `QWebEngineSettings.JavascriptCanAccessClipboard` and `JavascriptCanPaste`. However, since enabling `JavascriptCanPaste` also requires enabling `JavascriptCanAccessClipboard`, I am suggesting that we expose it in one single qutebrowser setting taking three values instead of making it two settings.

**Pull request closed without merging**
