### PR TITLE
Add an extra Tab for GitHub login

### LINKED ISSUE #5984: qute-pass support for GitHub
qute-pass userscript currently does not work for https://github.com/login

### PR DESCRIPTION
**Pull request by ssiyad**
Closes #5984

### CODE REVIEW

**Comment by The-Compiler** [comment]
I'm not really a fan of this to be honest - we'd need to add more and more "workarounds" for different sites. IMHO those edge-cases are better served by the `--username-only` and `--password-only` arguments to the script.

@bascht @lufte what's your take on this?

**Comment by lufte** [comment]
Huh, this looks like Github messed it up. I remember this working in the past. 

Yeah, I don't think we should start including these workarounds in the userscript, specially in cases like this where the site could get fixed in a couple of days and now you have to revert the changes. The userscript is supposed to work on most sites, not all of them. However, we could look into better approaches than "hitting Tab", like focusing the correct inputs based on the elements' `type` or something.

**Comment by ssiyad** [comment]
Agree. This PR is more of an hot-fix than a proper solution. I'll try improve it

**Comment by ssiyad** [comment]
@The-Compiler I changed the logic from `fake-key` to `jseval`. Please check and comment

**Comment by The-Compiler** [comment]
Still not sure what to think about it, I suppose it'll just break other corner cases instead... FWIW there's also the `password_fill` script by @t-wissmann which uses JS to find and fill the fields.

Would be great to hear some other opinions on this, though.

**Comment by lufte** [comment]
Hmm, I agree that this will break more cases than it fixes. What I had in mind is:
1- Keep the current behavior with the user input (meaning: don't try to focus it).
2- Focus the password field based on the "type" attribute. Like you do now, but forget about the element's id, as it's not required to have any particular value. The type _should_ be "password" though.

That could still break if there are multiple inputs with type="password" or none (maybe the fields are some fancy components made with React or something). I wouldn't mind testing it with my logins though.

I didn't know about that other userscript. It's approach could work too.

**Comment by The-Compiler** [comment]
As the original issue was fixed on GitHub's side and it's unclear if this change makes things better or worse (probably both, depending on the page), I'm closing this.

In the long run, I plan to add some kind of API in qutebrowser for password management (#30), so that userscripts won't have to care about details like this. Then, with testcases and such, things can be improved there.

**Pull request closed without merging**
