### PR TITLE
Support playlist in mpv userscript.

### PR DESCRIPTION
**Pull request by jnphilipp**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3057)

### CODE REVIEW

**Comment by The-Compiler** [comment]
It looks like always passing `--ytdl-raw-options=yes-playlist=` does no harm, but I'm not sure there should be a lot of option customizing in here.

What about adding `$@` to the arguments though, so you could do `:spawn -u view_in_mpv --ytdl-raw-options=yes-playlist=` (or keybind/alias that) though?

cc @t-wissmann

**Comment by jnphilipp** [comment]
I think that playlist is something the userscript should handle automatic. Since IMO that is the expected behavoir, when opening an playlist link on youtube.

**Comment by t-wissmann** [comment]
I'd refrain from putting anything specific to youtube urls in the script and so I vote for either expanding the last line to
```
"${video_command[@]}" "$@" "$QUTE_URL"
```
or/and to include `"--ytdl-raw-options=yes-playlist="` in the `video_command` array. I'm fine with doing both, because the `"$@"`-change is a good idea anyway! :-)

**Comment by jnphilipp** [comment]
I think putting it in the ```video_command``` is a good compromise. I'll change it accordingly.

**Comment by The-Compiler** [comment]
Seems fine to me - thanks!

**Pull request merged**
