### PR TITLE
Check if the tab is current in HintManager._start_cb

### PR DESCRIPTION
**Pull request by user202729**
Reopen this because accidentally closed #4763.

Currently tabbed_browser and tab are not check for None because

> I think at this time, the tab should not be closed (because otherwise find_css would raise an error), so tabbed_browser cannot be None.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4764)

### CODE REVIEW

**Comment by user202729** [comment]
(force pushed to fix code style) The problem is (I think) tabbed widget doesn't override the `widget.currentWidget().tab_id` attribute (`currentWidget()` just return the real object), so the test think that the tab is wrong.

**Comment by user202729** [comment]
Note that the test is failing (the bug does not happen) on qtwebkit because `find_css` is synchronous. Should I use `@qtwebkit_skip` or the old test approach (

```
And I wait for 0.5s
And I run :follow-hint a
Then no crash should happen
```

), or
```
And I wait for 0.5s
And I run :follow-hint a
Then the error "follow-hint: This command is only allowed in hint mode, not normal." should be shown
```
?

**Comment by The-Compiler** [comment]
I'd prefer the old test approach - the second example looks good, except I'd still prefer waiting for the log (e.g. `And I wait for "hints: *" in the log`) instead of hardcoding 0.5s.

**Comment by The-Compiler** [comment]
Looks great now, thanks!

**Pull request merged**
