### PR TITLE
Load icons via importlib.resources

### PR DESCRIPTION
**Pull request by toofar**
The PyQt resources system is gone in 6.2 and deprecated before that. This should be the last usage of it.

Switches icons to be read with `utils.resources.read_file_binary()` in `notification.py` (fallback desktop notification icon) and `app.py` (icon for the desktop window).

importlib only loads resources under a package, so the icons are moved under the `qutebrowser/` directory.

I've gone looking for other references to the icons and they all look understandable from reading them to be honest, so I'm optimistic. There's a couple of places that referenced icons that didn't need updating because that was referencing after they had been copied from source.

I've tested what I could running from git (notification fallback icon shows up, windows get icons and multiple icons show up in xprop). I haven't tested setup.py/Makefile or Windows or Mac. Not sure if I can test the last two. I can try the Makefile installation at least tomorrow or so.

Let me know what other QA stuff I should do to make this more convincing.

I guess there should be a changelog entry which highlights this for packagers, although there will be a lot of them over the next couple of weeks I'm sure.

Closes: #6062

### CODE REVIEW

**Comment by The-Compiler** [comment]
> There's a couple of places that referenced icons that didn't need updating because that was referencing after they had been copied from source.

I don't understand what you mean by this. Can you elaborate?

> I've tested what I could running from git (notification fallback icon shows up, windows get icons and multiple icons show up in xprop). I haven't tested setup.py/Makefile or Windows or Mac. Not sure if I can test the last two. I can try the Makefile installation at least tomorrow or so.

Yeah, I suppose it'd be good to test the makefile just to make (hah!) sure it works. Would also be good to test `python3 scripts/asciidoc2html.py --website tmpout; cd tmpout; python3 -m http.server` and then visiting `localhost:8080` looks as expected.

I can give it a try with the Windows/macOS PyInstaller stuff, probably easiest since I have the environments for that set up already. But it looks pretty good indeed already judging from the diff!

> 
> Let me know what other QA stuff I should do to make this more convincing.

**Comment by toofar** [comment]
>> There's a couple of places that referenced icons that didn't need updating because that was referencing after they had been copied from source.

> I don't understand what you mean by this. Can you elaborate?

Oops, tried to refactor the sentence and broke it. I mean there are a couple of places that reference /icons/... paths without a "qutebrowser" parent directory, but that's fine because they only refer to files that have already been copied into a new folder just for them. In particular this is in www/header.asciidoc, where the icons would have been copied by asciidoc2html.py already, and misc/Makefile where `/icons/hicolor/...` is referenced but that directory had the icons copied into it earlier in the same file.

> Would also be good to test python3 scripts/asciidoc2html.py --website tmpout; cd tmpout; python3 -m http.server and then visiting localhost:8080 to ensure it looks as expected.

Aha, yes. That does work better than visiting it via file:// :smile: 

image

**Review by The-Compiler — CHANGES_REQUESTED** [review]
The PyInstaller builds don't work yet:

```
Traceback (most recent call last):
  File "qutebrowser\__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "qutebrowser\qutebrowser.py", line 245, in main
    return app.run(args)
  File "qutebrowser\app.py", line 123, in run
    init(args=args)
  File "qutebrowser\app.py", line 152, in init
    _init_icon()
  File "qutebrowser\app.py", line 187, in _init_icon
    pixmap.loadFromData(resources.read_file_binary(filename))
  File "qutebrowser\utils\resources.py", line 136, in read_file_binary
    return path.read_bytes()
  File "pathlib.py", line 1259, in read_bytes
  File "pathlib.py", line 1252, in open
  File "pathlib.py", line 1120, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\florian.bruhin\\proj\\qutebrowser\\dist\\qutebrowser-2.5.0-x64\\icons\\qutebrowser-16x16.png'
```

Looks like we need to add it to `data_files` so they are actually copied:

```diff
diff --git a/misc/qutebrowser.spec b/misc/qutebrowser.spec
index 11eb11c7d..60729266e 100644
--- a/misc/qutebrowser.spec
+++ b/misc/qutebrowser.spec
@@ -15,6 +15,7 @@ def get_data_files():
     data_files = [
         ('../qutebrowser/html', 'html'),
         ('../qutebrowser/img', 'img'),
+        ('../qutebrowser/icons', 'icons'),
         ('../qutebrowser/javascript', 'javascript'),
         ('../qutebrowser/html/doc', 'html/doc'),
         ('../qutebrowser/git-commit-id', '.'),
```

I suppose other than that, it should be ready? Couldn't really figure out how to best test the makefile install without actually installing it system-wide, but it seems to look fine from a quick look at the file tree.

**Comment by toofar** [comment]
Ah, nice. I installed via Makefile to a chroot and it seemed to work well enough (after I fixed the other place I missed). As in I could see multiple icons in xprop, I only had Qt5.12 in that chroot though so couldn't test notifications. I could see the icons got copied over though.

I had to work around the "man" target of the makefile because asciidoc runs xmllint with "--nonet" so can't verify external schemas:
```
"xmllint" --nonet --noout --valid "/home/user/projects/qutebrowser/doc/qutebrowser.1.xml"
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/home/user/projects/qutebrowser/doc/qutebrowser.1.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
/home/user/projects/qutebrowser/doc/qutebrowser.1.xml:5: validity error : Validation failed: no DTD found !
```
:shrug:

**Comment by The-Compiler** [comment]
Thanks, great work! Seems to work fine for PyInstaller now too. One tiny step closer to Qt 6 support! :tada:

**Pull request merged**
