### PR TITLE
Support pasting text that starts with a hyphen

### PR DESCRIPTION
**Pull request by toofar**
My password generator found this one.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Huh, I don't think this should happen. When I copy `-foo` to primary selection and run `:insert-text {primary}` (or `:message-info {primary}`), everything works as expected.

@toofar Does your password setup use `:insert-text` directly, not `:insert-text {primary}` maybe?

**Comment by toofar** [comment]
Keepass puts it in primary selection and I press shift+insert to paste.

**Comment by user202729** [comment]
> Huh, I don't think this should happen. When I copy `-foo` to primary selection and run `:insert-text {primary}` (or `:message-info {primary}`), everything works as expected.

It doesn't work properly for me, even if it's run directly in the command-line instead of binding to a key.

**Comment by The-Compiler** [comment]
Hmm, I just tried again and could reproduce it - not sure what I did differently last time, my bad!

Long-term there should probably be a proper fix for this (see #2017), but until then, this seems like a good idea - thank you!

**Pull request merged**
