### PR TITLE
Add cosmetic filtering and scriptlet injection

### PR DESCRIPTION
**Pull request by alkim0**
# This was for the old master (before the Qt 6 merge), please see #7629 for the new pull request

This pull request contains the implementation for cosmetic filtering and scriptlet injection. Addresses #6480.

The main body of the code for this is spread over the two files: `components/braveadblock.py`, and `components/ublock_resources.py`.

Note that these changes work only for WebEngine.

Cosmetic filtering is implemented in two steps. First, before the page loads, the Brave ad blocker engine is queried for URL-specific filters that should be applied. The user-specified css (using `stylesheet.js`) is then updated to include these filters via the newly added `add_dynamic_css` function. Next, after the page loads, an asynchronous javascript function gets the list of classes and ids generated on the current page. The callback to this function calls the Brave ad blocker with this information and applies the returned generic filters, once again using the `add_dynamic_css` function. To facilitate this, the following APIs have been added: `api.hook.before_loaded`, `api.hook.load_started`, `api.hook.load_finished`, `api.Tab.add_dynamic_css`, `api.Tab.remove_dynamic_css`. In addition, the change mentioned in the critical changes section was implemented.

For scriptlet injection, in addition to the filter lists, additional javascript templates/functions need to be downloaded and added to the Brave ad blocker before working properly. The `:adblock-update-resources` command was added to perform this action. The code for this mostly lies in `components/ublock_resources.py` and takes heavy inspiration inspiration from the original Brave ad blocker implementation (specifically https://github.com/brave/adblock-rust/blob/master/src/resources/resource_assembler.rs). It downloads the resources specified by ublock's [redirect-engine.js](https://github.com/gorhill/uBlock/blob/master/src/js/redirect-engine.js) as well ublock's [scriptlets.js](https://github.com/gorhill/uBlock/tree/master/assets/resources) and caches them. These resources are not expected to change as often as the filter lists, so they are managed separately. In addition, the urls are fairly unintuitive to the user, so they were not added as a config option, but rather hardcoded into the code.

In addition to the added resources, ublock's filter lists make liberal uses of aliases, but the current version of python-adblock does not support it. A pull request to support aliases is currently pending (https://github.com/ArniDagur/python-adblock/pull/70), but in the mean time, https://github.com/alkim0/python-adblock must be used to fully support scriptlets.

The scriptlets are injected at the same time as the dynamic css (i.e., during the `api.hook.before_loaded`), and uses the newly added function `add_web_script` to do this. The following API changes have been made to support scriptlet injection: `api.Tab.add_web_script`, `api.Tab.remove_web_script`, `api.usertypes.InjectionPoint`.

Finally, a unit test regarding adblocker resources and cosmetic filtering has been added.

P.S.
The `qutebrowser/utils/resources.py` file failed the coverage test before I made any changes.

# Critical Changes
In addition to being emitted during `_load_url_prepare`, the `api.tab.Tab.before_load_started` signal is now also emitted during `_on_navigation_request`. The reason for this is that `_load_url_prepare` is not always called before a new page loads. For example, this can happen when a non-clickable object is clicked to open in the background. In this case, `TabbedBrowser.tabopen` will be called with `url=None`, so `load_url` and `_load_url_prepare` are not called. However, `_on_navigation_request` is always called, and the url is always known by this point. For a reliable `api.hook.before_loaded` hook, it is essential we emit `before_load_started` during `_on_navigation_request` as well. We don't want to remove the emit from `_load_url_prepare` either, since that gets called before `_on_navigation_request`, and we need the hook to fire as soon as possible.

# API Changes
## `api.hook.before_loaded`
A hook that is guaranteed to be notified before a page loads. Components which need to do something before a page loads should use this hook. The hook may be called multiple times before a page loads. The `api.Tab` object which is about to load and the url which we are about to load are passed in as arguments.

## `api.hook.load_started`
A hook that is guaranteed to be notified after the page loads. Components which need to do something after a page starts loading should use this hook. The `api.Tab` object which is starting to load is passed in as an argument.

## `api.hook.load_finished`
A hook that is guaranteed to be notified after the page finishes loading. Components which need to do something after a page load finishes should use this hook. The `api.Tab` object which just finished loading and the success flag of whether the load was done successfully is passed in as arguments.

## `api.Tab.add_dynamic_css`
Adds css which will get applied to every page the `api.Tab` object loads. This has lower precedence than the user-specified stylesheet in the user config. This css is expected to change often, hence the "dynamic".

## `api.Tab.remove_dynamic_css`
Removes the aforementioned css which will get applied to every page the `api.Tab` object loads.

## `api.Tab.add_web_script`
Adds a snippet of javascript to be executed during the `api.Tab` object's page load. The specific moment in which the web script executes can be controlled with `api.usertypes.InjectionPoint`. These "web scripts" are intentionally separated from the greasemonkey scripts. Greasemonkey scripts are added and managed by the end user, but these scripts are meant to be used by the components within qutebrowser. This interface also allows for more control over exactly how the added scripts will be executed.

## `api.Tab.remove_web_script`
Removes the aforementioned snippet of javascript to be executed during the `api.Tab` object's page load. 

## `api.usertypes.InjectionPoint`
A type representing the point at which to execute an injected web script.

# Other changes to core implementation
* `_update_stylesheet` now also includes `stylesheet.js` in its injected script (wrapped in the global wrapper) because sometimes asynchronous code runs before injected scripts, and `stylesheet.set_css` will obviously fail if `window._qutebrowser.stylesheet` has not been specified.
* Added additional javascript logging to scripts to denote when certain scripts are run (only if the current logging level is DEBUG).

# Other considerations
* Currently, querying the ad blocker for cosmetic filters is in the critical path. To some degree, this is necessary since scriptlets need to be injected upon document creation (otherwise they won't take effect on current page load).
* Right now, the generic css is gathered and applied in one go at the end using the `load_finished` hook, to make this faster, we may want to have some javascript observe the DOM and update as we go along, but this likely requires QT's web channels.
* Brave's ad blocker comes with a resource assembler which can help us get rid of a lot of the code in `components/ublock_resources.py`, but python-adblock does not have the interface implemented for that. In the future, if/when python-adblock does implement the interface, we should move the code out from `components/ublock_resources.py`, but for now, I did it this way just to get things working.

# Qt 6
To try this PR with Qt6, use the branch `adblock-qt6` instead of `master`.

### CODE REVIEW

**Comment by darthdubu** [comment]
I don't know anything about programming but I just wanted to say thankyou for working on this and I'm very happy to see that it will hopefully be implemented sometime soon. I may even try to figure out how I can test it out as is. Great work, qutebrowser is so awesome and I really want to stick with it even with some of the shortcomings.

**Comment by darthdubu** [comment]
I've built it using ```python3 scripts/mkvenv.py``` however upon launching it with ```.venv/bin/python3 -m qutebrowser```
I get this
image
I am able to do :adblock-update-resources and it appears to do its function successfully however I can't actually load any websites to test whether it does work correctly. 

image

The resulting browser is really glitchy and weird. Perhaps I'm missing libraries? It could be user error as I've never done this before.

**Comment by The-Compiler** [comment]
@darthdubu Try with `--pyqt-type link` so it uses your system-wide Qt install - the binary Qt is too old to work with more recent glibc versions.

**Comment by darthdubu** [comment]
Thanks that did the trick. It's up now but I don't believe it's working at least not on youtube.
image
I ran :adblock-update and :adblock-update-resources

**Comment by alkim0** [comment]
@darthdubu Did you add the ublock filters to your config file?

For a quick howto, see (https://github.com/qutebrowser/qutebrowser/issues/6480#issuecomment-1182499581)

**Comment by nonetrix** [comment]
Just commenting here so Github notifies me about this

Looking forward to this. Sorry for annoying you, but seems to be the only way however

**Comment by The-Compiler** [comment]
@nonetrix you can simply click the "subscribe" button in the sidebar...

**Comment by The-Compiler** [comment]
I haven't had a chance to take a closer look at this so far (and it will probably take me a while, given how big this PR is), but FWIW, I got this crash report:

```
Traceback (most recent call last):
  File "/home/bs/qutebrowser/qutebrowser/components/ublock_resources.py", line 226, in _on_all_resources_downloaded
    engine_info.engine.add_resource(  # type: ignore[call-arg]
TypeError: argument 'content_type': 'list' object cannot be converted to 'PyString'
```

**Comment by alkim0** [comment]
@The-Compiler Can I ask what version of python-adblock you have? I added a check to ensure that interface is only used with versions greater than 0.5.2, but it seems to be calling it regardless.

Note that for the full benefits of this patch, you need an updated version of python-adblock. (See https://github.com/qutebrowser/qutebrowser/issues/6480#issuecomment-1182499581). Of course, this shouldn't be required, so there's still a bug here somewhere.

**Comment by The-Compiler** [comment]
Note that wasn't my setup, this was from a crash report someone submitted (anonymously). They're indeed on python-adblock 0.6.0, so I suppose that was it.

Some early feedback from the CI before I look into this in more detail:

- Tests [seem to fail](https://github.com/qutebrowser/qutebrowser/runs/7510480552?check_suite_focus=true) on Windows
- They also [seem to crash](https://github.com/qutebrowser/qutebrowser/runs/7510480698?check_suite_focus=true) on QtWebKit. While the new feature doesn't need to work there, it shouldn't crash either. While there are plans to remove QtWebKit for v3.0.0, it might make things easier if it still works correctly until that's the case.
- In a previous CI run, I also spotted some renderer process crashes. Not sure what that was about, or why they are gone now. Do you have any idea how this affects e.g. RAM usage in renderer processes?

**Comment by nonetrix** [comment]
Off topic

Why does Qutebtowser still support QTWebKit? seems deprecated unfortunately, like the idea of WebKit support but QT implementation isn't ideal. Would it be possible to embed WebKitGTK?

**Comment by The-Compiler** [comment]
@nonetrix please do a quick search for more related places for off-topic questions - e.g. the relevant issue (#4039 in this case), or [other discussion channels](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/index.asciidoc#getting-help). I'm assuming there will be *many* comments related to this PR over its lifetime (given how big this is), and off-topic comments just make things harder in that regard.

**Comment by alkim0** [comment]
@The-Compiler This shouldn't have much of an effect on RAM, unless the underlying adblock engine itself takes a lot of RAM, but I don't think that should be the case either.

**Comment by alkim0** [comment]
@The-Compiler I can't figure out the `qtnetwork-download-manager` error which only happens on windows. I think perhaps I'm setting the tests up wrong, but I have no idea what's wrong exactly...

Regarding the `TimeoutError`, the only thing that I can think of is `components/braveadblock.py` runs some asynchronous javascript code in `update_cosmetic_filters` and perhaps that's taking a while to return? I'm not sure what else it would be.

If you have any insights, I'd appreciate it.

It's difficult to pinpoint these bugs since they don't occur on my personal setup.

**Comment by bqv** [comment]
Hi @alkim0 ,

I tried this patch on 2.5.2, and the browser runs, but :adblock-update-resources fails with "redirect-engine.js could not be parsed"

**Comment by zooki2006** [comment]
> Hi @alkim0 ,
> 
> I tried this patch on 2.5.2, and the browser runs, but :adblock-update-resources fails with "redirect-engine.js could not be parsed"

ditto

**Comment by duarm** [comment]
same from the two above, logs

```
16:12:20 DEBUG    downloads  downloads:_remove_item:997 Removed download 1: redirect-engine.js [   0.00B/s|    ?|100%|15.08kB/15.08kB]
16:12:20 DEBUG    message    message:_log_stack:55 Stack for error message:
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.5.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 129, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 139, in qt_mainloop
    return objects.qapp.exec()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 317, in _on_reply_finished
    self._finish_download()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 293, in _finish_download
    self.finished.emit()
  File "/usr/lib/python3.10/site-packages/qutebrowser/components/utils/blockutils.py", line 155, in _on_download_finished
    self.single_download_finished.emit(url, download.fileobj)
  File "/usr/lib/python3.10/site-packages/qutebrowser/components/ublock_resources.py", line 334, in _on_redirect_engine_download
    message.error("braveadblock: redirect-engine.js could not be parsed")
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/message.py", line 73, in error
    stack = ''.join(traceback.format_stack())
16:12:20 ERROR    message    message:error:78 braveadblock: redirect-engine.js could not be parsed
```

**Comment by toofar** [comment]
It looks like the redirectableResources map got moved from redirect-engine.js to a new redirect-resources.js in https://github.com/gorhill/uBlock/commit/985ea24e826d62dc1f05fb09c95603780d47fbf6

**Comment by alkim0** [comment]
@bqv @zooki2006 @duarm @toofar Updated. Try the new version

**Comment by duarm** [comment]
working perfectly

pic-full-221028-1945-15

MERGE!
(I use speedtest-cli btw, entered speedtest by ookla for researching purposes)

**Comment by duarm** [comment]
working perfectly
pic-full-221028-1945-15

MERGE!

**Comment by zooki2006** [comment]
this is now working perfectly this was the one thing i was missing from qutebrowser.
thanks for the work alkim0 and for fixing it.

**Comment by alkim0** [comment]
For those who are using Qt6, a new branch `adblock-qt6` has been created (based off of `master-qt6`) and is confirmed to be working with Qt 6.4.

@The-Compiler @toofar I will close this PR and open a new one from `adblock-qt6` when `master-qt6` becomes the new `master` (I'm assuming this PR will not get merged before that).

**Comment by alkim0** [comment]
New pull request in #7629

**Pull request closed without merging**
