### PR TITLE
added completer with tab behavior to file download dialog

### PR DESCRIPTION
**Pull request by reutsharabani**
Removed `..` from file system view.

Added simple completer for the file system's tree view in the download view. Attached to the line input (user input) but doesn't filter (yet). Now iterates *completions* on tab.

Should add:
- filtering (and sorting) of the tree view on partial text
- highlighting of completion in tree view (optional: disable

### CODE REVIEW

**Comment by The-Compiler** [comment]
Hmm - this doesn't seem to do anything when pressing tab, while the previous code already did iterate over directories when doing so - or am I missing something?

**Comment by reutsharabani** [comment]
For me it iterates the possible completions (folders) from the current root directory... It doesn't select them in the view, only completes them in the line input. Does it not do the same for you?

What I've tried so far unsuccessfully is using "QFileSystemModel.setNameFilters" which fairly early "loses state". I've also tried "QSortFilterProxyModel" but it had similar issues so I've moved back to the completer which seemed to do some of what I'm trying to acheive.

I've looked for examples of the QSortFilterProxyModel but it didn't seem ot have any good ones with the QFileSystemModel. I also saw the existing completer implementation but didn't go into completion view.

During the week I'm a lot less available so even though it's not exactly a solution for the ticket - maybe others want to do it. I pushed my changes and will see if anyone wants to pick up from there as well.

I'll probably only pick it up again in a few days (weekend).

**Comment by haasn** [comment]
For me pressing `tab` pretty much just deletes the input.

**Comment by cosminadrianpopescu** [comment]
I've tested also this patch and it has the same effect. On tab it completes with the available file names. So, for example, let's say that in `/tmp` I have 3 files: `file1.txt`, 'file2.txt` and `abc.txt`. If I type in the input text `/tmp/file` and then click tab, is going to display `file1.txt` with `1.txt` selected. Then, if I click again tab, is going to display `file2.txt` with `2.txt` selected and then clicking again tab is going to display again `file1.txt`. The default behaviour, right now is that if I type `/tmp/file` and then type `tab`, is going to display `/tmp/file1.txt`, then `/tmp/file2.txt` then `/tmp/abc.txt`. Which is to say is not taking into consideration the last part. Is displaying all the options anyway.

In my oppinion this is a much needed pull request.

**Comment by reutsharabani** [comment]
Can we please try to see what the differences are that make this fail on some pcs? What qt versions are you running @The-Compiler @haasn ? I thought this is a very little change and used mostly qt native stuff. I'm surprised it didn't work. I can get to it later today if there is interest for others than myself.

I'm on the last LTS ubuntu (16.04 I think), but didn't check the qt version I'm using (currently at work).

**Comment by The-Compiler** [comment]
Qt 5.7 here, and with pretty random behavior - sometimes the input gets deleted, sometimes nothing happens, and sometimes I get a "completion" (with the text selected), but even without pressing tab.

**Comment by reutsharabani** [comment]
Thanks. I'll see what I can do to test on more environments...

**Comment by haasn** [comment]
> Qt 5.7 here, and with pretty random behavior - sometimes the input gets deleted, sometimes nothing happens, and sometimes I get a "completion" (with the text selected), but even without pressing tab.

Pretty much this, still happens on Qt 5.7.1

**Comment by reutsharabani** [comment]
@haasn I'll try and add the QT version I'm using when I'm at home (I don't have internet accessoutside work at the moment, we moved). @cosminadrianpopescu what is your QT version? If we find that its consistent in separate versions I'll happily see what I can do to make it consistent across versions.

**Comment by The-Compiler** [comment]
Yes - the CI tests on various setups (Archlinux, Ubuntu Trusty, Ubuntu Xenial, Debian Jessie, Windows, OS X) with various Qt versions

**Comment by reutsharabani** [comment]
I've just ocnfirmed that this works on qt 5.5.1. I'm not sure if python somehow uses something else. The full output of `qmake --version`: `Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu`

I can try it again, but I'd like some input if this is the behavior you aim for. I'd also need some help with where and how to test it properly.

**Comment by cosminadrianpopescu** [comment]
@reutsharabani 

```
QMake version 3.0
Using Qt version 5.7.0 in /usr/lib
```

**Comment by The-Compiler** [comment]
Any update on this, @reutsharabani?

**Comment by The-Compiler** [comment]
Closing this as you don't seem to be interested in working on this anymore, @reutsharabani. I added the patch to #2104 though to make sure nothing gets lost. Thanks for the contribution anyways!

**Comment by reutsharabani** [comment]
No problem. Life got in the way.

Great project.

**Pull request closed without merging**
