### PR TITLE
Fix FAQ grammar

### PR DESCRIPTION
**Pull request by das-g**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4428)

### CODE REVIEW

**Comment by bitraid** [comment]
Also, I'm pretty sure it's "a URL" and not "an URL".

**Comment by toofar** [comment]
Not if you pronounce URL like a german. Also I have known one (1) native english speaker who pronounced it "earl". ;)

**Comment by fiete201** [comment]
I really should lookup the rules for a vs an again :-D

**Comment by The-Compiler** [comment]
I also used to write "an user" automatically until I made Travis fail when I do that, so I [did the same](https://github.com/qutebrowser/qutebrowser/commit/2152081d82bb9ea43bfd5562c6f964ff4026f193) for "an URL" now :laughing: 

I agree the old grammar was odd, looks like that slipped through the cracks - thanks @das-g!

**Pull request merged**
