### PR TITLE
Get rid of pylint disable unused import when import is only used in type comment

### PR DESCRIPTION
**Pull request by user202729**
As suggested in #4778.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4783)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Looks like it doesn't work - pylint==2.3.1 with astroid==2.2.5 still complains on my machine with Python 3.7 - same [on Travis](https://travis-ci.org/qutebrowser/qutebrowser/jobs/532152363) as well, for some reason.

**Comment by user202729** [comment]
That's weird. I'm pretty sure that it worked when I used it at PR 4730.

**Comment by user202729** [comment]
It turns out that codes like

```
from typing import Optional
a = None  # type: Optional[str]
```

can be compiled successfully, but codes like

```
import typing
a = None  # type: typing.Optional[str]
```

reports "Unused import typing".

**Comment by The-Compiler** [comment]
Thanks for looking into it! I opened https://github.com/PyCQA/pylint/issues/2915

**Pull request closed without merging**
