### PR TITLE
Add a dead-simple mooltipass integration for password_fill

### PR DESCRIPTION
**Pull request by rrix**
This relies on behavior added to mooltipy in https://github.com/oSquat/mooltipy/pull/11 so probably
shouldn't be merged until that is merged. Wanted to make it visible at least in the meantime in case there are any Mooltipass users who want it.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2802)

### CODE REVIEW

**Comment by t-wissmann** [comment]
This code is not ready to be used, isn't it? The query entries returns nothing so, I expect `password_fill` to exit with the error message 'No entrie found for …'. So (as soon as your mooltipy-PR is merged), you should check in `query_entries` whether there is an entry in mooltipy for the current url and fill the array `files` accordingly.

**Comment by lahwaacz** [comment]
Also, please don't suggest `pip install mooltipy`.

**Comment by rrix** [comment]
> Also, please don't suggest pip install mooltipy.

Why? As far as I'm aware it's not packaged in any mainstream distribution.

**Comment by lahwaacz** [comment]
What if it will be packaged some day? There are [multiple ways to install python packages](https://stackoverflow.com/questions/42007071/when-install-external-python-packages-global-when-local-pip-or-system-package) and recommending users to blindly use one way without understanding the consequences on their system is only bound to cause trouble. I'm sure @The-Compiler could write a book about this :laughing:

**Comment by t-wissmann** [comment]
Creating an array here is quite fragile (e.g. if your password or username contains a `*`, then it is interpreted as a wildcard; yes, bash scripting is confusing). I suggest:

    output=$(mooltipy login get -w "$simple_url")
    username=${output%%$'\n'*}
    password=${output#*$'\n'}

It reads the output of mooltipy into the variable output. Everything before the first newline `$'\n'` is written to `$username`, everything after the first space into `$password`. If you insist on the array, because it is more intuitive, then you can create the array with the line

    mapfile -t < <(mooltipy login get -w "$simple_url")

And then you can access its contents as you did. I leave it up to you :-)

**Comment by The-Compiler** [comment]
Any update on this, @rrix?

**Comment by The-Compiler** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
