### PR TITLE
importer.py: add yandex browser as chrome browser

### PR DESCRIPTION
**Pull request by fridokus**
Some people use the yandex browser, which is based on chromium! Enable import from this ..

### CODE REVIEW

**Comment by The-Compiler** [comment]
Have you tested that the script actually works with Yandex?

**Comment by fridokus** [comment]
Nope.. will try and get back.. :+1:

**Comment by The-Compiler** [comment]
@fridokus So, what's the conclusion on this one?

**Comment by fridokus** [comment]
Managed to import after exporting from yandex bookmarks manager into an html file, so I guess it's not needed to add it to this list?

**Pull request closed without merging**
