### PR TITLE
Keychains in passthrough modes

### LINKED ISSUE #1044: Map key sequence against <Esc> or 'leave-mode'
Is there any way to map a sequence such as 'jk' to 'leave-mode'? Unfortunately, only combinations are supported.

Thanks for the excellent work!

### PR DESCRIPTION
**Pull request by MichaelMackus**
Will fix #1044 

One annoyance is currently there's no code to passthrough for when a user inputs for example `jj` and there's a `jk` keybinding (so, the only text that gets displayed is `j` instead of `jj`). We'll need to discuss how to resolve that.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3075)

### CODE REVIEW

**Comment by MichaelMackus** [comment]
@The-Compiler one way I resolved this before in `dwb` is by storing all the events in an array (for example, we could do this instead of storing the "_keystring" variable). Then, when we "clear" the timer we just re-emit the events that were stored (and filtered from before). We'd have to add some additional code to passthrough these events unchanged, though. Let me know your thoughts and if you can think of a better way.

**Comment by The-Compiler** [comment]
Nice! I'm not sure how to best handle the "whitelisting" for re-emitting. Unfortunately, `QKeyEvent` doesn't seem to have a good way to attach user data to it. What we could try is setting an attribute on the Python object and see whether we can still read the same attribute after it arrived in the event filter. But I doubt it...

Another way would be using `QApplication.sendEvent` and just having a flag on the event filter - unfortunately, using that has been a great recipe for segfaults in the past...

The last possibility I can think of is something similar to `_releaseevents_to_pass` in `ModeManager`, i.e. keep a list/set of keys around which should be temporarily passed and remove them once they arrived.

---

I gave this a quick test, and it seems to break in prompt modes. Since `n` is bound to `:prompt-accept no`, qutebrowser tries to reject the prompt when trying to type an `n` e.g. in a HTTP auth prompt.

Also, it'd be nice if you could take a look at `tests/unit/keyinput/` and add some new tests for this. Let me know if you need help with that!

**Comment by MichaelMackus** [comment]
@The-Compiler thanks for the input. I'll take a look at the bug in prompt modes when I find some free time.

**Comment by The-Compiler** [comment]
@MichaelMackus Any update on this? FWIW I don't think this would be useful without the re-emitting of events, which is probably quite a bit of work to get right...

**Comment by MichaelMackus** [comment]
@The-Compiler yea, I agree. I've been planning on working on this, just haven't found the time. I should have some extra time this weekend to take another look at this.

**Comment by The-Compiler** [comment]
@MichaelMackus How are things looking? I'm quite busy lately as well, so don't worry - but I'd also like to avoid having lots of "dead" PRs around :wink:

**Comment by MichaelMackus** [comment]
No extra time yet. If you'd like you can close and I'll re-open when I implement the event queue.

**Comment by The-Compiler** [comment]
Let's do that then - I added a comment to #1044 for now. Let me know if you need help with something!

**Pull request closed without merging**
