### PR TITLE
Autocommand (added the autocmd command)

### PR DESCRIPTION
**Pull request by cosminadrianpopescu**
This pull request adds autocommands. 

`:autocmd`: shows all the registered autocommands
`:autocmd <event>`: will delete all the auto commands added the `event` (if there are more than 2 a confirmation message is displayed)
`:autocmd <event> <url_pattern>`: will delete the autocommands registered for the `event` and for the given `url_pattern`
`autocmd <event> <url_pattern> <qutebrowser_command>`: adds a new autocommand for the given `event`. 

How this works: 

Basically you can add any qutebrowser command for one of the given events (`qwebview` signals):
- `loadFinished`
- `loadStarted`
- `linkClicked`
- `loadProgress`
- `statusBarMessage`
- `linkHovered`
- `selectionChanged`
- `downloadRequested`

To add a command you have to define an url pattern for which the command will be executed (`*` means in all tabs). The url pattern is just a simple regular expresison to match the tab url to know if the command should be executed or no. 

For example: 

```
:autocmd loadStarted https://popescu.eu.com.* set network ssl-strict false
:autocmd LoadFinished https://popescu.eu.com.* set network ssl-strict ask
```

This will make qutebrowser not check the invalid certificate for any request which contains `https://popescu.eu.com`. 

In order to add a new event in the list, in the `autocommands.py` file, we can add a new method and annotate it with `@add_as_event`. Then this will appear in the events list. 

In the moment that a slot is executed, the parameters given will be replaced as place holders: `{key}`. For example, for the event `downloadRequested`, the place holder `{url}` will be replaced with the url which has been clicked

`:autocmd downloadRequested * jseval alert("You clicked {url}")` will make the qutebrowser trigger an alert with the url clicked for any downloads requested. 

If you agree with the pull and you want to included in the main repository, I can also create the documentation in the `commands.asciidoc` file and also (if you are interested) I can implemnt an option to disable the events.

[Review on Reviewable](https://reviewable.io/reviews/the-compiler/qutebrowser/1155)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks, this is definitely interesting! I definitely do want to have this included, I'm just not sure if I want it before the QtWebEngine inclusion (in #666) or not. Though with the current events, I'd guess it'd work out.

In either case, this'll need some adjustments for the linters (check the [Travis-CI output](https://travis-ci.org/The-Compiler/qutebrowser/builds/94477073)) and some tests before I'll include it.

I haven't had time for a closer review yet - but from a quick look I don't see any signals connected to those autocmd slots. Did I miss something?

Also, please stop sending crash reports while developing :laughing: I got 11 crash reports with autocmd code in it so far :wink:

**Comment by cosminadrianpopescu** [comment]
The crash reports might be sent automatically, because every time I got asked I clicked `escape`. So maybe there is a bug? :)

I will try to add some tests. The events are connected in the `webview.py`: 

```
autocmds_manager = objreg.get('autocmds-manager')
autocmds_manager.register_events(page)
```

The `register_events` function will perform the connects.

**Comment by lahwaacz** [comment]
@cosminadrianpopescu How do you solve the scope of options? As far as I know, all options are (currently) global, so in the example above:

    :autocmd loadStarted https://popescu.eu.com.* set network ssl-strict false
    :autocmd LoadFinished https://popescu.eu.com.* set network ssl-strict ask

you are actually disabling certificates checking globally until a particular page is fully loaded. This is not particularly safe as loading can "freeze" due to network problems, so other pages might be loaded meanwhile. Also, is `loadFinished` guaranteed to occur after every `loadStarted` with the same domain? What if the loading fails or the site redirects?

To make it safe, I think something like vim's `:setlocal` is needed (see [this comment](https://github.com/The-Compiler/qutebrowser/issues/35#issuecomment-165381204)).

**Comment by shioyama** [comment]
Any chance this will get finished/merged? I'm actually running with this PR right now, not seeing any critical issues although my use-case is pretty simple. Would really like to see this added to master.

**Comment by cosminadrianpopescu** [comment]
@lahwaacz 
That was just an example. I don't use it this way. I actually use the autocommands to save the session. But I think that there could be other uses.

**Comment by The-Compiler** [comment]
@lahwaacz See https://github.com/The-Compiler/qutebrowser/pull/1155#issuecomment-161557322

I'm mainly focusing on tests and the new QtWebEngine backend currently, as QtWebKit has various issues - and now that it's completely unmaintained, security issues with it will probably also be ignored. This also means it's a somewhat time-critical thing, as at some point QtWebKit will probably be dropped by some distributions - it already means I'll have to stick with Python 3.4 and Qt 5.5 on Windows.

The problem is that this is a really difficult transition requiring a lot of work - so I'm trying to defer most big contributions until after that's done. In any case I'm focusing on good test coverage to make things easier - so as mentioned above, at minimum this'll need some tests.

I realize this is an unpleasant situation to be in, for me as well - but I'd really like to avoid increasing technical debt and complexity until after the transition.

**Comment by cosminadrianpopescu** [comment]
For me it's not urgent. I am anyway use the master branch distribution in which I've merged the autocommands, the pdfjs and the greasemonkey scripts. So, I suppose that other people could do the same for the time being. Anyway, because of lots of seg faults, I also look forward for the new QtWebEngine to be in place. Please let me know if I can help in anyway with the QtWebEngine.

**Comment by The-Compiler** [comment]
> Please let me know if I can help in anyway with the QtWebEngine.

Contributing tests for existing features would be most helpful - there are still some low-hanging fruits. See #999 for details, and let me know if you need help getting started!

**Comment by cosminadrianpopescu** [comment]
#999 is quite big. Do you have something in particular in mind, or I can choose anything there? Also, this is not the branch master, no? Which would be the branch to work on?

**Comment by The-Compiler** [comment]
Ideally something from the "Short-time TODO for #666" list - but anything else would be helpful too. The BDD end-to-end tests mentioned there are end-to-end tests in the [Gherkin language](https://github.com/cucumber/cucumber/wiki/Gherkin), see `tests/integration/features/*.feature`, and `conftest.py` and the other `*.py` files for the code behind the feature files.

But anything helps, unittests as well. Just pick what you think you'd like (ideally something marked as `(easy)` to start), add a comment to avoid duplicate work, and see how far you can get.

This is all on `master`, mostly in `tests/unit` and `tests/integration`. The goal is to get the current QtWebKit functionality tested before introducing QtWebEngine.

**Comment by shioyama** [comment]
@The-Compiler No worries about this, QtWebEngine is the clear priority. I'll see if I can help with the testing as well.

**Comment by The-Compiler** [comment]
@cosminadrianpopescu You asked how you could help QtWebEngine support some while back - just wanted to tell you I'm currently running [a crowdfunding](http://igg.me/at/qutebrowser) to work on QtWebEngine support full-time for a few weeks - contributing there would be an excellent way to help out too! :wink:

**Comment by cosminadrianpopescu** [comment]
Done.

**Comment by The-Compiler** [comment]
Awesome, thank you! :+1+

**Comment by The-Compiler** [comment]
This is quite outdated by now I'm afraid, and I never got around to taking another look at it - sorry! Since your forked repository seems to be gone and this needs some major updates, I'm now closing this. I added the patch to #35 though, to make sure it doesn't get lost. Thanks for the contribution anyways, @cosminadrianpopescu!

**Pull request closed without merging**
