### PR TITLE
Clear unpinned tabs before prompting user with :tab-only

### LINKED ISSUE #3461: Answering 'no' to :tab-only prompt with pinned tabs should close non-pinned tabs
If anyone prefers the current behavior of `<no>` when running `:tab-only`, please let me know here!

This will change the behavior of `<no>` to 'close all non-pinned tabs except the current one' instead of 'don't close any tabs'.

```
<hdqn> [20:54:21] :tab-only prompts to close pinned tabs and fails
    completely if denied
<tyil> [20:54:34] The-Compiler: yeah, its weird, bu tall I wanted was
    a working qutebrowser :p
<The-Compiler> [20:54:49] hdqn: I think that's intended
<hdqn> [20:55:05] I suggest at least having a setting for this - I
    expected to keep the current tab and all pinned tabs
<The-Compiler> [20:55:47] jgkamat: what do you think? ^
<hdqn> [20:59:18] 'pinned' is generally considered to mean 'immune to
    auto-moving/sorting/deletion', 'fixed in place', and there is
    literally 0 sane reason to keep :tab-only atomic
<hdqn> [21:00:29] of course I'm aware that I can just submit a PR, so
    I'll leave that here for you guys to consider ^-^
<hdqn> [21:00:50] qb is making my life so much easier <3
<***> Playback Complete.
<jgkamat> hmmmmmmmmm
<jgkamat> hdqn: so you think that if you said 'no' to the prompt, it
    should delete all non-pinned tabs?
<jgkamat> adding a setting would be easy but I don't think it would be
    needed (I don't think people would mind what happened too much). I
    would personally prefer changing the <no> behavior if that's what
    people wanted
<The-Compiler> I don't mind much either way, but I think hdqn has a
    point
<The-Compiler> "oh, I have pinned tabs, now I don't want to close
    anything at all" seems to make less sense to me than "hm, okay, I
    want to keep the pinned ones but still close the rest"
```

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #3461

If anyone thinks the new behavior seems wrong, let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3467)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Looks good, thanks!

**Comment by jb55** [comment]
I almost never want to close pinned tabs when running :tab-only, perhaps there should be a way to configure a default instead of prompting every time?

**Comment by jgkamat** [comment]
William Casarin writes:

> I almost never want to close pinned tabs when running :tab-only, perhaps there should be a way to configure a default instead of prompting every time?

Yup, it would be pretty easy to add a config setting for this, it would be a
pretty easy intro issue. Would you like to tackle it? :)

If not, file an issue and I can add an option (or we can file it as easy for
new contributors)

**Comment by jb55** [comment]
@jgkamat will do!

**Comment by The-Compiler** [comment]
FWIW I'd prefer a `:tab-only --pinned {yes,no,ask}` option (or perhaps `--with-pinned` and `--no-pinned`?) instead of an option.

**Comment by jb55** [comment]
@The-Compiler sounds good. I was also playing around with an option for explicitly enabling/disabling prompts for pinned tabs. Would a config option be ok for that? Something like this?

```patch
commit 61c95afd77846a1e0f546c2fcd9bbc1eb2e54200
Author: William Casarin <jb55@jb55.com>
Date:   Sat Aug 18 13:20:12 2018 -0700

    WIP config: add tabs.pinned.close_prompt
    
    Adds an option for configuring pinned tabs close prompt behavior
    
      - always: Always prompt close confirmations
      - never: never prompt close confirmations

diff --git a/qutebrowser/config/configdata.yml b/qutebrowser/config/configdata.yml
index 6e9515381..feec40a9f 100644
--- a/qutebrowser/config/configdata.yml
+++ b/qutebrowser/config/configdata.yml
@@ -1543,6 +1543,15 @@ tabs.pinned.ignore_tab_only:
   type: Bool
   desc: Whether the tab_only command should ignore pinned tabs.
 
+tabs.pinned.close_prompt:
+  default: always
+  type:
+    name: String
+    valid_values:
+      - always: Always prompt close confirmations
+      - never: Never prompt close confirmations
+  desc: When to prompt close confirmations for pinned tabs.
+
 tabs.pinned.shrink:
   default: true
   type: Bool
diff --git a/qutebrowser/mainwindow/tabbedbrowser.py b/qutebrowser/mainwindow/tabbedbrowser.py
index 9c4473874..0b92fbd0f 100644
--- a/qutebrowser/mainwindow/tabbedbrowser.py
+++ b/qutebrowser/mainwindow/tabbedbrowser.py
@@ -272,9 +272,17 @@ class TabbedBrowser(QWidget):
             text="Are you sure you want to close a pinned tab?"):
         """Helper method for tab_close.
 
-        If tab is pinned, prompt. If not, run yes_action.
+        If tab is pinned, check tabs.pinned.close_prompt.
+        If close_prompt is:
+          always: prompt
+          never:  dont prompt, ignore yes_action
+
         If tab is destroyed, abort question.
         """
+
+        if config.val.tabs.pinned.close_prompt == 'never':
+            return
+
         if tab.data.pinned and not force:
             message.confirm_async(
                 title='Pinned Tab',
```

**Comment by jb55** [comment]
> FWIW I'd prefer a :tab-only --pinned {yes,no,ask} argument (or perhaps --with-pinned and --no-pinned flags?) instead of an option.

@The-Compiler I was implementing this and I found the yes/no option confusing. What about:

`:tab-only --pinned {keep,close,ask}`

**Comment by jb55** [comment]
I couldn't get `:tab-only --pinned [choices]` to work, so I might have to go with `:tab-only --keep-pinned` and `:tab-only --close-pinned`

**Comment by The-Compiler** [comment]
> I was also playing around with an option for explicitly enabling/disabling prompts for pinned tabs. Would a config option be ok for that? Something like this?

Maybe just have a `:tab-close --force` or so instead? Then you can change your `d` binding to pass that argument. I try to avoid adding more and more options where command flags can do the job as well :wink:

**Pull request merged**
