### PR TITLE
Prompt when closing a pinned tab via the mouse

### LINKED ISSUE #2761: Closing a pinned tab via click does not warn before close
On current master. I'll prepare a PR to fix this, so hopefully I'll submit that soon :smile:

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #2761 

I tried to make the changes for this as small as possible, so there's probably a better way to do this, if that's the case, let me know and I'll patch it in.

Most notably, maybe I can move the `tab_close_prompt_if_pinned` wrapper function elsewhere, because it dosen't make that much sense for it to be in CommandDispatcher. If there is a better place, where should it go.

I could also move the 'check if pinning' logic higher up (into `tabbedbrowser:close_tab`), but I'm not sure if that's a good idea (would it make program structure easer or harder to read...).

Let me know what you think! :smile:

Also, is there a way to add tests for clicking on a tab? If so I can add a test for this case.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2762)

### CODE REVIEW

**Comment by The-Compiler** [comment]
I agree it's not really nice to have this as a `staticmethod` in `CommandDispatcher`. Probably makes sense to move the pinning check to `Tabbedbrowser.close_tab` indeed - however, it probably needs some `prompt_if_pinned` argument so we can set that to `False` for `:tab-detach`.

**Comment by jgkamat** [comment]
@The-Compiler, on a second look at this, we can't move the prompt logic up to `close_tab`. because then the current behavior of `:tab-only` (refusing to close any tabs if a `:tab-only` would close any pinned tabs) would be impossible without code duplication. 

I'm starting to think that this general structure seems like the best one I can think of. Maybe I could move the static method to `TabbedBrowser` and call it a day? What do you think? :confused:

**Comment by The-Compiler** [comment]
I'd say just make it a normal function in `tabbedbrowser.py` then, no need for it to be a static method.

**Comment by The-Compiler** [comment]
Thanks! Merged to `master` and cherry-picked to `v0.11.x`.

**Pull request merged**
