### PR TITLE
Move getting argv from main function

### PR DESCRIPTION
**Pull request by heckad**
It is needed if I want to open browser from my script with my args.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4615)

### CODE REVIEW

**Comment by jgkamat** [comment]
On February 26, 2019 8:08:27 PM CST, Andrey <notifications@github.com> wrote:
>It is needed if I want to open browser from my script with my args.

Hmm, my script passes arguments through just fine.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by heckad** [comment]
Through what? You do not have argv value in main. Linter does not allow to modify `sys.argv`, because needed add argv as arg in main function.

**Comment by jgkamat** [comment]
Andrey writes:

> Through what? You do not have argv value in main. Linter does not allow to modify sys.argv, because needed add argv as arg in main function.

There is an example script in the install docs.

https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#creating-a-wrapper-script


That function is not a public api, the name and arguments can change at any
time. You probably shouldn't depend on it.

**Comment by heckad** [comment]
Why main function doesn't public? It is the entry point of program. 

My target to call it from my python script (non bash like in https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#creating-a-wrapper-script) with prepared argv. For making it I should modify `sys.argv` but linter doesn’t allow such code. How to pass arguments without touching `sys.argv`.

**Comment by jgkamat** [comment]
Andrey writes:

> My target to call it from my python script (non bash like in https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#creating-a-wrapper-script) with prepared argv. For making it I should modify `sys.argv` but linter doesn’t allow such code. How to pass arguments without touching `sys.argv`.

Sure, here's a python version, just replace qutebrowser with where your
qutebrowser binary would be (or not):

#!/usr/bin/python3

import subprocess
import sys

subprocess.run(["qutebrowser"] + sys.argv[1:])


> Why main function doesn't public? It is the entry point of program.

I still don't know what you're trying to do, so I'll assume you're doing
something like:

import qutebrowser.qutebrowser
qutebrowser.qutebrowser.main(<your arguments>)

qutebrowser is not a library, it's a program (with a few exceptions, like the
config api, and the plugin api, if that's fixed in the future). The entry
point is not standardized because there's no reason for it to be (and it gives
us the flexibility to rename and change things later on). For example, if we
wanted to change our namespace to 'org.qutebrowser' instead of
'qutebrowser.qutebrowser', we could do that if we wanted, and that would break
your script.

Also - if somoene (like you) is incorrectly using this as an api and
hot-patching 'sys.argv' to get it working, this change itself will break their
setup, as sys.argv is only evaluated on import time now.

**Comment by The-Compiler** [comment]
I agree with what @jgkamat said - even more so if it involves you silencing our linter instead of yours.

The only supported ways to launch qutebrowser is as a subprocess (as jgkamat demonstrated), or by modifying `sys.argv` and using `pkg_resources` like `/usr/bin/qutebrowser` does:

```python
from pkg_resources import load_entry_point
load_entry_point('qutebrowser', 'gui_scripts', 'qutebrowser')()
```

**Pull request closed without merging**
