### PR TITLE
Fix prompt crash when windows are closed

### LINKED ISSUE #3378: RegistryUnavailableError when closing download prompt after closing window
Crash report from some while ago from @edrex, on v1.0.2: https://crashes.qutebrowser.org/view/d658759c

```
13:11:06 DEBUG    modes      tabbedbrowser:on_mode_left:618 Left status-input mode, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://[...].slack.com/messages/[...]/convo/[...]/'>
13:11:06 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.prompt (reason aborted) as we're in mode KeyMode.normal
[...]
13:11:06 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 200, in _get_window_registry
    return win.registry
AttributeError: 'NoneType' object has no attribute 'registry'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/mainwindow/prompt.py", line 335, in <lambda>
    maybe=True))
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 109, in leave
    instance(win_id).leave(mode, reason, maybe=maybe)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 99, in instance
    return objreg.get('mode-manager', scope='window', window=win_id)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 227, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 216, in _get_registry
    return _get_window_registry(window)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 202, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

---

> This is repeatable for me on linux/i3. I'm running in "tabs are windows" mode.
>  
>  - Click "print" button for PDF attachment in GMail
>  - It opens in a new window, and "Save to" dialog pops up
>  - Close that window
>  - Hit "escape" to exit the "save to" dialog which is displayed in the original gmail window as well
>  - Crash
>  
> I wonder if it's repeatable for a normal "save as" dialog when closing the originating window and then exiting the dialog from another. Also if it's related to "tabs are windows"

### PR DESCRIPTION
**Pull request by jgkamat**
Fixes #3378, continuation of #4608 (see there for discussion).

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4697)

### CODE REVIEW

**Comment by jgkamat** [comment]
Not sure if disconnecting the signals is cleaner than catching the exception or not, if not, I'll revert it.

Just removing this won't work because we manually call abort in a bunch of places (and I don't think a global bridge will work here).

**Comment by user202729** [comment]
I think it's safer to catch the error because Python is garbage collected, and there's no guarantee on when the object (`PromptContainer`) will be destroyed, and it would be a problem if it's destroyed after the window.

(which also cause the bug mentioned [here](https://github.com/qutebrowser/qutebrowser/issues/1249#issuecomment-446266469), although in this case `isdeleted` is safe)

**Comment by The-Compiler** [comment]
FWIW I've also seen really funny PyQt/Qt behavior (segfaults and such) when connecting to `destroyed` signals - I'm not sure if those have been fixed in the meantime (it's been a while), but I'd still like to avoid doing that. At best, it's still quite indeterministic.

**Comment by jgkamat** [comment]
Hmm, I'll just restore the old catch method from the old PR then, I can't think of anything better.

**Comment by The-Compiler** [comment]
Thanks @pcapriotti and @jgkamat!

**Pull request merged**
