### PR TITLE
Fix #3396

### LINKED ISSUE #3396: "Suspended" tabs in history
When `session.lazy_restore` is `true`, "qute://back/*" urls are included in the history. As re-opening such URLs is pointless, perhaps they should not be saved in the history.

### PR DESCRIPTION
**Pull request by seebye**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3403)

### CODE REVIEW

**Comment by mschilli87** [comment]
@seebye: Was this supposed to be closed? Is the fix for #3396 already merged?

**Comment by seebye** [comment]
I closed it as it contained also commits from another pull request and I don't know how to create a new branch based on the master branch of qutebrowser/qutebrowser

**Comment by The-Compiler** [comment]
In the future, I suggest creating a new branch for every pull request to avoid things like this.

Assuming you have your repo set as `origin` in `git remote -v`, and haven't added my repo yet, you should be able to do something like this:

```
# Add my repo
$ git remote add upstream git@github.com:qutebrowser/qutebrowser.git 
# Make sure you're up-to-date
$ git fetch upstream
# Create another `upstream-master` branch to work with (in the future, your `master` branch should be that, with all changes in a branch)
# Create a feature branch for your fix
$ git checkout -b fix-3396 upstream/master
# Get the commit over to that branch
$ git cherry-pick a911094846e438596e5a0656cf6f8f515eb3fd21
# Push your new branch (might need to use `--set-upstream` stuff if git tells you to)
$ git push origin
```

I didn't test this FWIW, but it should work. Then you can create a PR for that new branch.

**Comment by seebye** [comment]
Thank you

**Pull request closed without merging**
