### PR TITLE
Add: new mode for Auto Search

### PR DESCRIPTION
**Pull request by jyscao**
* when `url.auto_search = 'no-url-scheme'`, URLs
  must contain schemes to be considered valid
* implements feature requested in #5038 

-------------------------
I'll add the tests in if the code looks good to you guys.

### CODE REVIEW

**Comment by The-Compiler** [comment]
@danielnelson can you give this a try?

**Comment by jyscao** [comment]
@The-Compiler, hoping you can provide some advice on adding the tests for this new feature/option. The `test_is_url` test function located in `tests/unit/utils/test_urlutils.py` is parametrized with boolean values for `is_url`, `is_url_no_autosearch` and `uses_dns`, and a string value for the actual `url` itself; if we do add in this additional 4th option to `url.auto_search`, how should I add it to this particular test?

Naively, I'd could just add it as a 4th boolean parameter to the ~50 test cases that currently exist already, in addition to whatever new cases I might be adding, but that seems really ugly to me. This also implies that if in the future more options were to be added (whether this is likely or not I cannot say), then this same kludgy change would have to be undertaken again.

I entertained the idea of adding an additional `@pytest.mark.parameterize` solely for this option, but that doesn't seem like a good idea either, since these boolean values are not independent, so they cannot just be multiplied together like a cartesian product.

What do you think Florian (or anyone else for that matter)? Any good ideas/suggestions?

**Comment by The-Compiler** [comment]
@jyscao One possibility would be to add a new class using [attrs](http://www.attrs.org/en/stable/) for the test cases, that makes it possible to set default values for the arguments.

See e.g. `VersionParams` and `test_version_output` in `tests/unit/utils/test_version.py` for an example.

**Comment by The-Compiler** [comment]
@jyscao Gentle ping - are you planning to add/change the tests accordingly, or should I take over?

**Comment by jyscao** [comment]
@The-Compiler Thanks for the remainder, this totally escaped my mind admittedly. I shall work on this in the next couple days :)

**Comment by danielnelson** [comment]
Sorry, I missed this when it was first opened.  I just installed the patch and so far I love it, its working just like I imagined.  I'll continue testing it out and update with any issues I run into.  Thanks so much!

**Comment by The-Compiler** [comment]
@mschilli87 can you do your thing? :wink:

**Comment by The-Compiler** [comment]
Merged - thanks @jyscao for the PR, @danielnelson for testing and @mschilli87 for the configdata review! :tada:

**Pull request merged**
