### PR TITLE
Fix links not being added to history

### LINKED ISSUE #2835: Links not added to history on this site
https://goswagger.io/

Try following a link on the left side, the page it directs you to is not added to the history. It is missing from `:history` as well as completion. If you refresh a page, it does get added. I'm guessing the website is doing something weird (scrolling is mostly broken as well) but I'm wondering if we can do anything here.

### PR DESCRIPTION
**Pull request by Enzime**
Closes #2835.

This adds a flag to store whether the current page has been added to history yet, and if not when either `loadFinished` or `loadProgress` with `perc=100` then the page will be added to history.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3260)

### CODE REVIEW

**Comment by The-Compiler** [comment]
@Enzime Any update on this?

**Comment by Enzime** [comment]
I haven't had too much time to look into this, but the main issue with this PR is that it adds links to history multiple times, and that's why the tests break because they expect it to be added exactly once sequentially.

**Comment by The-Compiler** [comment]
Do you still plan to fix this up, or should we close this in the meantime?

**Comment by Enzime** [comment]
You can close this for now, someone else can work on this if they want.

**Pull request closed without merging**
