### PR TITLE
Block sub-domains with host blocker

### LINKED ISSUE #6365: Block sub-domains with host blocker?
See the discussion here: #6340 (cc @4nd3r)

### PR DESCRIPTION
**Pull request by 4nd3r**
closes #6365, discussion in #6340 

`... import _widened_hostnames` doesn't feel right. make `_widened_hostnames` public, duplicate code or leave as-is?

haven't look into tests yet.

### CODE REVIEW

**Comment by The-Compiler** [comment]
If it's now used in multiple places, `_widened_hosts` should be public, but also not in `configutils`. Unfortunately, moving it elsewhere will potentially lead to circular imports... See 608a1ead410607c6fd7394dcf75d55495448b4ea.

However, I tried moving it back, and it seems to work fine - so that's what I'd recommend doing:

```diff

diff --git a/qutebrowser/config/configutils.py b/qutebrowser/config/configutils.py
index d619eb21f..28d4a3fe3 100644
--- a/qutebrowser/config/configutils.py
+++ b/qutebrowser/config/configutils.py
@@ -32,22 +32,13 @@
 from PyQt5.QtGui import QFontDatabase
 from PyQt5.QtWidgets import QApplication
 
-from qutebrowser.utils import utils, urlmatch, usertypes, qtutils
+from qutebrowser.utils import utils, urlmatch, urlutils, usertypes, qtutils
 from qutebrowser.config import configexc
 
 if TYPE_CHECKING:
     from qutebrowser.config import configdata
 
 
-def _widened_hostnames(hostname: str) -> Iterable[str]:
-    """A generator for widening string hostnames.
-
-    Ex: a.c.foo -> [a.c.foo, c.foo, foo]"""
-    while hostname:
-        yield hostname
-        hostname = hostname.partition(".")[-1]
-
-
 class ScopedValue:
 
     """A configuration value which is valid for a UrlPattern.
@@ -231,7 +222,7 @@ def get_for_url(self, url: QUrl = None, *, fallback: bool = True) -> Any:
         candidates: List[ScopedValue] = []
         # Urls trailing with '.' are equivalent to non-trailing types.
         # urlutils strips them, so in order to match we will need to as well.
-        widened_hosts = _widened_hostnames(url.host().rstrip('.'))
+        widened_hosts = urlutils.widened_hostnames(url.host().rstrip('.'))
         # We must check the 'None' key as well, in case any patterns that
         # did not have a domain match.
         for host in itertools.chain(widened_hosts, [None]):
diff --git a/qutebrowser/utils/urlutils.py b/qutebrowser/utils/urlutils.py
index 045981680..002f10411 100644
--- a/qutebrowser/utils/urlutils.py
+++ b/qutebrowser/utils/urlutils.py
@@ -26,7 +26,7 @@
 import posixpath
 import urllib.parse
 import mimetypes
-from typing import Optional, Tuple, Union
+from typing import Optional, Tuple, Union, Iterable
 
 from PyQt5.QtCore import QUrl
 from PyQt5.QtNetwork import QHostInfo, QHostAddress, QNetworkProxy
@@ -619,3 +619,12 @@ def parse_javascript_url(url: QUrl) -> str:
         raise Error("Resulted in empty JavaScript code")
 
     return code
+
+
+def widened_hostnames(hostname: str) -> Iterable[str]:
+    """A generator for widening string hostnames.
+
+    Ex: a.c.foo -> [a.c.foo, c.foo, foo]"""
+    while hostname:
+        yield hostname
+        hostname = hostname.partition(".")[-1]
diff --git a/tests/unit/config/test_configutils.py b/tests/unit/config/test_configutils.py
index 4d3082a92..725a38c28 100644
--- a/tests/unit/config/test_configutils.py
+++ b/tests/unit/config/test_configutils.py
@@ -300,29 +300,6 @@ def test_domain_lookup_sparse_benchmark(url, values, benchmark):
     benchmark(lambda: values.get_for_url(url))
 
 
-class TestWiden:
-
-    @pytest.mark.parametrize('hostname, expected', [
-        ('a.b.c', ['a.b.c', 'b.c', 'c']),
-        ('foobarbaz', ['foobarbaz']),
-        ('', []),
-        ('.c', ['.c', 'c']),
-        ('c.', ['c.']),
-        ('.c.', ['.c.', 'c.']),
-        (None, []),
-    ])
-    def test_widen_hostnames(self, hostname, expected):
-        assert list(configutils._widened_hostnames(hostname)) == expected
-
-    @pytest.mark.parametrize('hostname', [
-        'test.qutebrowser.org',
-        'a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.z.y.z',
-        'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq.c',
-    ])
-    def test_bench_widen_hostnames(self, hostname, benchmark):
-        benchmark(lambda: list(configutils._widened_hostnames(hostname)))
-
-
 class TestFontFamilies:
 
     @pytest.mark.parametrize('family_str, expected', [
diff --git a/tests/unit/utils/test_urlutils.py b/tests/unit/utils/test_urlutils.py
index a5599c6c9..97ff268ca 100644
--- a/tests/unit/utils/test_urlutils.py
+++ b/tests/unit/utils/test_urlutils.py
@@ -778,3 +778,26 @@ def test_hypothesis(self, source):
             pass
         else:
             assert parsed == source
+
+
+class TestWiden:
+
+    @pytest.mark.parametrize('hostname, expected', [
+        ('a.b.c', ['a.b.c', 'b.c', 'c']),
+        ('foobarbaz', ['foobarbaz']),
+        ('', []),
+        ('.c', ['.c', 'c']),
+        ('c.', ['c.']),
+        ('.c.', ['.c.', 'c.']),
+        (None, []),
+    ])
+    def test_widen_hostnames(self, hostname, expected):
+        assert list(urlutils.widened_hostnames(hostname)) == expected
+
+    @pytest.mark.parametrize('hostname', [
+        'test.qutebrowser.org',
+        'a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.z.y.z',
+        'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq.c',
+    ])
+    def test_bench_widen_hostnames(self, hostname, benchmark):
+        benchmark(lambda: list(urlutils.widened_hostnames(hostname)))

```

**Comment by 4nd3r** [comment]
I'm trying to understand if someone might want to have previous behvior. I'm thinking that people, who come from UBO and Brave, expect this kind of behavior, but existing QB users might not. Maybe they are not just aware of this "restriction"?

Blocking every subdomain of blocked host makes default hosts blocking list (Steven Black) much more effective, because it contains lots of entries where only main domain is defined, but ads and trackers are served from subdomains, which change from time to time.

For example, Steven Black's list (or rather pgl.yoyo.org, because Steven's list is compilation) only defines main domain `realsrv.com`, but all the nasty stuff is served from `a.`, `ads.` and `syndication.` subdomains.

**Comment by 4nd3r** [comment]
some more data. recently I scanned all third party requests made by web sites in `.ee` zone. that gave me 34415 unique hosts.

and when I compare old and proposed hostblocking behavior, I get following:
```
$ wc -l ee3phosts.list.uniq
34415 ee3phosts.list.uniq
$ ./adblock_simulator.py -s example.com -d ee3phosts.list.uniq -h sbhosts -b | wc -l
2080
$ ./ee3phosts.list.blocked_by_hostblock.py | wc -l
1177
```

of course, you can't judge or evaluate the effectiveness of hosts list by number of blocked hosts, so add some salt to this data.

**Comment by The-Compiler** [comment]
Thanks for the data, that definitely is convincing! I guess it's okay to have it by default, I struggle to think of a case where `example.org` should be blocked but `*.example.org` is legit.

Please ignore the GitHub code scanning comments - I've played around with that a bit yesterday, but tuned it down again now. This mostly looks good to me otherwise, but I want to take a closer look at a couple of things. Will get back to it soon-ish, though I'm busy with other stuff in the next couple of days.

Is there anything left to be done from your point of view?

**Comment by 4nd3r** [comment]
> I struggle to think of a case where `example.org` should be blocked but `*.example.org` is legit.

one can use whitelisting then? sounds like rare edge case to me, which definetly can happen.

> Is there anything left to be done from your point of view?

not really. I'm dogfooding it currently and I haven't experienced any issues, yet and hopefully stays like this.

**Comment by The-Compiler** [comment]
Sorry for the radio silence here, I've had a very stressful time in April. I plan to get back to this either this or next week.

**Comment by 4nd3r** [comment]
No worries, take your time - mental health first, then everything else.

**Comment by The-Compiler** [comment]
Thanks for your PR and your patience! :+1: Merged with a small cleanup in 4899d1d10f612fa9f0477cd7e7d1f30db746fc89.

**Pull request merged**
