### PR TITLE
update apparmor profile

### LINKED ISSUE #5729: The default apparmor profile causes a segfault
**Version info**:

qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1 (compiled 5.15.0)

(Void Linux)

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When using the apparmor profile in enforce mode, qutebrowser segfaults.

**How to reproduce**

Install the default qutebrowser apparmor profile, enable apparmor and run:

```
%: sudo aa-enforce qutebrowser
Setting /usr/bin/qutebrowser to enforce mode.
Warning: profile qutebrowser represents multiple programs
%: qutebrowser
12:27:16 WARNING: EGL not available
[0918/122717.093837:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources.pak
Some features may not be available.
[0918/122717.093892:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources_100p.pak
Some features may not be available.
[0918/122717.093920:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources_200p.pak
Some features may not be available.
[0918/122717.095185:ERROR:resource_bundle_qt.cpp(123)] failed to load locale.pak
LaunchProcess: failed to execvp:
/usr/lib/qt5/libexec/QtWebEngineProcess
[12650:12662:0918/122717.109661:ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches
[12650:12650:0918/122717.111713:ERROR:extension_system_qt.cpp(122)] Failed to parse extension manifest.
zsh: segmentation fault  qutebrowser
```

After some tweaking of the profile adding these rules:
```
/usr/share/qt5/resources/* r,
/dev/shm/.org.chromium.Chromium.* rw,
/usr/lib/qt5/libexec/QtWebEngineProcess ux,
/etc/mime.types r,
/proc/sys/fs/inotify/max_user_watches r,
```

it still fails, but in a different place:
```
%: qutebrowser
12:10:59 WARNING: EGL not available
[0918/121100.213215:ERROR:resource_bundle_qt.cpp(123)] failed to load locale.pak
LaunchProcess: failed to execvp:
/usr/lib/qt5/libexec/QtWebEngineProcess
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:02 ERROR: Renderer process did not start
12:11:02 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
```

### PR DESCRIPTION
**Pull request by GbGp**
Simple apparmor profile for qutebrowser. Could probably be improved taking inspiration from the [chromium profile](https://gitlab.com/apparmor/apparmor-profiles/blob/master/ubuntu/18.04/usr.bin.chromium-browser) found in the apparmor repository, but this one is a good start and works fine for me.
Closes #5729

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thank you! :+1:

**Comment by The-Compiler** [comment]
Thank you! :+1:

**Comment by PaperMountainStudio** [comment]
Hi, thanks a lot for your work. I adapted your profile for Void Linux which uses /usr/share/qt5 instead of /usr/share/qt with the following patch:
```
From d76f66dee17043b4b37f4b0377bab015b24183d9 Mon Sep 17 00:00:00 2001
From: Paper <paper@tilde.institute>
Date: Wed, 21 Oct 2020 00:00:00 +0200
Subject: [PATCH] update apparmor profile

---
 misc/apparmor/usr.bin.qutebrowser | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

diff --git a/misc/apparmor/usr.bin.qutebrowser b/misc/apparmor/usr.bin.qutebrowser
index 3d27be697..d7c26bdaf 100644
--- a/misc/apparmor/usr.bin.qutebrowser
+++ b/misc/apparmor/usr.bin.qutebrowser
@@ -33,12 +33,12 @@ profile qutebrowser /usr/{local/,}bin/qutebrowser {
     /usr/bin/ldconfig ix,
     /usr/bin/uname ix,
     /usr/bin/qutebrowser rix,
-    /usr/lib/qt/libexec/QtWebEngineProcess mrix,
+    /usr/lib/qt{,5}/libexec/QtWebEngineProcess mrix,
     /usr/share/pdf.js/** r,
-    /usr/share/qt/translations/qtwebengine_locales/* r,
-    /usr/share/qt/qtwebengine_dictionaries r,
-    /usr/share/qt/qtwebengine_dictionaries/* r,
-    /usr/share/qt/resources/* r,
+    /usr/share/qt{,5}/translations/qtwebengine_locales/* r,
+    /usr/share/qt{,5}/qtwebengine_dictionaries r,
+    /usr/share/qt{,5}/qtwebengine_dictionaries/* r,
+    /usr/share/qt{,5}/resources/* r,
 
     owner @{HOME}/ r,
     owner /dev/shm/.org.chromium* rw,
-- 
2.29.0
```
However, when I start qutebrowser and open a webpage (for example github.com), I get this error in the console:
```
%: qutebrowser
00:23:23 WARNING: EGL not available
[1275:1288:1021/002324.541199:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
00:23:33 ERROR: Renderer process crashed
00:23:33 WARNING: Wayland does not support QWindow::requestActivate()
```

And I see this in the browser:
```
Unable to load page
Error while opening http://github.com/
Renderer process crashed
```

Since you created the profile, I think you may know something more about it. Here is the log:
```
2020-10-20T22:23:16.82840 kern.warn: [218780.237327] kauditd_printk_skb: 216 callbacks suppressed
2020-10-20T22:23:16.82892 kern.notice: [218780.237328] audit: type=1400 audit(1603232596.826:1054161): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="qutebrowser" pid=873 comm="apparmor_parser"
2020-10-20T22:23:22.36390 kern.notice: [218785.773225] audit: type=1400 audit(1603232602.362:1054162): apparmor="DENIED" operation="open" profile="qutebrowser" name="/usr/share/icu/67.1/icudt67l.dat" pid=1249 comm="qutebrowser" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2020-10-20T22:23:23.02124 kern.notice: [218786.430267] audit: type=1400 audit(1603232603.019:1054163): apparmor="DENIED" operation="open" profile="qutebrowser" name="/usr/share/terminfo/x/xterm-16color" pid=1249 comm="qutebrowser" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2020-10-20T22:23:23.02130 kern.notice: [218786.430307] audit: type=1400 audit(1603232603.019:1054164): apparmor="DENIED" operation="open" profile="qutebrowser" name="/home/paper/.inputrc" pid=1249 comm="qutebrowser" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
2020-10-20T22:23:23.02132 kern.notice: [218786.430309] audit: type=1400 audit(1603232603.019:1054165): apparmor="DENIED" operation="open" profile="qutebrowser" name="/etc/inputrc" pid=1249 comm="qutebrowser" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2020-10-20T22:23:23.18825 kern.notice: [218786.596976] audit: type=1400 audit(1603232603.186:1054166): apparmor="DENIED" operation="mknod" profile="qutebrowser" name="/usr/share/fonts/cantarell/.uuid.TMP-tTrc6B" pid=1249 comm="qutebrowser" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
2020-10-20T22:23:23.19023 kern.notice: [218786.598692] audit: type=1400 audit(1603232603.188:1054167): apparmor="DENIED" operation="mknod" profile="qutebrowser" name="/usr/share/fonts/X11/cyrillic/.uuid.TMP-vTiAgC" pid=1249 comm="qutebrowser" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
2020-10-20T22:23:23.19027 kern.notice: [218786.598876] audit: type=1400 audit(1603232603.188:1054168): apparmor="DENIED" operation="mknod" profile="qutebrowser" name="/usr/share/fonts/X11/util/.uuid.TMP-ZFjBnF" pid=1249 comm="qutebrowser" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
2020-10-20T22:23:23.19029 kern.notice: [218786.599132] audit: type=1400 audit(1603232603.188:1054169): apparmor="DENIED" operation="mknod" profile="qutebrowser" name="/home/paper/.fonts/fonts/D2Coding/.uuid.TMP-UzF01E" pid=1249 comm="qutebrowser" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
2020-10-20T22:23:23.19033 kern.notice: [218786.599588] audit: type=1400 audit(1603232603.188:1054170): apparmor="DENIED" operation="open" profile="qutebrowser" name="/home/paper/.cache/fontconfig/086774135a6ab97f3b443fbf8838ad05-le64.cache-7" pid=1249 comm="qutebrowser" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
2020-10-20T22:23:23.19123 kern.notice: [218786.599842] audit: type=1400 audit(1603232603.189:1054171): apparmor="DENIED" operation="chmod" profile="qutebrowser" name="/var/cache/fontconfig/" pid=1249 comm="qutebrowser" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0
2020-10-20T22:23:33.23150 kern.warn: [218796.640702] show_signal: 30 callbacks suppressed
2020-10-20T22:23:33.23156 kern.info: [218796.640704] traps: QtWebEngineProc[1298] trap int3 ip:7f74c6b9ad51 sp:7ffc29f066b0 error:0 in libQt5WebEngineCore.so.5.15.1[7f74c3993000+5e5a000]
```

**Comment by GbGp** [comment]
It's denying access to a some stuff that should be allowed from `#include <abstractions/fonts>`. What version of the userspace tools are you using?
As reference check the last released version of abstractions/fonts:
https://gitlab.com/apparmor/apparmor/-/blob/apparmor-3.0/profiles/apparmor.d/abstractions/fonts

**Comment by PaperMountainStudio** [comment]
it works with apparmor 3.0, thanks

**Pull request merged**
