### PR TITLE
Merge master into new-config

### PR DESCRIPTION
**Pull request by rcorre**
See 90c49b3fe7e62183b29b6525b1552910e8087548 for the circular import issue I mentioned. I'm not actually sure why moving `bind` works, but it does.

Also, I had to resolve a few conflicts outside completion, but hopefully I got them right. I'm assuming that's the case if the tests pass :grin:

There seems to be some sort of problem with vulture

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2914)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Hmm, reviewing this is going to be fun 😆 

From a quick look at Travis:

- [Circular import on Python 3.4](https://travis-ci.org/qutebrowser/qutebrowser/jobs/266648852) - as I said earlier it's okay to ignore this, but it'd still make my life easier if I could drop support for Python 3.4 after taking care of this, so if you find a quick&dirty fix, that'd be appreciated.
- [Renderer crash errors](https://travis-ci.org/qutebrowser/qutebrowser/jobs/266648855) now seem to fail some tests which worked before? Those are all with Qt 5.9 which should show an error page instead of a message.
- [Double-registration of `proxy-factory`](https://travis-ci.org/qutebrowser/qutebrowser/jobs/266648856)
- [pylint complains](https://travis-ci.org/qutebrowser/qutebrowser/jobs/266648861) because the [config checker](https://github.com/qutebrowser/qutebrowser/blob/new-config/scripts/dev/pylint_checkers/qute_pylint/config.py) I wrote is a bit of a hack (but still was very useful!). Probably fine to silence it.
- docs/vulture have the same circular import than Python 3.4 has.

**Comment by The-Compiler** [comment]
Ah, looks like `git show` shows merge commits much nicer than GitHub does. Interesting commits from what I can see:

- 71b71dbc58092b6068a3f5ee4b1c287193ad348d the original merge
- 5ea420b49b58aee4a42f7cd79fe9b14f1f87c159 first fixes
- 0286e9ddf28b9b8d8bcbce188865d3621bc2fd5c fixing completion tests
- 90c49b3fe7e62183b29b6525b1552910e8087548 moving bind completion
- b5a6583559b1e69ac0aa481ca79e05814f5d15f4 fixing linters
- 722137ab2967f7bafcfa9ab41a239a0db9345b9f fixing some end2end tests
- 111846a909c442fed4aecc715cc91d72a8288ab6 another merge from master

@rcorre can you please take a look at the things in #2779 as well?

**Comment by rcorre** [comment]
> Double-registration of proxy-factory

Probably a bad merge [here](https://github.com/qutebrowser/qutebrowser/commit/71b71dbc58092b6068a3f5ee4b1c287193ad348d#diff-ec456d450dcb3f97959274d26a152004L403) and [here](https://github.com/qutebrowser/qutebrowser/commit/71b71dbc58092b6068a3f5ee4b1c287193ad348d#diff-6ffaa354811114a1994cc790c991dc93R39). Can you provide any context on the changes in `proxy.init` and `JSBridge` from master?

**Comment by The-Compiler** [comment]
My bad for saying `quteurls.feature` in #2779 - that should be the (already existing) `qutescheme.feature`.

**Comment by The-Compiler** [comment]
@rcorre Do you have some WIP work for this you haven't pushed yet? If not, I'd like to try finishing this tomorrow, as I'll have some hours of time while in a train to Budapest :wink:

Also, would you mind if I copy-pasted some conflict resolutions/code without proper attribution to you in the git commits? Since this is pretty much impossible to review as a diff, I'm kind of considering just re-doing the merge and copying from you for the completion related stuff, and then reviewing the diff between the two merges.

**Comment by rcorre** [comment]
@The-Compiler that all sounds fine, I have nothing unpushed. Thanks!

**Comment by The-Compiler** [comment]
Looking at the remaining issues:

- `test_setting_option_completion` [fails](https://travis-ci.org/qutebrowser/qutebrowser/jobs/271827568#L942), probably due to a similar issue to what you fixed in fc022167541aae2f1a9227cc054cda7f4ad25eac
- `eslint` [fails](https://travis-ci.org/qutebrowser/qutebrowser/jobs/271827589#L706) due to a version upgrade, which was fixed in 19385208788d938630938bbdcbb780becbeed4b9, so feel free to ignore that
- Various environments with Qt 5.9 [fail](https://travis-ci.org/qutebrowser/qutebrowser/jobs/271827579#L650) due to a bad merge here in `tabbedbrowser.py:_on_renderer_process_terminated`:

```
            error_page = jinja.render(
                'error.html', title="Error loading {}".format(url_string),
<<<<<<< HEAD
                url=url_string, error=msg)
            QTimer.singleShot(0, lambda: tab.set_html(error_page))
            log.webview.error(msg)
=======
                url=url_string, error=msg, icon='')
            QTimer.singleShot(100, lambda: show_error_page(error_page))
>>>>>>> master
```

5ecda25fdb0d0231c40b5153a0c67eab3474303c removed the `log.webview.error` (or rather moved it to `show_error_page`) in `master`, but when merging you re-added it.

**Comment by rcorre** [comment]
This should be ready, but I'm not quite sure why py34-cov is [failing](https://travis-ci.org/qutebrowser/qutebrowser/jobs/272023925) as I don't see any actual failure message

**Comment by The-Compiler** [comment]
It looks like that's just because the old Qt used there likes to segfault on exit. We used to have a workaround for this, dropped it when it seemed more stable, and for some reason it came back - but I didn't worry about it as we're going to drop the old Qt soon anyways.

I'm more worried about the [issues on AppVeyor](https://ci.appveyor.com/project/qutebrowser/qutebrowser/build/new-config-1675/job/egvbcdjia6m7nnmt).  The `test_progress_affecting_statusbar_height` one also happens on the `new-config` branch - I don't know what it is, but it isn't your fault :wink:. I'll try to leave a review on Reviewable for the remaining issues.

**Comment by The-Compiler** [comment]
Reviewed 136 of 136 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pytest.ini, line 50 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQk_iE9Co_LLJutt5H:-KtQk_iE9Co_LLJutt5I:bmpkuf) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/pytest.ini#L50)):*
> ```INI
>     ^QGeoclueMaster error creating GeoclueMasterClient\.
>     ^Geoclue error: Process org\.freedesktop\.Geoclue\.Master exited with status 127
>     ^Failed to create Geoclue client interface. Geoclue error: org\.freedesktop\.DBus\.Error\.Disconnected
> ```

This is now in here twice, here and two lines below.

---

*[doc/help/settings.asciidoc, line 1078 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQkRmkxGC0CeRBnwRz:-KtQkRmkxGC0CeRBnwS-:b5mjsx5) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/doc/help/settings.asciidoc#L1078)):*
> ```AsciiDoc
> =======
> Valid values:
> >>>>>>> upstream/master
> ```

You should probably re-run `src2asciidoc.py`.

---

*[qutebrowser/completion/models/configmodel.py, line 31 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQl2A20TWcUJSaOG3V:-KtQl2A20TWcUJSaOG3W:b-aryzt4) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L31)):*
> ```Python
>     model = completionmodel.CompletionModel(column_widths=(20, 70, 10))
>     options = ((x.name, x.description, info.config.get_str(x.name))
>                for x in configdata.DATA.values())
> ```

nitpick: Please call this `opt` instead of `x` so it's a bit more readable (as it's an `Option` object).

---

*[qutebrowser/completion/models/configmodel.py, line 47 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQlB2gUkkbvvctqnsj:-KtQlB2hKuuZpuNLgCJJ:b-qgxf3d) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L47)):*
> ```Python
> 
>     try:
>         current = str(info.config.get(optname) or '""')
> ```

Shouldn't this use `info.config.get_str` instead?

---

*[qutebrowser/completion/models/configmodel.py, line 51 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQljZOs7PUlPYuhTih:-KtQljZOs7PUlPYuhTii:b-xlxn69) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L51)):*
> ```Python
>         return None
> 
>     opt = configdata.DATA[optname]
> ```

`config.instance.get_opt(optname)` would be the proper API to use here - it doesn't really matter as it only re-raises `KeyError` as `NoOptionError` and we know the option exists, but I'd prefer using it anyways.

---

*[qutebrowser/completion/models/configmodel.py, line 52 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQlt0OoWEI678plpDt:-KtQlt0P5kePcVXsylI6:bwpzdr8) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L52)):*
> ```Python
> 
>     opt = configdata.DATA[optname]
>     default = str(opt.default or '""')
> ```

`opt.typ.to_str(opt.default)`?

---

*[qutebrowser/completion/models/configmodel.py, line 71 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQmL1ai3yS8qCSdnsw:-KtQmL1ai3yS8qCSdnsx:bqfljgy) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L71)):*
> ```Python
>     """
>     model = completionmodel.CompletionModel(column_widths=(20, 60, 20))
>     cmd_text = info.keyconf.get_bindings_for('normal').get(key)
> ```

There's a new `def get_command(self, key, mode):` now.

---

*[qutebrowser/mainwindow/messageview.py, line 72 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQnBmmL9rq2rNwp1St:-KtQnBmmL9rq2rNwp1Su:b4tlze0) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/mainwindow/messageview.py#L72)):*
> ```Python
> 
> 
> class MessageView(QWidget):
> ```

I'm not confident yet whether the changes here are correct, i.e. whether they still contain the changes from https://github.com/qutebrowser/qutebrowser/pull/2808/files

I need to take a closer look, but I'm running out of time for today :wink:

---

*[qutebrowser/mainwindow/tabbedbrowser.py, line 724 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQneNL6_Rr0HG95T2f:-KtQneNMYGdxaa9u8C0R:b-r4ohma) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/mainwindow/tabbedbrowser.py#L724)):*
> ```Python
>             error_page = jinja.render(
>                 'error.html', title="Error loading {}".format(url_string),
>                 url=url_string, error=msg, icon='')
> ```

You re-added the `icon=''` here which was removed in 3a6bcb3dd0873776a5002c6bd55754634ae94e5c - I think that's incorrect.

---

*[tests/end2end/features/downloads.feature, line 597 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQkllJG2S7neBbKLWh:-KtQkllJG2S7neBbKLWi:b-nmloum) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/tests/end2end/features/downloads.feature#L597)):*
> ```Gherkin
> 
>     Scenario: Downloading to unwritable destination
>         When I set downloads.location.prompt to false
> ```

You removed a "When the unwritable dir is unwritable" from 3b53ec1cb6c136ffb12e46f3b532e546cb0bd421 here, causing a failure on AppVeyor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914)*

**Comment by The-Compiler** [comment]
Some more things I noticed:

- [ ] The `FIXME:conf` in `tests/unit/completion/test_models.py` can probably go now.
- [ ] Somehow I don't see `utilcmds.py` on reviewable, but there was a conflict in `debug_cache_stats` and I think you accidentally removed the output for the history which was added in 9b0395db087f320e150626df7e182c66f9a47c86 - it should probably look like this:

```python
@cmdutils.register(debug=True)
def debug_cache_stats():
    """Print LRU cache stats."""
    prefix_info = configdata.is_valid_prefix.cache_info()
    # pylint: disable=protected-access
    render_stylesheet_info = config._render_stylesheet.cache_info()
    # pylint: enable=protected-access
    try:
        from PyQt5.QtWebKit import QWebHistoryInterface
        interface = QWebHistoryInterface.defaultInterface()
        history_info = interface.historyContains.cache_info()
    except ImportError:
        history_info = None

    log.misc.debug('is_valid_prefix: {}'.format(prefix_info))
    log.misc.debug('_render_stylesheet: {}'.format(render_stylesheet_info))
    log.misc.debug('history: {}'.format(history_info))
```

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-:-KtQpZqaqJ9IS0xckfLI:b4mm9g2)*

**Comment by rcorre** [comment]
Review status: 134 of 137 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pytest.ini, line 50 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQk_iE9Co_LLJutt5H:-KtR6ffJvM3_b_N0IZ0-:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/pytest.ini#L50)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

This is now in here twice, here and two lines below.
</blockquote></details>

Done.

---

*[doc/help/settings.asciidoc, line 1078 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQkRmkxGC0CeRBnwRz:-KtRN908hyuRNB0YgI_a:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/doc/help/settings.asciidoc#L1078)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

You should probably re-run `src2asciidoc.py`.
</blockquote></details>

Done.

---

*[qutebrowser/completion/models/configmodel.py, line 31 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQl2A20TWcUJSaOG3V:-KtRNG-SPBR3iKN0Js7c:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L31)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

nitpick: Please call this `opt` instead of `x` so it's a bit more readable (as it's an `Option` object).
</blockquote></details>

Done.

---

*[qutebrowser/completion/models/configmodel.py, line 47 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQlB2gUkkbvvctqnsj:-KtRNMMWP-p0EGmGRWLj:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L47)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

Shouldn't this use `info.config.get_str` instead?
</blockquote></details>

Done.

---

*[qutebrowser/completion/models/configmodel.py, line 51 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQljZOs7PUlPYuhTih:-KtRN_HGquSVLFv2NQfE:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L51)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

`config.instance.get_opt(optname)` would be the proper API to use here - it doesn't really matter as it only re-raises `KeyError` as `NoOptionError` and we know the option exists, but I'd prefer using it anyways.
</blockquote></details>

Done.

---

*[qutebrowser/completion/models/configmodel.py, line 52 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQlt0OoWEI678plpDt:-KtRNv8a4W5BGzDYKJ5C:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L52)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

`opt.typ.to_str(opt.default)`?
</blockquote></details>

Done.

---

*[qutebrowser/completion/models/configmodel.py, line 71 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQmL1ai3yS8qCSdnsw:-KtROGLo-xQ8j0IgW-9B:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/completion/models/configmodel.py#L71)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

There's a new `def get_command(self, key, mode):` now.
</blockquote></details>

Done.

---

*[qutebrowser/mainwindow/tabbedbrowser.py, line 724 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQneNL6_Rr0HG95T2f:-KtRPRs3Xbr5AI3ONAIB:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/mainwindow/tabbedbrowser.py#L724)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

You re-added the `icon=''` here which was removed in 3a6bcb3dd0873776a5002c6bd55754634ae94e5c - I think that's incorrect.
</blockquote></details>

Done.

---

*[tests/end2end/features/downloads.feature, line 597 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQkllJG2S7neBbKLWh:-KtRQCl_WNTK61x2NwCK:b-896fix) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/tests/end2end/features/downloads.feature#L597)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

You removed a "When the unwritable dir is unwritable" from 3b53ec1cb6c136ffb12e46f3b532e546cb0bd421 here, causing a failure on AppVeyor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914)*

**Comment by rcorre** [comment]
*[qutebrowser/mainwindow/messageview.py, line 72 at r1](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtQnBmmL9rq2rNwp1St:-KtS5VLZWKJFZ3p9Y5r1:bi4huvn) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/a5ecb75fcd0b00b06359bf69331d7aa8fe7850e8/qutebrowser/mainwindow/messageview.py#L72)):*
<details><summary><i>Previously, The-Compiler (Florian Bruhin) wrote…</i></summary><blockquote>

I'm not confident yet whether the changes here are correct, i.e. whether they still contain the changes from https://github.com/qutebrowser/qutebrowser/pull/2808/files

I need to take a closer look, but I'm running out of time for today :wink:
</blockquote></details>

I think I got it right, there was one acidentally aded line that I just removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914)*

**Comment by The-Compiler** [comment]
Reviewed 8 of 9 files at r2.
Review status: 136 of 137 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[qutebrowser/misc/utilcmds.py, line 184 at r2](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914#-KtVn-tdNTNhZ7kK8gmo:-KtVn-tdNTNhZ7kK8gmp:bkbvikh) ([raw file](https://github.com/qutebrowser/qutebrowser/blob/deb6cccff9b2fdca843dce71f485d4ad64f0af70/qutebrowser/misc/utilcmds.py#L184)):*
> ```Python
>     log.misc.debug('_render_stylesheet: {}'.format(render_stylesheet_info))
>     log.misc.debug('history: {}'.format(history_info))
> ```

One blank line too much (see flake8) - but I can fix that up while merging unless you're quicker :wink:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914)*

**Comment by rcorre** [comment]
looks like the only things left are:

- Appveyor issue with statusbar height
- py34 segfault on exit
- eslint error

Which are all unrelated to the PR, if I understand correctly

**Comment by The-Compiler** [comment]
Reviewed 1 of 9 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qutebrowser/qutebrowser/2914)*

**Comment by The-Compiler** [comment]
Yeah, looks good now - thanks! 👍

**Pull request merged**
