### PR TITLE
Add a readability favicon

### PR DESCRIPTION
**Pull request by rien333**
I'm not sure whether you like my idea and/or approach, but I sometimes have slight difficulty recognizing what my readability tabs are. I thought a favicon might help me differentiate them from the rest. Moreover, most browser have a symbol that indicates them being in 'readability' mode. 

I've embedded the favicon as a base64 encoded svg. Not sure if you like this approach, but at least this allows the script to remain fairly "standalone".

 The icon is just the Mozilla readability icon, but with its color changed to white. (if I understand correctly, their license allows qutebrowser to redistribute it without any further requirements) 

Not sure about the color of the icon, but I went with pure white because it goes okay with the standard qutebrowser color scheme and has a lot of contrast. 

Feel free to just discard this PR btw, though I kinda like it myself.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Without this PR, does the tab get no favicon at all or the website's favicon? Can you link to the Mozilla license for that icon, or at least the location you got it from?

**Comment by rien333** [comment]
> Without this PR, does the tab get no favicon at all or the website's favicon?

There is no favicon at all. If you prefer, I could transfer the original icon, but this might get confusing. (or leave things as is, and show no icon)

Here is the link to the original icon used in firefox: https://github.com/mozilla/gecko-dev/blob/master/browser/themes/shared/reader/readerMode.svg

I didn't read the [MPL FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) right I think, so discard my previous comment about not having to do anything else. As I understand Q10 now, I would probably at least need to add a link to the license. 

The pale moon distrubtion (a "repackaged" firefox) also distributes this icon. I think I can just follow their approach, and add comments similar to here: https://github.com/Ascrod/readerview/commit/0128fe95a5bfc9fe4fb35962a9017540abeead53.

**Comment by The-Compiler** [comment]
Seems fine to me to have the readability icon then, and probably better than no icon!

I think we can figure out the licensing thing. What we're redistributing here is essentially a binary form. I'd indeed add a comment similar to the one you linked (except the "This Source Code Form", I guess), and also add a link to https://raw.githubusercontent.com/mozilla/gecko-dev/master/browser/themes/shared/reader/readerMode.svg - that should be enough.

**Comment by rien333** [comment]
Okay, I hope I did the licensing thing right, I don't really speak lawyer. Sorry to bother you about something so minor.

**Comment by The-Compiler** [comment]
No worries, seems like a good idea! I don't speak much legalese either, so I try to find a compromise between doing the proper legalese stuff and common sense :wink:

Thanks!

**Pull request merged**
