### PR TITLE
Window IDs start at one; tab-give uses count as-is

### PR DESCRIPTION
**Pull request by bodograumann**
Seems to work for me and tests ran ok afaict. (Little unhappy with only having python 3.9, not 3.8).
`1gD` now correctly gives to the window with `win_id == 1`.

This solves part of #4529. Doing the same change for tabs is also suggested, but `1gm` works fine. So not sure if the change makes sense there. The difference is also, that tabs are organized as a list and the user-facing tab_index afaics is already starting from `1`.

### CODE REVIEW

**Comment by bodograumann** [comment]
Ok, guess I'll have to work a bit more on the details.

**Comment by The-Compiler** [comment]
No idea off-hand what's going on with the tests I'm afraid. Please do the same change for the tab IDs as well though - it's very confusing to have one start at 0 and the other at 1 (for developers, that is). From the user's perspective it probably doesn't change much, as counts (as in `1gm`) take tab indices (changing numbers, only in the current window) rather than IDs (a continuing counter like with windows).

**Comment by bodograumann** [comment]
@The-Compiler Sure, I can understand that. Will just take some more time.
For the tests I already saw that at some place there is `window = 0` and I mostly looked at `win_id`, so I'm hopeful that I can fix it.

**Comment by joaonunatingscode** [comment]
@bodograumann what's the state of this? This is a draft, tell me if I can pick it up where you left it.

**Comment by bodograumann** [comment]
Wow, has it already been two years?
I just started going through all the places I found and updated the count to be 1-based.
You could try rebasing, but not sure if rebasing makes sense after all this time.
Please also consider the long-living feature branch qt6-v2.

Unfortunately there are too many other things I want to do and so I don't have time to continue here.
(Also I didn't really encounter the need for this change in real-live afaicr)
So feel free to pick it up. @joaonunatingscode

**Pull request closed without merging**
