### PR TITLE
Throttle autosaves to 60s

### PR DESCRIPTION
**Pull request by jgkamat**
This PR is dependent on #4498 and is currently just a single tiny commit on top of it (currently d7ebda9bd4f51f79b79a3d0299ce73808d92139f). Because of that, this needs to wait for #4498 to be resolved (at which point I'll re-do this tiny commit).

See https://github.com/qutebrowser/qutebrowser/issues/4535 for incentive.

2019-01-27-003304_844x821_scrot

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/4545)

### CODE REVIEW

**Comment by jgkamat** [comment]
Oh I completely forgot about #4087 when making this (sorry @toofar). Either one of these solutions will work, #4087 works by marking the session as dirty whenever it changes, and updating it every x seconds, while this will throttle the requests to x time. I'm not sure which way is preferred though. This method does have a cost on the first page load in the period. I could add an option to disable the first load (and go directly to a throttled delay) though. 

I'm fine with trashing this though, whatever we decide is better :)

**Comment by toofar** [comment]
#4087 also has a downside, it ties the autosave session to `auto_save.interval` so if that is `0` then the autosave feature will be disabled whereas previously you couldn't disable it. I'm fine with that personally but  when it was added in #2081 there was no provision for disabling it and I assume that was on purpose.

**Comment by jgkamat** [comment]
FWIW, I would prefer a seperate knob to tweak the rate of this save (and/or if it should be done), as it's very expensive for me. I would put it at every 10-30 min or so, but others probably wont.

**Comment by jgkamat** [comment]
Just a random note, it looks like chrome saves localstorage, cookies, and
other similar to disk on a 1 min interval as well, (that's my rationale for
60s being a good default...):

TIME     COMM           PID    T BYTES   OFF_KB   LAT(ms) FILENAME
23:50:01 TaskSchedulerB 31423  S 0       0          46.74 Cookies-journal
23:50:01 TaskSchedulerB 31423  S 0       0          23.59 Cookies-journal
23:50:01 TaskSchedulerB 31423  S 0       0          44.00 Cookies
23:50:01 TaskSchedulerB 31423  S 0       0          24.10 Cookies-journal
[snip]
23:51:01 TaskSchedulerB 31423  S 0       0          52.92 Cookies-journal
23:51:01 TaskSchedulerB 31423  S 0       0          17.74 Cookies-journal
23:51:01 TaskSchedulerB 31423  S 0       0          46.34 Cookies
23:51:01 TaskSchedulerB 31423  S 0       0          27.70 Cookies-journal

**Comment by The-Compiler** [comment]
Not sure about the interval (for people having more frequent crashes, 1min might be too slow?) - but let's merge it and see what people think. Thanks!

**Pull request merged**
