### PR TITLE
qute-pass: Escape backslashes in username and password

### PR DESCRIPTION
**Pull request by cryzed**
This was reported to me by someone via e-mail, this should hopefully take care of that issue. Maybe someone could chime in and tell me if I'm overlooking something.

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3858)

### CODE REVIEW

**Comment by cryzed** [comment]
@jgkamat what are the disadvantages of insert-text? It seems overall much better suited for this usecase?

**Comment by jgkamat** [comment]
@cryzed the main issue is that you have to delay subsequent insert-text's with `:later`, since they all happen at once and don't queue up like `fake-key` does.

It also might not work on some super fancy js textboxes, which aren't detected as editable by qutebrowser.

**Comment by cryzed** [comment]
Hold off of on merging this then, I'll also escape < and >. Any other keys I should be aware of?

**Comment by jgkamat** [comment]
I don't think you'll be able to escape them fully, for example, `\\<x\\>` leads to an error. There's also quotes, for example `"hello` fails (unless escaped). Spaces (unless quoted) may be an issue as well, and the `;;` pattern will cause issues too (which `insert-text` fails on as well).

**Comment by cryzed** [comment]
That's problematic, I'm unsure what to do then. Switching entirely to `insert-text` seems like a non-ideal solution as well... Could we maybe change `fake-key`or add a flag to it, that simply sends the string following it, without interpreting any special characters?

**Comment by jgkamat** [comment]
For `fake-key` we have to parse the keystring into [qt keys](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/commands.py#L2129), I'm not sure if there's an easy way to say "ignore special keys". If there is though, it would be easy to add it.

**Comment by cryzed** [comment]
Okay, this is the simplest solution I could come up with. In practice, I don't notice any slowdowns and this seems to avoid all escaping issues entirely.

**Comment by jgkamat** [comment]
Hmm, at least for quotes, I think this would break, for example, `:fake-key "` dosen't insert a quote. Spaces as well (`:fake-key` with two spaces does nothing as well).

**Comment by cryzed** [comment]
So escaping " and spaces with \ should work? Kind of frustrating...

**Comment by cryzed** [comment]
> I don't like the approach here (looping over all the chars manually like this), but I'm fine with having it in because it seems to work, if you think its OK.

Believe me, I'm not a fan either. If you have a different method that is just as reliable, let me know.

> This will probably break for other nonprinting characters as well (like tabs), but I think websites will break on those before we do :P

I have never seen a tab used in username or passwords, so I agree with you.

> Are you fine with putting this in? I'd like to get one other person (preferrably someone who uses qute-pass to look this over as well and test it out).

I am fine with putting this in, yes, since it seems to work perfectly fine for me (performance and accuracy-wise). I also think that escaping all characters besides space by default should hopefully prevent future headaches if we come across any that hold some special meaning to Qt. I'll contact the person who initially made me aware of the problem and see if they can maybe comment here.

**Comment by The-Compiler** [comment]
I'm still not too keen about using userscripts to fill passwords (because of issues like this), but I can't blame you, as there's no other way yet. It's really time for a proper plugin API :laughing: 

Going to merge this as it looks fine, thanks!

**Pull request merged**
