### PR TITLE
Rename :buffer to :tab-select

### LINKED ISSUE #2907: Rename/rebind :buffer
`:buffer` doesn't really have a qutebrowser-like name, it should probably be called `:tab-select` or so. Also, it seems its `gt` binding isn't really known, but `T` to focus tabs is.

The current default behaviour of `T` is to focus the first tab, which probably isn't too useful. It might be a good idea to bind `T` without a count to do what `gt` does.

### PR DESCRIPTION
**Pull request by cryzed**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/2910)

(edit by @jgkamat: Closes #2907)

### CODE REVIEW

**Comment by NoctuaNivalis** [comment]
#2907 because links are awesome.

**Comment by jgkamat** [comment]
Hmm, it seems like a bunch of tests broke in this PR (but the change looks good). Perhaps the tests need to be updated to use the new format? I'd be happy to take a look at that tonight, but I'm a bit busy right now :)

**Comment by cryzed** [comment]
That would be appreciated @jgkamat!

**Comment by jgkamat** [comment]
Seems like a few more tests are failing,

```
FAIL tests/end2end/features/test_tabs_bdd.py::test_tabfocus_without_indexcount
FAIL tests/end2end/features/test_tabs_bdd.py::test_tabselect_without_args
```

Sounds like there are problems with the no args case, I'll try to figure those out later

**Comment by jgkamat** [comment]
Ok, the default behavior change is intentional, per #2907. But I have a comment.

Now, it seems that `:tab-select` and `:tab-focus` seem to do exactly the same thing (when no args, focus just calls select). The only difference I see is that `:tab-focus` uses a `[count]` while `:tab-select` takes an index.

I suggest doing the following (but I think we should wait for @The-Compiler's opinion before doing anything).

1. Remove `:tab-focus` completely
2. Update `:tab-select` to take either a count or an index.
3. If a count and index is provided, prefer the count to the index.
4. Bind 'T' to set the command text to `:tab-select`

thoughts? There might be a cleaner way to do this that I'm not considering.

**Comment by The-Compiler** [comment]
There also is some discussion about this in #1317 but I don't have the time to read through it at the moment.

The main difference is that `:tab-select` takes a `win/tab` index, and `:tab-focus` only takes a tab index. Since `:tab-focus` doesn't have any completion at the moment, I guess it's fine to merge `:buffer`/`:tab-select` into it thinking about it again... And once a completion can get a window ID, we can just show the tabs for the current window at the top of the `:tab-focus` completion.

Also cc'ing @rcorre and @toofar

**Comment by rcorre** [comment]
Based on the discussion, it sounds like `tab-select`, `tab-focus`, and `buffer` can all be merged into one command, which:

1. Given a count, focuses that tab in the current window
2. Given no count, takes an arg of form [win-id]/[tab-id], using `buffer` completion, modified to show the current window first. 

In order to do this, completion functions must be provided some sort of `CompletionContext`, which has come up several times now (and might resolve some circular import issues I've been hitting in the `new-config` branch).

Am I understanding correctly?

**Comment by The-Compiler** [comment]
@rcorre You mean something like #2814? Yeah, that'd be needed at least for the "show the current window first" part. Also, `:tab-focus 2` should probably still focus the second tab of the current window, without needing a window ID.

As for the circular import issue, open a new issue here if you need help. Also note we're dropping Python 3.4 soon anyways, so if it's a Python 3.4 only thing, you might want to just ignore it.

**Comment by reed9999** [comment]
Just curious, is there any reason not to support :buffer as a synonym for backwards compatibility? From https://github.com/cryzed/qutebrowser/pull/2 I infer the intention is no longer to support the old name, or at least to test that it doesn't break. :)

@jgkamat

**Comment by jgkamat** [comment]
@reed9999 I think that's its reasonable to keep `:buffer` as a default alias to `:tab-focus`. This is more so we don't have multiple definitions for the same thing in the language. 

I don't think aliases support completion right now though.

**Comment by The-Compiler** [comment]
I'd prefer avoiding keeping legacy stuff around - if someone is really used to `:buffer` they can still add an alias, but having multiple commands which do the same is just confusing for users, IMHO.

What I usually did in the past is keeping the old name around with a deprecation warning shown and then removing it in the following release, but since the next release is v1.0.0 and going to break stuff anyways, I wouldn't bother at all.

**Comment by reed9999** [comment]
@jgkamat @The-Compiler 
Thanks. I just ask to improve my understanding of modern open-source software engineering practices. :) I don't have any investment one way or the other, just wondered.

**Comment by The-Compiler** [comment]
Quick update: I'm back from my exams and merged the new config - there are at least three PRs related to `:tab-` commands in some way: #2648, #2910 and #2937.

I intend to merge some other PRs today (which don't conflict), and then look at the PR and merge them one-by-one, starting with the oldest one. Please don't rebase on the latest master before that, or you'll just have conflicts again.

Sorry for the pain, but yeah, I knew why I asked people to hold back PRs for a bit :wink:

**Comment by jgkamat** [comment]
No problem, I think this PR also needs more thought (and might need to be re-done), so I'm fine with resolving all the conflicts once everyone else is done :)

**Comment by cryzed** [comment]
It's no issue to close this, so someone can create a new pull request for this.

**Comment by The-Compiler** [comment]
@jgkamat Do you want to pick this up once the other related PRs are in?

**Comment by jgkamat** [comment]
yup, I'm happy to take this over, it might be a little while before I get to it though, since I'm a bit busy with classwork (and I would like to get the other PR's i'm working on in first, since I feel like they are a bit more important).

**Comment by The-Compiler** [comment]
sure, no hurry!

**Comment by The-Compiler** [comment]
This conflicts now that #3024 is in and @jgkamat volunteered to redo it :wink:
Closing this now - thanks a lot @cryzed though!

**Pull request closed without merging**
