### PR TITLE
Reload configuration on USR1 signal

### PR DESCRIPTION
**Pull request by sphaugh**
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3157)

### CODE REVIEW

**Comment by neeasade** [comment]
this would be nice. I've been doing dance where I bind reload to a keybind and have xdotool find and send that keybind to qutebrowser.

**Comment by mschilli87** [comment]
isn't SIGUSR1 [already used](https://github.com/qutebrowser/qutebrowser/blob/35d5038ab13718918d176ea7c1900b32e692d348/qutebrowser/misc/earlyinit.py#L125)?

**Comment by pkillnine** [comment]
you can already send commands to a running qutebrowser instance by running for example `qutebrowser :config-reload`.

**Comment by lahwaacz** [comment]
And with `:bind` you can make a binding without xdotool or whatever.

**Comment by neeasade** [comment]
> you can already send commands to a running qutebrowser instance by running for example qutebrowser :config-reload.

ah! very cool.

> And with :bind you can make a binding without xdotool or whatever.

xdotool was to send the keybind, not create it. This was as of a year or so ago (could you send commands to qutebrowser like above then?), I made a userscript to load from xrdb and bound it, and then would xdotool send the bind.

**Comment by The-Compiler** [comment]
FWIW passing commands to a running instance was possible since c3ce167926b3cc476ef1c6b8606b872891e8a419 which was before v0.1 :wink:

**Comment by neeasade** [comment]
TIL, that's great.

**Comment by sphaugh** [comment]
@The-Compiler It's a little slower than sending a signal (~a second) and steals focus though, is there anything we could do about that?

**Pull request closed without merging**
